TextFrame_Object = element TextFrame { attribute Self { xsd:string },
    attribute ParentStory { xsd:string }?,
    attribute PreviousTextFrame { xsd:string }?,
    attribute NextTextFrame { xsd:string }?,
    attribute ContentType { ContentType_EnumValue }?,
    attribute AllowOverrides { xsd:boolean }?,
    attribute FillColor { xsd:string }?,
    attribute FillTint { xsd:double }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute CornerRadius { xsd:double }?,
    attribute StrokeWeight { xsd:double }?,
    attribute MiterLimit { xsd:double {minInclusive="1" maxInclusive="500" } }?,
    attribute EndCap { EndCap_EnumValue }?,
    attribute EndJoin { EndJoin_EnumValue }?,
    attribute StrokeType { xsd:string }?,
    attribute StrokeCornerAdjustment { StrokeCornerAdjustment_EnumValue }?,
    attribute StrokeDashAndGap { list { xsd:double * } }?,
    attribute LeftLineEnd { ArrowHead_EnumValue }?,
    attribute RightLineEnd { ArrowHead_EnumValue }?,
    attribute StrokeColor { xsd:string }?,
    attribute StrokeTint { xsd:double }?,
    attribute GradientFillStart { UnitPointType_TypeDef }?,
    attribute GradientFillLength { xsd:double }?,
    attribute GradientFillAngle { xsd:double }?,
    attribute GradientStrokeStart { UnitPointType_TypeDef }?,
    attribute GradientStrokeLength { xsd:double }?,
    attribute GradientStrokeAngle { xsd:double }?,
    attribute OverprintStroke { xsd:boolean }?,
    attribute GapColor { xsd:string }?,
    attribute GapTint { xsd:double }?,
    attribute OverprintGap { xsd:boolean }?,
    attribute StrokeAlignment { StrokeAlignment_EnumValue }?,
    attribute Nonprinting { xsd:boolean }?,
    attribute ItemLayer { xsd:string }?,
    attribute Locked { xsd:boolean }?,
    attribute LocalDisplaySetting { DisplaySettingOptions_EnumValue }?,
    attribute GradientFillHiliteLength { xsd:double }?,
    attribute GradientFillHiliteAngle { xsd:double }?,
    attribute GradientStrokeHiliteLength { xsd:double }?,
    attribute GradientStrokeHiliteAngle { xsd:double }?,
    attribute AppliedObjectStyle { xsd:string }?,
    attribute CornerOption { CornerOptions_EnumValue }?,
    attribute Visible...
