TextFramePreference_Object = element TextFramePreference { attribute TextColumnCount { xsd:int {minInclusive="1" maxInclusive="40" } }?,
    attribute TextColumnGutter { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute TextColumnFixedWidth { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute UseFixedColumnWidth { xsd:boolean }?,
    attribute FirstBaselineOffset { FirstBaseline_EnumValue }?,
    attribute MinimumFirstBaselineOffset { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute VerticalJustification { VerticalJustification_EnumValue }?,
    attribute VerticalThreshold { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute IgnoreWrap { xsd:boolean }?,
    attribute UseFlexibleColumnWidth { xsd:boolean }?,
    attribute TextColumnMaxWidth { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute AutoSizingType { AutoSizingTypeEnum_EnumValue }?,
    attribute AutoSizingReferencePoint { AutoSizingReferenceEnum_EnumValue }?,
    attribute UseMinimumHeightForAutoSizing { xsd:boolean }?,
    attribute MinimumHeightForAutoSizing { xsd:double }?,
    attribute UseMinimumWidthForAutoSizing { xsd:boolean }?,
    attribute MinimumWidthForAutoSizing { xsd:double }?,
    attribute UseNoLineBreaksForAutoSizing { xsd:boolean }?,
    attribute VerticalBalanceColumns { xsd:boolean }?,
    element Properties { element InsetSpacing { (unit_type,
                xsd:double {minInclusive="0" maxInclusive="8640" } ) |
            (list_type,
                element ListItem { unit_type,
                    xsd:double {minInclusive="0" maxInclusive="8640" } },
                element ListItem { unit_type,
                    xsd:double {minInclusive="0" maxInclusive="8640" } },
                element ListItem { unit_type,
                    xsd:double {minInclusive="0" maxInclusive="8640" } },
                element ListItem { unit_type,
                    xsd:double {minInclusive="0" maxInclusive="8640" } } ) }? } ? }
