# frozen_string_literal: true

module Idml
  module Parts
    # Typed model for the package's `designmap.xml` part. The file's
    # root is `<Document>` directly (no `<idPkg:Document>` wrapper
    # unlike other parts). Every attribute from `Document_Object` in
    # `reference-docs/schemas/package/designmap.rnc` is declared,
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Designmap < Lutaml::Model::Serializable
      include Idml::Part

      part_file "designmap.xml"

      attribute :dom_version, :string
      attribute :self_attr, :string
      attribute :story_list, :string
      attribute :full_name, :string
      attribute :visible, :boolean
      attribute :file_path, :string
      attribute :modified, :boolean
      attribute :saved, :boolean
      attribute :name, :string
      attribute :zero_point, :string
      attribute :active_layer, :string
      attribute :unused_swatches, :string
      attribute :converted, :boolean
      attribute :recovered, :boolean
      attribute :read_only, :boolean
      attribute :id_attr, :integer
      attribute :cmyk_profile_list, :string
      attribute :rgb_profile_list, :string
      attribute :cmyk_profile, :string
      attribute :rgb_profile, :string
      attribute :solid_color_intent, :string
      attribute :after_blending_intent, :string
      attribute :default_image_intent, :string
      attribute :rgb_policy, :string
      attribute :cmyk_policy, :string
      attribute :accurate_lab_spots, :boolean
      attribute :selected_page_items, :string
      attribute :transparency_attribute_default_property, :string
      attribute :applied_math_ml_font_size, :float
      attribute :applied_math_ml_rgb_color, :string
      attribute :tint_value, :float
      attribute :prefer_math_ml_in_epub_export, :boolean
      attribute :active_process, :string

      attribute :layer, Idml::Elements::Layer, collection: true
      attribute :bookmark, Idml::Elements::Bookmark, collection: true
      attribute :condition, Idml::Elements::Condition, collection: true
      attribute :hyperlink, Idml::Elements::Hyperlink, collection: true
      attribute :hyperlink_page_destination,
                Idml::Elements::HyperlinkPageDestination, collection: true
      attribute :hyperlink_url_destination,
                Idml::Elements::HyperlinkURLDestination, collection: true

      xml do
        root "Document"
        map_attribute "DOMVersion", to: :dom_version
        map_attribute "Self", to: :self_attr
        map_attribute "StoryList", to: :story_list
        map_attribute "FullName", to: :full_name
        map_attribute "Visible", to: :visible
        map_attribute "FilePath", to: :file_path
        map_attribute "Modified", to: :modified
        map_attribute "Saved", to: :saved
        map_attribute "Name", to: :name
        map_attribute "ZeroPoint", to: :zero_point
        map_attribute "ActiveLayer", to: :active_layer
        map_attribute "UnusedSwatches", to: :unused_swatches
        map_attribute "Converted", to: :converted
        map_attribute "Recovered", to: :recovered
        map_attribute "ReadOnly", to: :read_only
        map_attribute "Id", to: :id_attr
        map_attribute "CMYKProfileList", to: :cmyk_profile_list
        map_attribute "RGBProfileList", to: :rgb_profile_list
        map_attribute "CMYKProfile", to: :cmyk_profile
        map_attribute "RGBProfile", to: :rgb_profile
        map_attribute "SolidColorIntent", to: :solid_color_intent
        map_attribute "AfterBlendingIntent", to: :after_blending_intent
        map_attribute "DefaultImageIntent", to: :default_image_intent
        map_attribute "RGBPolicy", to: :rgb_policy
        map_attribute "CMYKPolicy", to: :cmyk_policy
        map_attribute "AccurateLABSpots", to: :accurate_lab_spots
        map_attribute "SelectedPageItems", to: :selected_page_items
        map_attribute "TransparencyAttributeDefaultProperty",
                      to: :transparency_attribute_default_property
        map_attribute "AppliedMathMLFontSize", to: :applied_math_ml_font_size
        map_attribute "AppliedMathMLRgbColor", to: :applied_math_ml_rgb_color
        map_attribute "TintValue", to: :tint_value
        map_attribute "PreferMathMLInEpubExport", to: :prefer_math_ml_in_epub_export
        map_attribute "ActiveProcess", to: :active_process
        map_element "Layer", to: :layer
        map_element "Bookmark", to: :bookmark
        map_element "Condition", to: :condition
        map_element "Hyperlink", to: :hyperlink
        map_element "HyperlinkPageDestination",
                    to: :hyperlink_page_destination
        map_element "HyperlinkURLDestination",
                    to: :hyperlink_url_destination
      end
    end
  end
end
