Tint_Object = element Tint { attribute Self { xsd:string }, attribute TintValue { xsd:double {minInclusive="0" maxInclusive="100"} }?, attribute BaseColor { xsd:string }, attribute Name { xsd:string }, attribute ColorOverride { ColorOverride_EnumValue }?, attribute SpotInkAliasSpotColorReference { xsd:string }?, attribute AlternateSpace { ColorSpace_EnumValue }?, attribute AlternateColorValue { list { xsd:double * } }?, attribute ColorEditable { xsd:boolean }?, attribute ColorRemovable { xsd:boolean }?, attribute Visible { xsd:boolean }?, attribute SwatchCreatorID { xsd:int }?, element Properties { element Label { element KeyValuePair { KeyValuePair_TypeDef }* }? } ? }
