Ink_Object = element Ink { attribute Self { xsd:string }, attribute Name { xsd:string }, attribute AliasInkName { xsd:string }?, attribute Angle { xsd:double {minInclusive="0" maxInclusive="360"} }?, attribute ConvertToProcess { xsd:boolean }?, attribute Frequency { xsd:double {minInclusive="1" maxInclusive="500"} }?, attribute NeutralDensity { xsd:double {minInclusive="0.001" maxInclusive="10"} }?, attribute PrintInk { xsd:boolean }?, attribute TrapOrder { xsd:int }?, attribute InkType { InkTypes_EnumValue }?, element Properties { element Label { element KeyValuePair { KeyValuePair_TypeDef }* }? } ? }
