Story_Object = element Story { attribute Self { xsd:string },
    attribute AppliedTOCStyle { xsd:string }?,
    attribute FontStyle { xsd:string }?,
    attribute PointSize { xsd:double }?,
    attribute KerningMethod { xsd:string }?,
    attribute Tracking { xsd:double }?,
    attribute Capitalization { Capitalization_EnumValue }?,
    attribute Position { Position_EnumValue }?,
    attribute Underline { xsd:boolean }?,
    attribute StrikeThru { xsd:boolean }?,
    attribute Ligatures { xsd:boolean }?,
    attribute NoBreak { xsd:boolean }?,
    attribute HorizontalScale { xsd:double }?,
    attribute VerticalScale { xsd:double }?,
    attribute BaselineShift { xsd:double }?,
    attribute Skew { xsd:double }?,
    attribute FillTint { xsd:double }?,
    attribute StrokeTint { xsd:double }?,
    attribute StrokeWeight { xsd:double }?,
    attribute OverprintStroke { xsd:boolean }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute OTFFigureStyle { OTFFigureStyle_EnumValue }?,
    attribute OTFOrdinal { xsd:boolean }?,
    attribute OTFFraction { xsd:boolean }?,
    attribute OTFDiscretionaryLigature { xsd:boolean }?,
    attribute OTFTitling { xsd:boolean }?,
    attribute OTFContextualAlternate { xsd:boolean }?,
    attribute OTFSwash { xsd:boolean }?,
    attribute UnderlineTint { xsd:double }?,
    attribute UnderlineGapTint { xsd:double }?,
    attribute UnderlineOverprint { xsd:boolean }?,
    attribute UnderlineGapOverprint { xsd:boolean }?,
    attribute UnderlineOffset { xsd:double }?,
    attribute UnderlineWeight { xsd:double }?,
    attribute StrikeThroughTint { xsd:double }?,
    attribute StrikeThroughGapTint { xsd:double }?,
    attribute StrikeThroughOverprint { xsd:boolean }?,
    attribute StrikeThroughGapOverprint { xsd:boolean }?,
    attribute StrikeThroughOffset { xsd:double }?,
    attribute StrikeThroughWeight { xsd:double }?,
    attribute FillColor { xsd:string }?,
    attribute StrokeColor { xsd:string }?,
    attribute AppliedLanguage { xsd:string }?,
    attribute ParagraphKashidaWidth { xsd:double }?,
    attribute FirstLineIndent { xsd:double }?,
    attribute LeftIndent { xsd:double }?,
    attribute RightIndent { xsd:double }?,
    attribute StartIndent { xsd:double }?,
    attribute EndIndent { xsd:double }?,
    attribute SpaceBefore { xsd:double }?,
    attribute SpaceAfter { xsd:double }?,
    attribute Justification { Justification_EnumValue }?,
    attribute SingleLineAlignment { SingleLineAlignment_EnumValue }?,
    attribute AutoLeading { xsd:double }?,
    attribute Leading { xsd:double }?,
    attribute LeadingType { LeadingType_EnumValue }?,
    attribute DropCapLines { xsd:int }?,
    attribute DropCapChars { xsd:int }?,
    attribute KeepFirstLines { xsd:int }?,
    attribute KeepLastLines { xsd:int }?,
    attribute KeepWithNext { xsd:int }?,
    attribute KeepTogether { xsd:boolean }?,
    attribute SpanColumnType { SpanColumnType_EnumValue }?,
    attribute SplitColumnInsideFirst { xsd:double }?,
    attribute SplitColumnInsideLast { xsd:double }?,
    attribute SplitColumnOutsideFirst { xsd:double }?,
    attribute SplitColumnOutsideLast { xsd:double }?,
    attribute MinimumGlyphScaling { xsd:double }?,
    attribute MaximumGlyphScaling { xsd:double }?,
    attribute MinimumWordScaling { xsd:double }?,
    attribute MaximumWordScaling { xsd:double }?,
    attribute DesiredGlyphScaling { xsd:double }?,
    attribute DesiredWordScaling { xsd:double }?,
    attribute DesiredLetterScaling { xsd:double }?,
    attribute AutoWordJustification { AutoJustification_EnumValue }?,
    attribute FlagNormal { xsd:boolean }?,
    attribute FlagParagraphStyle { xsd:boolean }?,
    attribute AppliedParagraphStyle { xsd:string }?,
    attribute AppliedFont { xsd:string }?,
    attribute TabList { xsd:string }?,
    ( Footnote_Object* &
        Note_Object* &
        Table_Object* &
        AnchoredObjectSetting_Object* &
        TextVariableInstance_Object* &
        Change_Object* &
        HiddenText_Object* &
        XMLElement_Object* &
        XMLInstruction_Object* &
        XMLComment_Object* &
        ParagraphStyleRange_Object* &
        CharacterStyleRange_Object* ) }
