Table_Object = element Table { attribute Self { xsd:string },
    attribute HeaderRowCount { xsd:int {minInclusive="0" maxInclusive="25" } }?,
    attribute FooterRowCount { xsd:int {minInclusive="0" maxInclusive="25" } }?,
    attribute TopBorderStrokeWeight { xsd:double }?,
    attribute TopBorderStrokeType { xsd:string }?,
    attribute TopBorderStrokeColor { xsd:string }?,
    attribute TopBorderStrokeTint { xsd:double }?,
    attribute TopBorderStrokeOverprint { xsd:boolean }?,
    attribute TopBorderStrokeGapColor { xsd:string }?,
    attribute TopBorderStrokeGapTint { xsd:double }?,
    attribute TopBorderStrokeGapOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeWeight { xsd:double }?,
    attribute LeftBorderStrokeType { xsd:string }?,
    attribute LeftBorderStrokeColor { xsd:string }?,
    attribute LeftBorderStrokeTint { xsd:double }?,
    attribute LeftBorderStrokeOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeGapColor { xsd:string }?,
    attribute LeftBorderStrokeGapTint { xsd:double }?,
    attribute LeftBorderStrokeGapOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeWeight { xsd:double }?,
    attribute BottomBorderStrokeType { xsd:string }?,
    attribute BottomBorderStrokeColor { xsd:string }?,
    attribute BottomBorderStrokeTint { xsd:double }?,
    attribute BottomBorderStrokeOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeGapColor { xsd:string }?,
    attribute BottomBorderStrokeGapTint { xsd:double }?,
    attribute BottomBorderStrokeGapOverprint { xsd:boolean }?,
    attribute RightBorderStrokeWeight { xsd:double }?,
    attribute RightBorderStrokeType { xsd:string }?,
    attribute RightBorderStrokeColor { xsd:string }?,
    attribute RightBorderStrokeTint { xsd:double }?,
    attribute RightBorderStrokeOverprint { xsd:boolean }?,
    attribute RightBorderStrokeGapColor { xsd:string }?,
    attribute RightBorderStrokeGapTint { xsd:double }?,
    attribute RightBorderStrokeGapOverprint { xsd:boolean }?,
    attribute SpaceBefore { xsd:double }?,
    attribute SpaceAfter { xsd:double }?,
    attribute SkipFirstAlternatingStrokeRows { xsd:int }?,
    attribute SkipLastAlternatingStrokeRows { xsd:int }?,
    attribute FirstAlternatingStrokeRows { xsd:int }?,
    attribute LastAlternatingStrokeRows { xsd:int }?,
    attribute StrokeOrder { StrokeOrder_EnumValue }?,
    attribute ColumnCount { xsd:int }?,
    attribute RowCount { xsd:int }?,
    attribute MattingColor { xsd:string }?,
    attribute MattingWidth { xsd:double }?,
    attribute ApplyToAllRows { xsd:boolean }?,
    attribute ApplyToAllColumns { xsd:boolean }?,
    attribute ApplyToAllLevelRows { xsd:boolean }?,
    attribute ApplyToAllLevelColumns { xsd:boolean }?,
    ( Row_Object* &
        Column_Object* &
        Cell_Object* ) }
