Cell_Object = element Cell { attribute Self { xsd:string },
    attribute Name { xsd:string },
    attribute RowSpan { xsd:int }?,
    attribute ColumnSpan { xsd:int }?,
    attribute TopInset { xsd:double }?,
    attribute LeftInset { xsd:double }?,
    attribute BottomInset { xsd:double }?,
    attribute RightInset { xsd:double }?,
    attribute FillColor { xsd:string }?,
    attribute FillTint { xsd:double }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute TopLeftDiagonalLine { xsd:boolean }?,
    attribute TopRightDiagonalLine { xsd:boolean }?,
    attribute DiagonalLineInFront { xsd:boolean }?,
    attribute DiagonalLineStrokeWeight { xsd:double }?,
    attribute DiagonalLineStrokeType { xsd:string }?,
    attribute DiagonalLineStrokeColor { xsd:string }?,
    attribute DiagonalLineStrokeTint { xsd:double }?,
    attribute DiagonalLineStrokeOverprint { xsd:boolean }?,
    attribute DiagonalLineStrokeGapColor { xsd:string }?,
    attribute DiagonalLineStrokeGapTint { xsd:double }?,
    attribute DiagonalLineStrokeGapOverprint { xsd:boolean }?,
    attribute ClipContentToCell { xsd:boolean }?,
    attribute FirstBaselineOffset { FirstBaseline_EnumValue }?,
    attribute VerticalJustification { VerticalJustification_EnumValue }?,
    attribute ParagraphSpacingLimit { xsd:double }?,
    attribute MinimumFirstBaselineOffset { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute RotationAngle { xsd:double }?,
    attribute LeftEdgeStrokeWeight { xsd:double }?,
    attribute LeftEdgeStrokeType { xsd:string }?,
    attribute LeftEdgeStrokeColor { xsd:string }?,
    attribute LeftEdgeStrokeTint { xsd:double }?,
    attribute LeftEdgeStrokeOverprint { xsd:boolean }?,
    attribute LeftEdgeStrokeGapColor { xsd:string }?,
    attribute LeftEdgeStrokeGapTint { xsd:double }?,
    attribute LeftEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute TopEdgeStrokeWeight { xsd:double }?,
    attribute TopEdgeStrokeType { xsd:string }?,
    attribute TopEdgeStrokeColor { xsd:string }?,
    attribute TopEdgeStrokeTint { xsd:double }?,
    attribute TopEdgeStrokeOverprint { xsd:boolean }?,
    attribute TopEdgeStrokeGapColor { xsd:string }?,
    attribute TopEdgeStrokeGapTint { xsd:double }?,
    attribute TopEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute RightEdgeStrokeWeight { xsd:double }?,
    attribute RightEdgeStrokeType { xsd:string }?,
    attribute RightEdgeStrokeColor { xsd:string }?,
    attribute RightEdgeStrokeTint { xsd:double }?,
    attribute RightEdgeStrokeOverprint { xsd:boolean }?,
    attribute RightEdgeStrokeGapColor { xsd:string }?,
    attribute RightEdgeStrokeGapTint { xsd:double }?,
    attribute RightEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute BottomEdgeStrokeWeight { xsd:double }?,
    attribute BottomEdgeStrokeType { xsd:string }?,
    attribute BottomEdgeStrokeColor { xsd:string }?,
    attribute BottomEdgeStrokeTint { xsd:double }?,
    attribute BottomEdgeStrokeOverprint { xsd:boolean }?,
    attribute BottomEdgeStrokeGapColor { xsd:string }?,
    attribute BottomEdgeStrokeGapTint { xsd:double }?,
    attribute BottomEdgeStrokeGapOverprint { xsd:boolean }?,
    ( Footnote_Object* &
        Note_Object* &
        TextVariableInstance_Object* &
        ParagraphStyleRange_Object* &
        CharacterStyleRange_Object* &
        HiddenText_Object* ) }
