Column_Object = element Column { attribute Self { xsd:string },
    attribute Name { xsd:string },
    attribute TopInset { xsd:double }?,
    attribute LeftInset { xsd:double }?,
    attribute BottomInset { xsd:double }?,
    attribute RightInset { xsd:double }?,
    attribute FillColor { xsd:string }?,
    attribute FillTint { xsd:double }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute TopLeftDiagonalLine { xsd:boolean }?,
    attribute TopRightDiagonalLine { xsd:boolean }?,
    attribute DiagonalLineInFront { xsd:boolean }?,
    attribute DiagonalLineStrokeWeight { xsd:double }?,
    attribute DiagonalLineStrokeType { xsd:string }?,
    attribute DiagonalLineStrokeColor { xsd:string }?,
    attribute DiagonalLineStrokeTint { xsd:double }?,
    attribute DiagonalLineStrokeOverprint { xsd:boolean }?,
    attribute DiagonalLineStrokeGapColor { xsd:string }?,
    attribute DiagonalLineStrokeGapTint { xsd:double }?,
    attribute DiagonalLineStrokeGapOverprint { xsd:boolean }?,
    attribute ClipContentToCell { xsd:boolean }?,
    attribute FirstBaselineOffset { FirstBaseline_EnumValue }?,
    attribute VerticalJustification { VerticalJustification_EnumValue }?,
    attribute ParagraphSpacingLimit { xsd:double }?,
    attribute MinimumFirstBaselineOffset { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute RotationAngle { xsd:double }?,
    attribute WritingDirection { xsd:boolean }?,
    attribute SingleColumnWidth { xsd:double }? }
