AnchoredObjectSetting_Object = element AnchoredObjectSetting { attribute AnchoredPosition { AnchorPosition_EnumValue }?,
    attribute SpineRelative { xsd:boolean }?,
    attribute LockPosition { xsd:boolean }?,
    attribute PinPosition { xsd:boolean }?,
    attribute AnchorPoint { AnchorPoint_EnumValue }?,
    attribute HorizontalAlignment { HorizontalAlignment_EnumValue }?,
    attribute HorizontalReferencePoint { AnchoredRelativeTo_EnumValue }?,
    attribute VerticalAlignment { VerticalAlignment_EnumValue }?,
    attribute VerticalReferencePoint { VerticallyRelativeTo_EnumValue }?,
    attribute AnchorXoffset { xsd:double }?,
    attribute AnchorYoffset { xsd:double }?,
    attribute AnchorSpaceAbove { xsd:double }? }
