Font_Object = element Font { attribute Self { xsd:string }, attribute FontFamily { xsd:string }?, attribute Name { xsd:string }?, attribute PostScriptName { xsd:string }?, attribute Status { FontStatus_EnumValue }?, attribute FontStyleName { xsd:string }?, attribute FontType { FontTypes_EnumValue }?, attribute WritingScript { xsd:int }?, attribute FullName { xsd:string }?, attribute FullNameNative { xsd:string }?, attribute FontStyleNameNative { xsd:string }?, attribute PlatformName { xsd:string }?, attribute Version { xsd:string }? }
