CompositeFontEntry_Object = element CompositeFontEntry { attribute Self { xsd:string }, attribute Name { xsd:string }?, attribute FontStyle { xsd:string }?, attribute RelativeSize { xsd:double }?, attribute HorizontalScale { xsd:double }?, attribute VerticalScale { xsd:double }?, attribute CustomCharacters { xsd:string }?, attribute Locked { xsd:boolean }?,
attribute ScaleOption { xsd:boolean }?, attribute BaselineShift { xsd:double }?, element Properties { element AppliedFont { (object_type, xsd:string ) | (string_type, xsd:string ) }?& element Label { element KeyValuePair { KeyValuePair_TypeDef }* }? } ? }
