TableStyle_Object = element TableStyle {
    attribute Self { xsd:string },
    attribute Name { xsd:string },
    attribute StrokeOrder { StrokeOrderTypes_EnumValue }?,
    attribute TopBorderStrokeWeight { xsd:double }?,
    attribute TopBorderStrokeType { xsd:string }?,
    attribute TopBorderStrokeColor { xsd:string }?,
    attribute TopBorderStrokeTint { xsd:double }?,
    attribute TopBorderStrokeOverprint { xsd:boolean }?,
    attribute TopBorderStrokeGapColor { xsd:string }?,
    attribute TopBorderStrokeGapTint { xsd:double }?,
    attribute TopBorderStrokeGapOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeWeight { xsd:double }?,
    attribute LeftBorderStrokeType { xsd:string }?,
    attribute LeftBorderStrokeColor { xsd:string }?,
    attribute LeftBorderStrokeTint { xsd:double }?,
    attribute LeftBorderStrokeOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeGapColor { xsd:string }?,
    attribute LeftBorderStrokeGapTint { xsd:double }?,
    attribute LeftBorderStrokeGapOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeWeight { xsd:double }?,
    attribute BottomBorderStrokeType { xsd:string }?,
    attribute BottomBorderStrokeColor { xsd:string }?,
    attribute BottomBorderStrokeTint { xsd:double }?,
    attribute BottomBorderStrokeOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeGapColor { xsd:string }?,
    attribute BottomBorderStrokeGapTint { xsd:double }?,
    attribute BottomBorderStrokeGapOverprint { xsd:boolean }?,
    attribute RightBorderStrokeWeight { xsd:double }?,
    attribute RightBorderStrokeType { xsd:string }?,
    attribute RightBorderStrokeColor { xsd:string }?,
    attribute RightBorderStrokeTint { xsd:double }?,
    attribute RightBorderStrokeOverprint { xsd:boolean }?,
    attribute RightBorderStrokeGapColor { xsd:string }?,
    attribute RightBorderStrokeGapTint { xsd:double }?,
    attribute RightBorderStrokeGapOverprint { xsd:boolean }?,
    attribute SpaceBefore { xsd:double }?,
    attribute SpaceAfter { xsd:double }?,
    attribute SkipFirstAlternatingStrokeRows { xsd:int }?,
    attribute SkipLastAlternatingStrokeRows { xsd:int }?,
    attribute StartRowStrokeCount { xsd:int }?,
    attribute StartRowStrokeColor { xsd:string }?,
    attribute StartRowStrokeWeight { xsd:double }?,
    attribute StartRowStrokeType { xsd:string }?,
    attribute StartRowStrokeTint { xsd:double }?,
    attribute StartRowStrokeGapOverprint { xsd:boolean }?,
    attribute StartRowStrokeGapColor { xsd:string }?,
    attribute StartRowStrokeGapTint { xsd:double }?,
    attribute StartRowStrokeOverprint { xsd:boolean }?,
    attribute EndRowStrokeCount { xsd:int }?,
    attribute EndRowStrokeColor { xsd:string }?,
    attribute EndRowStrokeWeight { xsd:double }?,
    attribute EndRowStrokeType { xsd:string }?,
    attribute EndRowStrokeTint { xsd:double }?,
    attribute EndRowStrokeOverprint { xsd:boolean }?,
    attribute EndRowStrokeGapColor { xsd:string }?,
    attribute EndRowStrokeGapTint { xsd:double }?,
    attribute EndRowStrokeGapOverprint { xsd:boolean }?,
    attribute SkipFirstAlternatingStrokeColumns { xsd:int }?,
    attribute SkipLastAlternatingStrokeColumns { xsd:int }?,
    attribute StartColumnStrokeCount { xsd:int }?,
    attribute StartColumnStrokeColor { xsd:string }?,
    attribute StartColumnStrokeWeight { xsd:double }?,
    attribute StartColumnStrokeType { xsd:string }?,
    attribute StartColumnStrokeTint { xsd:double }?,
    attribute StartColumnStrokeOverprint { xsd:boolean }?,
    attribute StartColumnStrokeGapColor { xsd:string }?,
    attribute StartColumnStrokeGapTint { xsd:double }?,
    attribute StartColumnStrokeGapOverprint { xsd:boolean }?,
    attribute EndColumnStrokeCount { xsd:int }?,
    attribute EndColumnStrokeColor { xsd:string }?,
    attribute EndColumnStrokeWeight { xsd:double }?,
    attribute EndColumnLineStyle { xsd:string }?,
    attribute EndColumnStrokeTint { xsd:double }?,
    attribute EndColumnStrokeOverprint { xsd:boolean }?,
    attribute EndColumnStrokeGapColor { xsd:string }?,
    attribute EndColumnStrokeGapTint { xsd:double }?,
    attribute EndColumnStrokeGapOverprint { xsd:boolean }?,
    attribute ColumnFillsPriority { xsd:boolean }?,
    attribute SkipFirstAlternatingFillRows { xsd:int }?,
    attribute SkipLastAlternatingFillRows { xsd:int }?,
    attribute StartRowFillColor { xsd:string }?,
    attribute StartRowFillCount { xsd:int }?,
    attribute StartRowFillTint { xsd:double }?,
    attribute StartRowFillOverprint { xsd:boolean }?,
    attribute EndRowFillColor { xsd:string }?,
    attribute EndRowFillCount { xsd:int }?,
    attribute EndRowFillTint { xsd:double }?,
    attribute EndRowFillOverprint { xsd:boolean }?,
    attribute SkipFirstAlternatingFillColumns { xsd:int }?,
    attribute SkipLastAlternatingFillColumns { xsd:int }?,
    attribute StartColumnFillColor { xsd:string }?,
    attribute StartColumnFillCount { xsd:int }?,
    attribute StartColumnFillTint { xsd:double }?,
    attribute StartColumnFillOverprint { xsd:boolean }?,
    attribute EndColumnFillColor { xsd:string }?,
    attribute EndColumnFillCount { xsd:int }?,
    attribute EndColumnFillTint { xsd:double }?,
    attribute EndColumnFillOverprint { xsd:boolean }?,
    attribute HeaderRegionSameAsBodyRegion { xsd:boolean }?,
    attribute FooterRegionSameAsBodyRegion { xsd:boolean }?,
    attribute LeftColumnRegionSameAsBodyRegion { xsd:boolean }?,
    attribute RightColumnRegionSameAsBodyRegion { xsd:boolean }?,
    attribute HeaderRegionCellStyle { xsd:string }?,
    attribute FooterRegionCellStyle { xsd:string }?,
    attribute LeftColumnRegionCellStyle { xsd:string }?,
    attribute RightColumnRegionCellStyle { xsd:string }?,
    attribute BodyRegionCellStyle { xsd:string }?,
    attribute KeyboardShortcut { list { xsd:short,
            xsd:short } }?,
    element Properties {
        element BasedOn { (object_type,
                xsd:string ) |
            (string_type,
                xsd:string ) }? &
        element Label { element KeyValuePair { KeyValuePair_TypeDef }* }?
    } ?
}
