CellStyle_Object = element CellStyle {
    attribute Self { xsd:string },
    attribute AppliedParagraphStyle { xsd:string }?,
    attribute GradientFillLength { xsd:double }?,
    attribute GradientFillAngle { xsd:double }?,
    attribute GradientFillStart { UnitPointType_TypeDef }?,
    attribute TopInset { xsd:double }?,
    attribute LeftInset { xsd:double }?,
    attribute BottomInset { xsd:double }?,
    attribute RightInset { xsd:double }?,
    attribute FillColor { xsd:string }?,
    attribute FillTint { xsd:double }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute TopLeftDiagonalLine { xsd:boolean }?,
    attribute TopRightDiagonalLine { xsd:boolean }?,
    attribute DiagonalLineInFront { xsd:boolean }?,
    attribute DiagonalLineStrokeWeight { xsd:double }?,
    attribute DiagonalLineStrokeType { xsd:string }?,
    attribute DiagonalLineStrokeColor { xsd:string }?,
    attribute DiagonalLineStrokeTint { xsd:double }?,
    attribute DiagonalLineStrokeOverprint { xsd:boolean }?,
    attribute DiagonalLineStrokeGapColor { xsd:string }?,
    attribute DiagonalLineStrokeGapTint { xsd:double }?,
    attribute DiagonalLineStrokeGapOverprint { xsd:boolean }?,
    attribute ClipContentToCell { xsd:boolean }?,
    attribute FirstBaselineOffset { FirstBaseline_EnumValue }?,
    attribute VerticalJustification { VerticalJustification_EnumValue }?,
    attribute ParagraphSpacingLimit { xsd:double }?,
    attribute MinimumFirstBaselineOffset { xsd:double {minInclusive="0" maxInclusive="8640" } }?,
    attribute RotationAngle { xsd:double }?,
    attribute LeftEdgeStrokeWeight { xsd:double }?,
    attribute LeftEdgeStrokeType { xsd:string }?,
    attribute LeftEdgeStrokeColor { xsd:string }?,
    attribute LeftEdgeStrokeTint { xsd:double }?,
    attribute LeftEdgeStrokeOverprint { xsd:boolean }?,
    attribute LeftEdgeStrokeGapColor { xsd:string }?,
    attribute LeftEdgeStrokeGapTint { xsd:double }?,
    attribute LeftEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute TopEdgeStrokeWeight { xsd:double }?,
    attribute TopEdgeStrokeType { xsd:string }?,
    attribute TopEdgeStrokeColor { xsd:string }?,
    attribute TopEdgeStrokeTint { xsd:double }?,
    attribute TopEdgeStrokeOverprint { xsd:boolean }?,
    attribute TopEdgeStrokeGapColor { xsd:string }?,
    attribute TopEdgeStrokeGapTint { xsd:double }?,
    attribute TopEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute BottomEdgeStrokeWeight { xsd:double }?,
    attribute BottomEdgeStrokeType { xsd:string }?,
    attribute BottomEdgeStrokeColor { xsd:string }?,
    attribute BottomEdgeStrokeTint { xsd:double }?,
    attribute BottomEdgeStrokeOverprint { xsd:boolean }?,
    attribute BottomEdgeStrokeGapColor { xsd:string }?,
    attribute BottomEdgeStrokeGapTint { xsd:double }?,
    attribute BottomEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute RightEdgeStrokeWeight { xsd:double }?,
    attribute RightEdgeStrokeType { xsd:string }?,
    attribute RightEdgeStrokeColor { xsd:string }?,
    attribute RightEdgeStrokeTint { xsd:double }?,
    attribute RightEdgeStrokeOverprint { xsd:boolean }?,
    attribute RightEdgeStrokeGapColor { xsd:string }?,
    attribute RightEdgeStrokeGapTint { xsd:double }?,
    attribute RightEdgeStrokeGapOverprint { xsd:boolean }?,
    attribute TopBorderStrokeWeight { xsd:double }?,
    attribute TopBorderStrokeType { xsd:string }?,
    attribute TopBorderStrokeColor { xsd:string }?,
    attribute TopBorderStrokeTint { xsd:double }?,
    attribute TopBorderStrokeOverprint { xsd:boolean }?,
    attribute TopBorderStrokeGapColor { xsd:string }?,
    attribute TopBorderStrokeGapTint { xsd:double }?,
    attribute TopBorderStrokeGapOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeWeight { xsd:double }?,
    attribute LeftBorderStrokeType { xsd:string }?,
    attribute LeftBorderStrokeColor { xsd:string }?,
    attribute LeftBorderStrokeTint { xsd:double }?,
    attribute LeftBorderStrokeOverprint { xsd:boolean }?,
    attribute LeftBorderStrokeGapColor { xsd:string }?,
    attribute LeftBorderStrokeGapTint { xsd:double }?,
    attribute LeftBorderStrokeGapOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeWeight { xsd:double }?,
    attribute BottomBorderStrokeType { xsd:string }?,
    attribute BottomBorderStrokeColor { xsd:string }?,
    attribute BottomBorderStrokeTint { xsd:double }?,
    attribute BottomBorderStrokeOverprint { xsd:boolean }?,
    attribute BottomBorderStrokeGapColor { xsd:string }?,
    attribute BottomBorderStrokeGapTint { xsd:double }?,
    attribute BottomBorderStrokeGapOverprint { xsd:boolean }?,
    attribute RightBorderStrokeWeight { xsd:double }?,
    attribute RightBorderStrokeType { xsd:string }?,
    attribute RightBorderStrokeColor { xsd:string }?,
    attribute RightBorderStrokeTint { xsd:double }?,
    attribute RightBorderStrokeOverprint { xsd:boolean }?,
    attribute RightBorderStrokeGapColor { xsd:string }?,
    attribute RightBorderStrokeGapTint { xsd:double }?,
    attribute RightBorderStrokeGapOverprint { xsd:boolean }?,
    attribute StartRowStrokeWeight { xsd:double }?,
    attribute StartRowStrokeType { xsd:string }?,
    attribute StartRowStrokeColor { xsd:string }?,
    attribute StartRowStrokeTint { xsd:double }?,
    attribute StartRowStrokeOverprint { xsd:boolean }?,
    attribute StartRowStrokeGapColor { xsd:string }?,
    attribute StartRowStrokeGapTint { xsd:double }?,
    attribute StartRowStrokeGapOverprint { xsd:boolean }?,
    attribute EndRowStrokeWeight { xsd:double }?,
    attribute EndRowStrokeType { xsd:string }?,
    attribute EndRowStrokeColor { xsd:string }?,
    attribute EndRowStrokeTint { xsd:double }?,
    attribute EndRowStrokeOverprint { xsd:boolean }?,
    attribute EndRowStrokeGapColor { xsd:string }?,
    attribute EndRowStrokeGapTint { xsd:double }?,
    attribute EndRowStrokeGapOverprint { xsd:boolean }?,
    attribute StartColumnStrokeWeight { xsd:double }?,
    attribute StartColumnStrokeType { xsd:string }?,
    attribute StartColumnStrokeColor { xsd:string }?,
    attribute StartColumnStrokeTint { xsd:double }?,
    attribute StartColumnStrokeOverprint { xsd:boolean }?,
    attribute StartColumnStrokeGapColor { xsd:string }?,
    attribute StartColumnStrokeGapTint { xsd:double }?,
    attribute StartColumnStrokeGapOverprint { xsd:boolean }?,
    attribute EndColumnStrokeWeight { xsd:double }?,
    attribute EndColumnStrokeType { xsd:string }?,
    attribute EndColumnStrokeColor { xsd:string }?,
    attribute EndColumnStrokeTint { xsd:double }?,
    attribute EndColumnStrokeOverprint { xsd:boolean }?,
    attribute EndColumnStrokeGapColor { xsd:string }?,
    attribute EndColumnStrokeGapTint { xsd:double }?,
    attribute EndColumnStrokeGapOverprint { xsd:boolean }?,
    attribute Name { xsd:string },
    element Properties {
        element BasedOn { (object_type,
                xsd:string ) |
            (string_type,
                xsd:string ) }? &
        element Label { element KeyValuePair { KeyValuePair_TypeDef }* }?
    } ?
}
