ObjectStyle_Object = element ObjectStyle {
    attribute Self { xsd:string },
    attribute EnableTextFrameAutoSizingOptions { xsd:boolean }?,
    attribute Name { xsd:string },
    attribute AppliedParagraphStyle { xsd:string }?,
    attribute ApplyNextParagraphStyle { xsd:boolean }?,
    attribute EnableFill { xsd:boolean }?,
    attribute EnableStroke { xsd:boolean }?,
    attribute EnableParagraphStyle { xsd:boolean }?,
    attribute EnableTextFrameGeneralOptions { xsd:boolean }?,
    attribute EnableTextFrameBaselineOptions { xsd:boolean }?,
    attribute EnableStoryOptions { xsd:boolean }?,
    attribute EnableTextWrapAndOthers { xsd:boolean }?,
    attribute EnableAnchoredObjectOptions { xsd:boolean }?,
    attribute CornerRadius { xsd:double }?,
    attribute FillColor { xsd:string }?,
    attribute FillTint { xsd:double }?,
    attribute OverprintFill { xsd:boolean }?,
    attribute StrokeWeight { xsd:double }?,
    attribute MiterLimit { xsd:double {minInclusive="1" maxInclusive="500" } }?,
    attribute EndCap { EndCap_EnumValue }?,
    attribute EndJoin { EndJoin_EnumValue }?,
    attribute StrokeType { xsd:string }?,
    attribute LeftLineEnd { ArrowHead_EnumValue }?,
    attribute RightLineEnd { ArrowHead_EnumValue }?,
    attribute StrokeColor { xsd:string }?,
    attribute StrokeTint { xsd:double }?,
    attribute OverprintStroke { xsd:boolean }?,
    attribute GapColor { xsd:string }?,
    attribute GapTint { xsd:double }?,
    attribute OverprintGap { xsd:boolean }?,
    attribute StrokeAlignment { StrokeAlignment_EnumValue }?,
    attribute Nonprinting { xsd:boolean }?,
    attribute GradientFillAngle { xsd:double }?,
    attribute GradientStrokeAngle { xsd:double }?,
    attribute StrokeCornerAdjustment { StrokeCornerAdjustment_EnumValue }?,
    attribute StrokeDashAndGap { list { xsd:double * } }?,
    attribute AppliedNamedGrid { xsd:string }?,
    attribute KeyboardShortcut { list { xsd:short,
            xsd:short } }?,
    attribute TopLeftCornerOption { CornerOptions_EnumValue }?,
    attribute TopRightCornerOption { CornerOptions_EnumValue }?,
    attribute BottomLeftCornerOption { CornerOptions_EnumValue }?,
    attribute BottomRightCornerOption { CornerOptions_EnumValue }?,
    attribute TopLeftCornerRadius { xsd:double }?,
    attribute TopRightCornerRadius { xsd:double }?,
    attribute BottomLeftCornerRadius { xsd:double }?,
    attribute BottomRightCornerRadius { xsd:double }?,
    attribute EnableFrameFittingOptions { xsd:boolean }?,
    attribute FrameFittingAttribute { FrameFittingOption_EnumValue }?,
    attribute LeftMargin { xsd:double }?,
    attribute RightMargin { xsd:double }?,
    attribute TopMargin { xsd:double }?,
    attribute BottomMargin { xsd:double }?,
    attribute FirstBaselineOffset { FirstBaseline_EnumValue }?,
    attribute MinimumHeight { xsd:double }?,
    attribute MaximumHeight { DimensionEnum }?,
    attribute AutoHeight { DimensionEnum }?,
    attribute Width { xsd:double }?,
    attribute Height { xsd:double }?,
    attribute AnchorPoint { AnchorPoint_EnumValue }?,
    attribute HorizontalLayoutConstraints { xsd:string }?,
    attribute VerticalLayoutConstraints { xsd:string }?,
    attribute LockPosition { xsd:boolean }?,
    attribute LockResizing { xsd:boolean }?,
    attribute DisableLayout { xsd:boolean }?,
    attribute RotateAngle { xsd:double }?,
    attribute ShearAngle { xsd:double }?,
    attribute PageItemAttributes { PageItemAttributes_TypeDef }?,
    attribute AppliedTOCStyle { xsd:string }?,
    attribute FrameType { FrameType_EnumValue }?,
    attribute GradientStrokeStart { UnitPointType_TypeDef }?,
    attribute GradientFillStart { UnitPointType_TypeDef }?,
    attribute EyedropperClickPoint { UnitPointType_TypeDef }?,
    attribute ContentType { ContentType_EnumValue }?,
    attribute AppliedObjectStyle { xsd:string }?,
    attribute Tooltip { xsd:string }?,
    attribute ObjectStyleAttribute { xsd:string }?
}
