# frozen_string: true

module Idml
  module Render
    # Resolves `AppliedParagraphStyle` and `AppliedCharacterStyle`
    # references to their style definitions in Resources/Styles.xml.
    # Built once per render pass from `Parts::Style`; StyleResolver
    # consults it to fill in formatting attributes that the PSR/CSR
    # element doesn't declare inline.
    #
    # Merge semantics: PSR/CSR inline attributes override style
    # attributes. When the PSR/CSR declares a value (non-nil), that
    # wins. When it doesn't, the style definition's value is used
    # as a default. When neither declares a value, the attribute
    # remains nil and the renderer applies its own default.
    class StyleLookup
      def self.from_package(package)
        styles = package&.style
        return new({}, {}) unless styles

        para_styles = index_styles(styles.paragraph_style)
        char_styles = index_styles(styles.character_style)
        new(para_styles, char_styles)
      end

      def initialize(para_styles, char_styles)
        @para_styles = para_styles
        @char_styles = char_styles
      end

      # Returns the ParagraphStyle referenced by `self_ref`, or nil.
      # `self_ref` is the PSR's AppliedParagraphStyle value (e.g.,
      # "ParagraphStyle/$ID/NormalParagraphStyle").
      def paragraph_style(self_ref)
        return nil unless self_ref

        @para_styles[self_ref]
      end

      # Returns the CharacterStyle referenced by `self_ref`, or nil.
      def character_style(self_ref)
        return nil unless self_ref

        @char_styles[self_ref]
      end

      # Returns the value of `attr_name` from the PSR, or from the
      # referenced ParagraphStyle when the PSR doesn't declare it.
      # Uses `public_send` (not `send`) to stay within public API
      # boundaries — the attribute readers generated by lutaml-model
      # are public.
      def resolve_para_attr(psr, attr_name)
        psr_value = psr.public_send(attr_name)
        return psr_value unless psr_value.nil?

        style = paragraph_style(psr.applied_paragraph_style)
        style&.public_send(attr_name)
      end

      # Returns the value of `attr_name` from the CSR, or from the
      # referenced CharacterStyle when the CSR doesn't declare it.
      def resolve_char_attr(csr, attr_name)
        csr_value = csr.public_send(attr_name)
        return csr_value unless csr_value.nil?

        style = character_style(csr.applied_character_style)
        style&.public_send(attr_name)
      end

      def self.index_styles(collection)
        collection.each_with_object({}) do |style, hash|
          hash[style.self_attr] = style if style.self_attr
        end
      end
      private_class_method :index_styles
    end
  end
end
