# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<AnchoredObjectSetting>`. Every
    # attribute from `AnchoredObjectSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class AnchoredObjectSetting < Lutaml::Model::Serializable
      attribute :anchored_position, :string
      attribute :spine_relative, :boolean
      attribute :lock_position, :boolean
      attribute :pin_position, :boolean
      attribute :anchor_point, :string
      attribute :horizontal_alignment, :string
      attribute :horizontal_reference_point, :string
      attribute :vertical_alignment, :string
      attribute :vertical_reference_point, :string
      attribute :anchor_xoffset, :float
      attribute :anchor_yoffset, :float
      attribute :anchor_space_above, :float

      xml do
        root "AnchoredObjectSetting"
        map_attribute "AnchoredPosition", to: :anchored_position
        map_attribute "SpineRelative", to: :spine_relative
        map_attribute "LockPosition", to: :lock_position
        map_attribute "PinPosition", to: :pin_position
        map_attribute "AnchorPoint", to: :anchor_point
        map_attribute "HorizontalAlignment", to: :horizontal_alignment
        map_attribute "HorizontalReferencePoint", to: :horizontal_reference_point
        map_attribute "VerticalAlignment", to: :vertical_alignment
        map_attribute "VerticalReferencePoint", to: :vertical_reference_point
        map_attribute "AnchorXoffset", to: :anchor_xoffset
        map_attribute "AnchorYoffset", to: :anchor_yoffset
        map_attribute "AnchorSpaceAbove", to: :anchor_space_above
      end
    end
  end
end
