# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<BaselineFrameGridOption>`. Every
    # attribute from `BaselineFrameGridOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class BaselineFrameGridOption < Lutaml::Model::Serializable
      attribute :use_custom_baseline_frame_grid, :boolean
      attribute :starting_offset_for_baseline_frame_grid, :float
      attribute :baseline_frame_grid_relative_option, :string
      attribute :baseline_frame_grid_increment, :float

      xml do
        root "BaselineFrameGridOption"
        map_attribute "UseCustomBaselineFrameGrid", to: :use_custom_baseline_frame_grid
        map_attribute "StartingOffsetForBaselineFrameGrid", to: :starting_offset_for_baseline_frame_grid
        map_attribute "BaselineFrameGridRelativeOption", to: :baseline_frame_grid_relative_option
        map_attribute "BaselineFrameGridIncrement", to: :baseline_frame_grid_increment
      end
    end
  end
end
