# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<BevelAndEmbossSetting>`. Every
    # attribute from `BevelAndEmbossSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (16 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class BevelAndEmbossSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :style, :string
      attribute :technique, :string
      attribute :depth, :float
      attribute :direction, :string
      attribute :size, :float
      attribute :soften, :float
      attribute :angle, :float
      attribute :altitude, :float
      attribute :use_global_light, :boolean
      attribute :highlight_color, :string
      attribute :highlight_blend_mode, :string
      attribute :highlight_opacity, :float
      attribute :shadow_color, :string
      attribute :shadow_blend_mode, :string
      attribute :shadow_opacity, :float

      xml do
        root "BevelAndEmbossSetting"
        map_attribute "Applied", to: :applied
        map_attribute "Style", to: :style
        map_attribute "Technique", to: :technique
        map_attribute "Depth", to: :depth
        map_attribute "Direction", to: :direction
        map_attribute "Size", to: :size
        map_attribute "Soften", to: :soften
        map_attribute "Angle", to: :angle
        map_attribute "Altitude", to: :altitude
        map_attribute "UseGlobalLight", to: :use_global_light
        map_attribute "HighlightColor", to: :highlight_color
        map_attribute "HighlightBlendMode", to: :highlight_blend_mode
        map_attribute "HighlightOpacity", to: :highlight_opacity
        map_attribute "ShadowColor", to: :shadow_color
        map_attribute "ShadowBlendMode", to: :shadow_blend_mode
        map_attribute "ShadowOpacity", to: :shadow_opacity
      end
    end
  end
end
