# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<BlendingSetting>`. Every
    # attribute from `BlendingSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class BlendingSetting < Lutaml::Model::Serializable
      attribute :blend_mode, :string
      attribute :opacity, :float
      attribute :knockout_group, :boolean
      attribute :isolate_blending, :boolean

      xml do
        root "BlendingSetting"
        map_attribute "BlendMode", to: :blend_mode
        map_attribute "Opacity", to: :opacity
        map_attribute "KnockoutGroup", to: :knockout_group
        map_attribute "IsolateBlending", to: :isolate_blending
      end
    end
  end
end
