# frozen_string_literal: true

module Idml
  module Elements
    # `<Cell>` — a single cell in an IDML Table. Per `Cell_Object`
    # in `reference-docs/schemas/package/Stories/Story.rnc`.
    #
    # Schema note: real IDML has `<Cell>` and `<Row>` as **siblings**
    # inside `<Table>`, not nested `<TableRow><TableCell>`. This
    # class is the schema-faithful model. The legacy
    # `Idml::Elements::TableCell` (which models the non-standard
    # `<TableCell>` element) is preserved for back-compat with the
    # existing synthetic test fixture — see TODO 84.
    #
    # The cell's `Name` attribute encodes its column/row position
    # as `"col:row"` (e.g., `"0:0"`, `"1:2"`). Carries text content
    # via inline `<ParagraphStyleRange>` → `<CharacterStyleRange>`
    # → `<Content>` children, the same structure as a Story.
    class Cell < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :row_span, :integer
      attribute :column_span, :integer
      attribute :column_type, :string
      attribute :cell_type, :string
      attribute :top_inset, :float
      attribute :left_inset, :float
      attribute :bottom_inset, :float
      attribute :right_inset, :float
      attribute :fill_color, :string
      attribute :fill_tint, :float
      attribute :overprint_fill, :boolean
      attribute :clip_content_to_cell, :boolean
      attribute :vertical_justification, :string
      attribute :paragraph_spacing_limit, :float
      attribute :rotation_angle, :float
      attribute :applied_cell_style, :string
      attribute :paragraph_style_range, Idml::Elements::ParagraphStyleRange,
                collection: true

      # The remaining Cell_Object attributes (per-side edge strokes,
      # diagonal lines, cell style overrides, …) in schema order —
      # generated by `scripts/rnc_to_lutaml.rb` from
      # reference-docs/schemas/package/Stories/Story.rnc.
      attribute :top_inset, :float
      attribute :left_inset, :float
      attribute :bottom_inset, :float
      attribute :right_inset, :float
      attribute :top_left_diagonal_line, :boolean
      attribute :top_right_diagonal_line, :boolean
      attribute :diagonal_line_in_front, :boolean
      attribute :diagonal_line_stroke_weight, :float
      attribute :diagonal_line_stroke_type, :string
      attribute :diagonal_line_stroke_color, :string
      attribute :diagonal_line_stroke_tint, :float
      attribute :diagonal_line_stroke_overprint, :boolean
      attribute :diagonal_line_stroke_gap_color, :string
      attribute :diagonal_line_stroke_gap_tint, :float
      attribute :diagonal_line_stroke_gap_overprint, :boolean
      attribute :clip_content_to_cell, :boolean
      attribute :first_baseline_offset, :string
      attribute :minimum_first_baseline_offset, :float
      attribute :left_edge_stroke_weight, :float
      attribute :left_edge_stroke_type, :string
      attribute :left_edge_stroke_color, :string
      attribute :left_edge_stroke_tint, :float
      attribute :left_edge_stroke_overprint, :boolean
      attribute :left_edge_stroke_gap_color, :string
      attribute :left_edge_stroke_gap_tint, :float
      attribute :left_edge_stroke_gap_overprint, :boolean
      attribute :top_edge_stroke_weight, :float
      attribute :top_edge_stroke_type, :string
      attribute :top_edge_stroke_color, :string
      attribute :top_edge_stroke_tint, :float
      attribute :top_edge_stroke_overprint, :boolean
      attribute :top_edge_stroke_gap_color, :string
      attribute :top_edge_stroke_gap_tint, :float
      attribute :top_edge_stroke_gap_overprint, :boolean
      attribute :right_edge_stroke_weight, :float
      attribute :right_edge_stroke_type, :string
      attribute :right_edge_stroke_color, :string
      attribute :right_edge_stroke_tint, :float
      attribute :right_edge_stroke_overprint, :boolean
      attribute :right_edge_stroke_gap_color, :string
      attribute :right_edge_stroke_gap_tint, :float
      attribute :right_edge_stroke_gap_overprint, :boolean
      attribute :bottom_edge_stroke_weight, :float
      attribute :bottom_edge_stroke_type, :string
      attribute :bottom_edge_stroke_color, :string
      attribute :bottom_edge_stroke_tint, :float
      attribute :bottom_edge_stroke_overprint, :boolean
      attribute :bottom_edge_stroke_gap_color, :string
      attribute :bottom_edge_stroke_gap_tint, :float
      attribute :bottom_edge_stroke_gap_overprint, :boolean
      attribute :inner_row_stroke_weight, :float
      attribute :inner_row_stroke_type, :string
      attribute :inner_row_stroke_color, :string
      attribute :inner_row_stroke_tint, :float
      attribute :inner_row_stroke_overprint, :boolean
      attribute :inner_row_stroke_gap_color, :string
      attribute :inner_row_stroke_gap_tint, :float
      attribute :inner_row_stroke_gap_overprint, :boolean
      attribute :inner_column_stroke_weight, :float
      attribute :inner_column_stroke_type, :string
      attribute :inner_column_stroke_color, :string
      attribute :inner_column_stroke_tint, :float
      attribute :inner_column_stroke_overprint, :boolean
      attribute :inner_column_stroke_gap_color, :string
      attribute :inner_column_stroke_gap_tint, :float
      attribute :inner_column_stroke_gap_overprint, :boolean
      attribute :top_edge_stroke_priority, :integer
      attribute :left_edge_stroke_priority, :integer
      attribute :bottom_edge_stroke_priority, :integer
      attribute :right_edge_stroke_priority, :integer
      attribute :graphic_left_inset, :float
      attribute :graphic_top_inset, :float
      attribute :graphic_right_inset, :float
      attribute :graphic_bottom_inset, :float
      attribute :clip_content_to_graphic_cell, :boolean
      attribute :writing_direction, :boolean
      attribute :applied_cell_style_priority, :integer

      xml do
        root "Cell"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "RowSpan", to: :row_span
        map_attribute "ColumnSpan", to: :column_span
        map_attribute "ColumnType", to: :column_type
        map_attribute "CellType", to: :cell_type
        map_attribute "TextTopInset", to: :top_inset
        map_attribute "TextLeftInset", to: :left_inset
        map_attribute "TextBottomInset", to: :bottom_inset
        map_attribute "TextRightInset", to: :right_inset
        map_attribute "FillColor", to: :fill_color
        map_attribute "FillTint", to: :fill_tint
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "ClipContentToTextCell", to: :clip_content_to_cell
        map_attribute "VerticalJustification", to: :vertical_justification
        map_attribute "ParagraphSpacingLimit", to: :paragraph_spacing_limit
        map_attribute "RotationAngle", to: :rotation_angle
        map_attribute "AppliedCellStyle", to: :applied_cell_style
        map_attribute "TopInset", to: :top_inset
        map_attribute "LeftInset", to: :left_inset
        map_attribute "BottomInset", to: :bottom_inset
        map_attribute "RightInset", to: :right_inset
        map_attribute "TopLeftDiagonalLine", to: :top_left_diagonal_line
        map_attribute "TopRightDiagonalLine", to: :top_right_diagonal_line
        map_attribute "DiagonalLineInFront", to: :diagonal_line_in_front
        map_attribute "DiagonalLineStrokeWeight",
                      to: :diagonal_line_stroke_weight
        map_attribute "DiagonalLineStrokeType", to: :diagonal_line_stroke_type
        map_attribute "DiagonalLineStrokeColor", to: :diagonal_line_stroke_color
        map_attribute "DiagonalLineStrokeTint", to: :diagonal_line_stroke_tint
        map_attribute "DiagonalLineStrokeOverprint",
                      to: :diagonal_line_stroke_overprint
        map_attribute "DiagonalLineStrokeGapColor",
                      to: :diagonal_line_stroke_gap_color
        map_attribute "DiagonalLineStrokeGapTint",
                      to: :diagonal_line_stroke_gap_tint
        map_attribute "DiagonalLineStrokeGapOverprint",
                      to: :diagonal_line_stroke_gap_overprint
        map_attribute "ClipContentToCell", to: :clip_content_to_cell
        map_attribute "FirstBaselineOffset", to: :first_baseline_offset
        map_attribute "MinimumFirstBaselineOffset",
                      to: :minimum_first_baseline_offset
        map_attribute "LeftEdgeStrokeWeight", to: :left_edge_stroke_weight
        map_attribute "LeftEdgeStrokeType", to: :left_edge_stroke_type
        map_attribute "LeftEdgeStrokeColor", to: :left_edge_stroke_color
        map_attribute "LeftEdgeStrokeTint", to: :left_edge_stroke_tint
        map_attribute "LeftEdgeStrokeOverprint", to: :left_edge_stroke_overprint
        map_attribute "LeftEdgeStrokeGapColor", to: :left_edge_stroke_gap_color
        map_attribute "LeftEdgeStrokeGapTint", to: :left_edge_stroke_gap_tint
        map_attribute "LeftEdgeStrokeGapOverprint",
                      to: :left_edge_stroke_gap_overprint
        map_attribute "TopEdgeStrokeWeight", to: :top_edge_stroke_weight
        map_attribute "TopEdgeStrokeType", to: :top_edge_stroke_type
        map_attribute "TopEdgeStrokeColor", to: :top_edge_stroke_color
        map_attribute "TopEdgeStrokeTint", to: :top_edge_stroke_tint
        map_attribute "TopEdgeStrokeOverprint", to: :top_edge_stroke_overprint
        map_attribute "TopEdgeStrokeGapColor", to: :top_edge_stroke_gap_color
        map_attribute "TopEdgeStrokeGapTint", to: :top_edge_stroke_gap_tint
        map_attribute "TopEdgeStrokeGapOverprint",
                      to: :top_edge_stroke_gap_overprint
        map_attribute "RightEdgeStrokeWeight", to: :right_edge_stroke_weight
        map_attribute "RightEdgeStrokeType", to: :right_edge_stroke_type
        map_attribute "RightEdgeStrokeColor", to: :right_edge_stroke_color
        map_attribute "RightEdgeStrokeTint", to: :right_edge_stroke_tint
        map_attribute "RightEdgeStrokeOverprint",
                      to: :right_edge_stroke_overprint
        map_attribute "RightEdgeStrokeGapColor",
                      to: :right_edge_stroke_gap_color
        map_attribute "RightEdgeStrokeGapTint", to: :right_edge_stroke_gap_tint
        map_attribute "RightEdgeStrokeGapOverprint",
                      to: :right_edge_stroke_gap_overprint
        map_attribute "BottomEdgeStrokeWeight", to: :bottom_edge_stroke_weight
        map_attribute "BottomEdgeStrokeType", to: :bottom_edge_stroke_type
        map_attribute "BottomEdgeStrokeColor", to: :bottom_edge_stroke_color
        map_attribute "BottomEdgeStrokeTint", to: :bottom_edge_stroke_tint
        map_attribute "BottomEdgeStrokeOverprint",
                      to: :bottom_edge_stroke_overprint
        map_attribute "BottomEdgeStrokeGapColor",
                      to: :bottom_edge_stroke_gap_color
        map_attribute "BottomEdgeStrokeGapTint",
                      to: :bottom_edge_stroke_gap_tint
        map_attribute "BottomEdgeStrokeGapOverprint",
                      to: :bottom_edge_stroke_gap_overprint
        map_attribute "InnerRowStrokeWeight", to: :inner_row_stroke_weight
        map_attribute "InnerRowStrokeType", to: :inner_row_stroke_type
        map_attribute "InnerRowStrokeColor", to: :inner_row_stroke_color
        map_attribute "InnerRowStrokeTint", to: :inner_row_stroke_tint
        map_attribute "InnerRowStrokeOverprint", to: :inner_row_stroke_overprint
        map_attribute "InnerRowStrokeGapColor", to: :inner_row_stroke_gap_color
        map_attribute "InnerRowStrokeGapTint", to: :inner_row_stroke_gap_tint
        map_attribute "InnerRowStrokeGapOverprint",
                      to: :inner_row_stroke_gap_overprint
        map_attribute "InnerColumnStrokeWeight", to: :inner_column_stroke_weight
        map_attribute "InnerColumnStrokeType", to: :inner_column_stroke_type
        map_attribute "InnerColumnStrokeColor", to: :inner_column_stroke_color
        map_attribute "InnerColumnStrokeTint", to: :inner_column_stroke_tint
        map_attribute "InnerColumnStrokeOverprint",
                      to: :inner_column_stroke_overprint
        map_attribute "InnerColumnStrokeGapColor",
                      to: :inner_column_stroke_gap_color
        map_attribute "InnerColumnStrokeGapTint",
                      to: :inner_column_stroke_gap_tint
        map_attribute "InnerColumnStrokeGapOverprint",
                      to: :inner_column_stroke_gap_overprint
        map_attribute "TopEdgeStrokePriority", to: :top_edge_stroke_priority
        map_attribute "LeftEdgeStrokePriority", to: :left_edge_stroke_priority
        map_attribute "BottomEdgeStrokePriority",
                      to: :bottom_edge_stroke_priority
        map_attribute "RightEdgeStrokePriority", to: :right_edge_stroke_priority
        map_attribute "GraphicLeftInset", to: :graphic_left_inset
        map_attribute "GraphicTopInset", to: :graphic_top_inset
        map_attribute "GraphicRightInset", to: :graphic_right_inset
        map_attribute "GraphicBottomInset", to: :graphic_bottom_inset
        map_attribute "ClipContentToGraphicCell",
                      to: :clip_content_to_graphic_cell
        map_attribute "WritingDirection", to: :writing_direction
        map_attribute "AppliedCellStylePriority",
                      to: :applied_cell_style_priority
        map_element "ParagraphStyleRange", to: :paragraph_style_range
      end

      def text_content
        paragraph_style_range.filter_map(&:text_content).join
      end

      # Cell name format is "col:row" (e.g., "0:0", "1:2").
      # Returns [col, row] integers or nil if Name is malformed.
      def col_row
        return nil unless name

        parts = name.split(":")
        return nil unless parts.length == 2

        [parts[0].to_i, parts[1].to_i]
      end
    end
  end
end
