# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<CellStyle>`. Every
    # attribute from `CellStyle_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (75 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class CellStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :extended_keyboard_shortcut, :string
      attribute :graphic_left_inset, :float
      attribute :graphic_top_inset, :float
      attribute :graphic_right_inset, :float
      attribute :graphic_bottom_inset, :float
      attribute :clip_content_to_graphic_cell, :boolean
      attribute :text_top_inset, :float
      attribute :text_left_inset, :float
      attribute :text_bottom_inset, :float
      attribute :text_right_inset, :float
      attribute :clip_content_to_text_cell, :boolean
      attribute :applied_paragraph_style, :string
      attribute :gradient_fill_length, :float
      attribute :gradient_fill_angle, :float
      attribute :gradient_fill_start, :string
      attribute :top_inset, :float
      attribute :left_inset, :float
      attribute :bottom_inset, :float
      attribute :right_inset, :float
      attribute :fill_color, :string
      attribute :fill_tint, :float
      attribute :overprint_fill, :boolean
      attribute :top_left_diagonal_line, :boolean
      attribute :top_right_diagonal_line, :boolean
      attribute :diagonal_line_in_front, :boolean
      attribute :diagonal_line_stroke_weight, :float
      attribute :diagonal_line_stroke_type, :string
      attribute :diagonal_line_stroke_color, :string
      attribute :diagonal_line_stroke_tint, :float
      attribute :diagonal_line_stroke_overprint, :boolean
      attribute :diagonal_line_stroke_gap_color, :string
      attribute :diagonal_line_stroke_gap_tint, :float
      attribute :diagonal_line_stroke_gap_overprint, :boolean
      attribute :clip_content_to_cell, :boolean
      attribute :first_baseline_offset, :string
      attribute :vertical_justification, :string
      attribute :paragraph_spacing_limit, :float
      attribute :minimum_first_baseline_offset, :float
      attribute :rotation_angle, :float
      attribute :left_edge_stroke_weight, :float
      attribute :left_edge_stroke_type, :string
      attribute :left_edge_stroke_color, :string
      attribute :left_edge_stroke_tint, :float
      attribute :left_edge_stroke_overprint, :boolean
      attribute :left_edge_stroke_gap_color, :string
      attribute :left_edge_stroke_gap_tint, :float
      attribute :left_edge_stroke_gap_overprint, :boolean
      attribute :top_edge_stroke_weight, :float
      attribute :top_edge_stroke_type, :string
      attribute :top_edge_stroke_color, :string
      attribute :top_edge_stroke_tint, :float
      attribute :top_edge_stroke_overprint, :boolean
      attribute :top_edge_stroke_gap_color, :string
      attribute :top_edge_stroke_gap_tint, :float
      attribute :top_edge_stroke_gap_overprint, :boolean
      attribute :right_edge_stroke_weight, :float
      attribute :right_edge_stroke_type, :string
      attribute :right_edge_stroke_color, :string
      attribute :right_edge_stroke_tint, :float
      attribute :right_edge_stroke_overprint, :boolean
      attribute :right_edge_stroke_gap_color, :string
      attribute :right_edge_stroke_gap_tint, :float
      attribute :right_edge_stroke_gap_overprint, :boolean
      attribute :bottom_edge_stroke_weight, :float
      attribute :bottom_edge_stroke_type, :string
      attribute :bottom_edge_stroke_color, :string
      attribute :bottom_edge_stroke_tint, :float
      attribute :bottom_edge_stroke_overprint, :boolean
      attribute :bottom_edge_stroke_gap_color, :string
      attribute :bottom_edge_stroke_gap_tint, :float
      attribute :bottom_edge_stroke_gap_overprint, :boolean
      attribute :keyboard_shortcut, :string
      attribute :rotation_runs_against_story, :boolean
      attribute :name, :string

      xml do
        root "CellStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "ExtendedKeyboardShortcut", to: :extended_keyboard_shortcut
        map_attribute "GraphicLeftInset", to: :graphic_left_inset
        map_attribute "GraphicTopInset", to: :graphic_top_inset
        map_attribute "GraphicRightInset", to: :graphic_right_inset
        map_attribute "GraphicBottomInset", to: :graphic_bottom_inset
        map_attribute "ClipContentToGraphicCell", to: :clip_content_to_graphic_cell
        map_attribute "TextTopInset", to: :text_top_inset
        map_attribute "TextLeftInset", to: :text_left_inset
        map_attribute "TextBottomInset", to: :text_bottom_inset
        map_attribute "TextRightInset", to: :text_right_inset
        map_attribute "ClipContentToTextCell", to: :clip_content_to_text_cell
        map_attribute "AppliedParagraphStyle", to: :applied_paragraph_style
        map_attribute "GradientFillLength", to: :gradient_fill_length
        map_attribute "GradientFillAngle", to: :gradient_fill_angle
        map_attribute "GradientFillStart", to: :gradient_fill_start
        map_attribute "TopInset", to: :top_inset
        map_attribute "LeftInset", to: :left_inset
        map_attribute "BottomInset", to: :bottom_inset
        map_attribute "RightInset", to: :right_inset
        map_attribute "FillColor", to: :fill_color
        map_attribute "FillTint", to: :fill_tint
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "TopLeftDiagonalLine", to: :top_left_diagonal_line
        map_attribute "TopRightDiagonalLine", to: :top_right_diagonal_line
        map_attribute "DiagonalLineInFront", to: :diagonal_line_in_front
        map_attribute "DiagonalLineStrokeWeight", to: :diagonal_line_stroke_weight
        map_attribute "DiagonalLineStrokeType", to: :diagonal_line_stroke_type
        map_attribute "DiagonalLineStrokeColor", to: :diagonal_line_stroke_color
        map_attribute "DiagonalLineStrokeTint", to: :diagonal_line_stroke_tint
        map_attribute "DiagonalLineStrokeOverprint", to: :diagonal_line_stroke_overprint
        map_attribute "DiagonalLineStrokeGapColor", to: :diagonal_line_stroke_gap_color
        map_attribute "DiagonalLineStrokeGapTint", to: :diagonal_line_stroke_gap_tint
        map_attribute "DiagonalLineStrokeGapOverprint", to: :diagonal_line_stroke_gap_overprint
        map_attribute "ClipContentToCell", to: :clip_content_to_cell
        map_attribute "FirstBaselineOffset", to: :first_baseline_offset
        map_attribute "VerticalJustification", to: :vertical_justification
        map_attribute "ParagraphSpacingLimit", to: :paragraph_spacing_limit
        map_attribute "MinimumFirstBaselineOffset", to: :minimum_first_baseline_offset
        map_attribute "RotationAngle", to: :rotation_angle
        map_attribute "LeftEdgeStrokeWeight", to: :left_edge_stroke_weight
        map_attribute "LeftEdgeStrokeType", to: :left_edge_stroke_type
        map_attribute "LeftEdgeStrokeColor", to: :left_edge_stroke_color
        map_attribute "LeftEdgeStrokeTint", to: :left_edge_stroke_tint
        map_attribute "LeftEdgeStrokeOverprint", to: :left_edge_stroke_overprint
        map_attribute "LeftEdgeStrokeGapColor", to: :left_edge_stroke_gap_color
        map_attribute "LeftEdgeStrokeGapTint", to: :left_edge_stroke_gap_tint
        map_attribute "LeftEdgeStrokeGapOverprint", to: :left_edge_stroke_gap_overprint
        map_attribute "TopEdgeStrokeWeight", to: :top_edge_stroke_weight
        map_attribute "TopEdgeStrokeType", to: :top_edge_stroke_type
        map_attribute "TopEdgeStrokeColor", to: :top_edge_stroke_color
        map_attribute "TopEdgeStrokeTint", to: :top_edge_stroke_tint
        map_attribute "TopEdgeStrokeOverprint", to: :top_edge_stroke_overprint
        map_attribute "TopEdgeStrokeGapColor", to: :top_edge_stroke_gap_color
        map_attribute "TopEdgeStrokeGapTint", to: :top_edge_stroke_gap_tint
        map_attribute "TopEdgeStrokeGapOverprint", to: :top_edge_stroke_gap_overprint
        map_attribute "RightEdgeStrokeWeight", to: :right_edge_stroke_weight
        map_attribute "RightEdgeStrokeType", to: :right_edge_stroke_type
        map_attribute "RightEdgeStrokeColor", to: :right_edge_stroke_color
        map_attribute "RightEdgeStrokeTint", to: :right_edge_stroke_tint
        map_attribute "RightEdgeStrokeOverprint", to: :right_edge_stroke_overprint
        map_attribute "RightEdgeStrokeGapColor", to: :right_edge_stroke_gap_color
        map_attribute "RightEdgeStrokeGapTint", to: :right_edge_stroke_gap_tint
        map_attribute "RightEdgeStrokeGapOverprint", to: :right_edge_stroke_gap_overprint
        map_attribute "BottomEdgeStrokeWeight", to: :bottom_edge_stroke_weight
        map_attribute "BottomEdgeStrokeType", to: :bottom_edge_stroke_type
        map_attribute "BottomEdgeStrokeColor", to: :bottom_edge_stroke_color
        map_attribute "BottomEdgeStrokeTint", to: :bottom_edge_stroke_tint
        map_attribute "BottomEdgeStrokeOverprint", to: :bottom_edge_stroke_overprint
        map_attribute "BottomEdgeStrokeGapColor", to: :bottom_edge_stroke_gap_color
        map_attribute "BottomEdgeStrokeGapTint", to: :bottom_edge_stroke_gap_tint
        map_attribute "BottomEdgeStrokeGapOverprint", to: :bottom_edge_stroke_gap_overprint
        map_attribute "KeyboardShortcut", to: :keyboard_shortcut
        map_attribute "RotationRunsAgainstStory", to: :rotation_runs_against_story
        map_attribute "Name", to: :name
      end
    end
  end
end
