# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<CharacterStyle>`. Every
    # attribute from `CharacterStyle_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (143 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class CharacterStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :imported, :boolean
      attribute :font_style, :string
      attribute :point_size, :float
      attribute :kerning_method, :string
      attribute :tracking, :float
      attribute :capitalization, :string
      attribute :position, :string
      attribute :underline, :boolean
      attribute :strike_thru, :boolean
      attribute :ligatures, :boolean
      attribute :no_break, :boolean
      attribute :horizontal_scale, :float
      attribute :vertical_scale, :float
      attribute :baseline_shift, :float
      attribute :skew, :float
      attribute :fill_tint, :float
      attribute :stroke_tint, :float
      attribute :stroke_weight, :float
      attribute :overprint_stroke, :boolean
      attribute :overprint_fill, :boolean
      attribute :otf_figure_style, :string
      attribute :otf_ordinal, :boolean
      attribute :otf_fraction, :boolean
      attribute :otf_discretionary_ligature, :boolean
      attribute :otf_titling, :boolean
      attribute :otf_contextual_alternate, :boolean
      attribute :otf_swash, :boolean
      attribute :underline_tint, :float
      attribute :underline_gap_tint, :float
      attribute :underline_overprint, :boolean
      attribute :underline_gap_overprint, :boolean
      attribute :underline_offset, :float
      attribute :underline_weight, :float
      attribute :strike_through_tint, :float
      attribute :strike_through_gap_tint, :float
      attribute :strike_through_overprint, :boolean
      attribute :strike_through_gap_overprint, :boolean
      attribute :strike_through_offset, :float
      attribute :strike_through_weight, :float
      attribute :fill_color, :string
      attribute :stroke_color, :string
      attribute :applied_language, :string
      attribute :kerning_value, :float
      attribute :split_document, :boolean
      attribute :emit_css, :boolean
      attribute :style_unique_id, :string
      attribute :include_class, :boolean
      attribute :extended_keyboard_shortcut, :string
      attribute :epub_aria_role, :string
      attribute :keyboard_shortcut, :string
      attribute :otf_slashed_zero, :boolean
      attribute :otf_historical, :boolean
      attribute :otf_stylistic_sets, :integer
      attribute :gradient_fill_length, :float
      attribute :gradient_fill_angle, :float
      attribute :gradient_stroke_length, :float
      attribute :gradient_stroke_angle, :float
      attribute :gradient_fill_start, :string
      attribute :gradient_stroke_start, :string
      attribute :otf_mark, :boolean
      attribute :otf_locale, :boolean
      attribute :positional_form, :string
      attribute :name, :string
      attribute :miter_limit, :float
      attribute :stroke_alignment, :string
      attribute :end_join, :string
      attribute :otf_overlap_swash, :boolean
      attribute :otf_stylistic_alternate, :boolean
      attribute :otf_justification_alternate, :boolean
      attribute :otf_stretched_alternate, :boolean
      attribute :character_direction, :string
      attribute :keyboard_direction, :string
      attribute :digits_type, :string
      attribute :kashidas, :string
      attribute :diacritic_position, :string
      attribute :x_offset_diacritic, :float
      attribute :y_offset_diacritic, :float
      attribute :paragraph_break_type, :string
      attribute :page_number_type, :string
      attribute :character_alignment, :string
      attribute :tsume, :float
      attribute :leading_aki, :float
      attribute :trailing_aki, :float
      attribute :character_rotation, :float
      attribute :jidori, :integer
      attribute :shatai_magnification, :float
      attribute :shatai_degree_angle, :float
      attribute :shatai_adjust_rotation, :boolean
      attribute :shatai_adjust_tsume, :boolean
      attribute :tatechuyoko, :boolean
      attribute :tatechuyoko_x_offset, :float
      attribute :tatechuyoko_y_offset, :float
      attribute :kenten_tint, :float
      attribute :kenten_stroke_tint, :float
      attribute :kenten_weight, :float
      attribute :kenten_overprint_fill, :string
      attribute :kenten_overprint_stroke, :string
      attribute :kenten_kind, :string
      attribute :kenten_placement, :float
      attribute :kenten_alignment, :string
      attribute :kenten_position, :string
      attribute :kenten_font_size, :float
      attribute :kenten_x_scale, :float
      attribute :kenten_y_scale, :float
      attribute :kenten_custom_character, :string
      attribute :kenten_character_set, :string
      attribute :ruby_tint, :float
      attribute :ruby_weight, :float
      attribute :ruby_overprint_fill, :string
      attribute :ruby_overprint_stroke, :string
      attribute :ruby_stroke_tint, :float
      attribute :ruby_font_size, :float
      attribute :ruby_open_type_pro, :boolean
      attribute :ruby_x_scale, :float
      attribute :ruby_y_scale, :float
      attribute :ruby_type, :string
      attribute :ruby_alignment, :string
      attribute :ruby_position, :string
      attribute :ruby_x_offset, :float
      attribute :ruby_y_offset, :float
      attribute :ruby_parent_spacing, :string
      attribute :ruby_auto_align, :boolean
      attribute :ruby_overhang, :boolean
      attribute :ruby_auto_scaling, :boolean
      attribute :ruby_parent_scaling_percent, :float
      attribute :ruby_parent_overhang_amount, :string
      attribute :warichu, :boolean
      attribute :warichu_size, :float
      attribute :warichu_lines, :integer
      attribute :warichu_line_spacing, :float
      attribute :warichu_alignment, :string
      attribute :warichu_chars_after_break, :integer
      attribute :warichu_chars_before_break, :integer
      attribute :otf_proportional_metrics, :boolean
      attribute :otfhv_kana, :boolean
      attribute :otf_roman_italics, :boolean
      attribute :scale_affects_line_height, :boolean
      attribute :cjk_grid_tracking, :boolean
      attribute :glyph_form, :string
      attribute :ruby_auto_tcy_digits, :integer
      attribute :ruby_auto_tcy_include_roman, :boolean
      attribute :ruby_auto_tcy_auto_scale, :boolean

      xml do
        root "CharacterStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "Imported", to: :imported
        map_attribute "FontStyle", to: :font_style
        map_attribute "PointSize", to: :point_size
        map_attribute "KerningMethod", to: :kerning_method
        map_attribute "Tracking", to: :tracking
        map_attribute "Capitalization", to: :capitalization
        map_attribute "Position", to: :position
        map_attribute "Underline", to: :underline
        map_attribute "StrikeThru", to: :strike_thru
        map_attribute "Ligatures", to: :ligatures
        map_attribute "NoBreak", to: :no_break
        map_attribute "HorizontalScale", to: :horizontal_scale
        map_attribute "VerticalScale", to: :vertical_scale
        map_attribute "BaselineShift", to: :baseline_shift
        map_attribute "Skew", to: :skew
        map_attribute "FillTint", to: :fill_tint
        map_attribute "StrokeTint", to: :stroke_tint
        map_attribute "StrokeWeight", to: :stroke_weight
        map_attribute "OverprintStroke", to: :overprint_stroke
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "OTFFigureStyle", to: :otf_figure_style
        map_attribute "OTFOrdinal", to: :otf_ordinal
        map_attribute "OTFFraction", to: :otf_fraction
        map_attribute "OTFDiscretionaryLigature", to: :otf_discretionary_ligature
        map_attribute "OTFTitling", to: :otf_titling
        map_attribute "OTFContextualAlternate", to: :otf_contextual_alternate
        map_attribute "OTFSwash", to: :otf_swash
        map_attribute "UnderlineTint", to: :underline_tint
        map_attribute "UnderlineGapTint", to: :underline_gap_tint
        map_attribute "UnderlineOverprint", to: :underline_overprint
        map_attribute "UnderlineGapOverprint", to: :underline_gap_overprint
        map_attribute "UnderlineOffset", to: :underline_offset
        map_attribute "UnderlineWeight", to: :underline_weight
        map_attribute "StrikeThroughTint", to: :strike_through_tint
        map_attribute "StrikeThroughGapTint", to: :strike_through_gap_tint
        map_attribute "StrikeThroughOverprint", to: :strike_through_overprint
        map_attribute "StrikeThroughGapOverprint", to: :strike_through_gap_overprint
        map_attribute "StrikeThroughOffset", to: :strike_through_offset
        map_attribute "StrikeThroughWeight", to: :strike_through_weight
        map_attribute "FillColor", to: :fill_color
        map_attribute "StrokeColor", to: :stroke_color
        map_attribute "AppliedLanguage", to: :applied_language
        map_attribute "KerningValue", to: :kerning_value
        map_attribute "SplitDocument", to: :split_document
        map_attribute "EmitCss", to: :emit_css
        map_attribute "StyleUniqueId", to: :style_unique_id
        map_attribute "IncludeClass", to: :include_class
        map_attribute "ExtendedKeyboardShortcut", to: :extended_keyboard_shortcut
        map_attribute "EpubAriaRole", to: :epub_aria_role
        map_attribute "KeyboardShortcut", to: :keyboard_shortcut
        map_attribute "OTFSlashedZero", to: :otf_slashed_zero
        map_attribute "OTFHistorical", to: :otf_historical
        map_attribute "OTFStylisticSets", to: :otf_stylistic_sets
        map_attribute "GradientFillLength", to: :gradient_fill_length
        map_attribute "GradientFillAngle", to: :gradient_fill_angle
        map_attribute "GradientStrokeLength", to: :gradient_stroke_length
        map_attribute "GradientStrokeAngle", to: :gradient_stroke_angle
        map_attribute "GradientFillStart", to: :gradient_fill_start
        map_attribute "GradientStrokeStart", to: :gradient_stroke_start
        map_attribute "OTFMark", to: :otf_mark
        map_attribute "OTFLocale", to: :otf_locale
        map_attribute "PositionalForm", to: :positional_form
        map_attribute "Name", to: :name
        map_attribute "MiterLimit", to: :miter_limit
        map_attribute "StrokeAlignment", to: :stroke_alignment
        map_attribute "EndJoin", to: :end_join
        map_attribute "OTFOverlapSwash", to: :otf_overlap_swash
        map_attribute "OTFStylisticAlternate", to: :otf_stylistic_alternate
        map_attribute "OTFJustificationAlternate", to: :otf_justification_alternate
        map_attribute "OTFStretchedAlternate", to: :otf_stretched_alternate
        map_attribute "CharacterDirection", to: :character_direction
        map_attribute "KeyboardDirection", to: :keyboard_direction
        map_attribute "DigitsType", to: :digits_type
        map_attribute "Kashidas", to: :kashidas
        map_attribute "DiacriticPosition", to: :diacritic_position
        map_attribute "XOffsetDiacritic", to: :x_offset_diacritic
        map_attribute "YOffsetDiacritic", to: :y_offset_diacritic
        map_attribute "ParagraphBreakType", to: :paragraph_break_type
        map_attribute "PageNumberType", to: :page_number_type
        map_attribute "CharacterAlignment", to: :character_alignment
        map_attribute "Tsume", to: :tsume
        map_attribute "LeadingAki", to: :leading_aki
        map_attribute "TrailingAki", to: :trailing_aki
        map_attribute "CharacterRotation", to: :character_rotation
        map_attribute "Jidori", to: :jidori
        map_attribute "ShataiMagnification", to: :shatai_magnification
        map_attribute "ShataiDegreeAngle", to: :shatai_degree_angle
        map_attribute "ShataiAdjustRotation", to: :shatai_adjust_rotation
        map_attribute "ShataiAdjustTsume", to: :shatai_adjust_tsume
        map_attribute "Tatechuyoko", to: :tatechuyoko
        map_attribute "TatechuyokoXOffset", to: :tatechuyoko_x_offset
        map_attribute "TatechuyokoYOffset", to: :tatechuyoko_y_offset
        map_attribute "KentenTint", to: :kenten_tint
        map_attribute "KentenStrokeTint", to: :kenten_stroke_tint
        map_attribute "KentenWeight", to: :kenten_weight
        map_attribute "KentenOverprintFill", to: :kenten_overprint_fill
        map_attribute "KentenOverprintStroke", to: :kenten_overprint_stroke
        map_attribute "KentenKind", to: :kenten_kind
        map_attribute "KentenPlacement", to: :kenten_placement
        map_attribute "KentenAlignment", to: :kenten_alignment
        map_attribute "KentenPosition", to: :kenten_position
        map_attribute "KentenFontSize", to: :kenten_font_size
        map_attribute "KentenXScale", to: :kenten_x_scale
        map_attribute "KentenYScale", to: :kenten_y_scale
        map_attribute "KentenCustomCharacter", to: :kenten_custom_character
        map_attribute "KentenCharacterSet", to: :kenten_character_set
        map_attribute "RubyTint", to: :ruby_tint
        map_attribute "RubyWeight", to: :ruby_weight
        map_attribute "RubyOverprintFill", to: :ruby_overprint_fill
        map_attribute "RubyOverprintStroke", to: :ruby_overprint_stroke
        map_attribute "RubyStrokeTint", to: :ruby_stroke_tint
        map_attribute "RubyFontSize", to: :ruby_font_size
        map_attribute "RubyOpenTypePro", to: :ruby_open_type_pro
        map_attribute "RubyXScale", to: :ruby_x_scale
        map_attribute "RubyYScale", to: :ruby_y_scale
        map_attribute "RubyType", to: :ruby_type
        map_attribute "RubyAlignment", to: :ruby_alignment
        map_attribute "RubyPosition", to: :ruby_position
        map_attribute "RubyXOffset", to: :ruby_x_offset
        map_attribute "RubyYOffset", to: :ruby_y_offset
        map_attribute "RubyParentSpacing", to: :ruby_parent_spacing
        map_attribute "RubyAutoAlign", to: :ruby_auto_align
        map_attribute "RubyOverhang", to: :ruby_overhang
        map_attribute "RubyAutoScaling", to: :ruby_auto_scaling
        map_attribute "RubyParentScalingPercent", to: :ruby_parent_scaling_percent
        map_attribute "RubyParentOverhangAmount", to: :ruby_parent_overhang_amount
        map_attribute "Warichu", to: :warichu
        map_attribute "WarichuSize", to: :warichu_size
        map_attribute "WarichuLines", to: :warichu_lines
        map_attribute "WarichuLineSpacing", to: :warichu_line_spacing
        map_attribute "WarichuAlignment", to: :warichu_alignment
        map_attribute "WarichuCharsAfterBreak", to: :warichu_chars_after_break
        map_attribute "WarichuCharsBeforeBreak", to: :warichu_chars_before_break
        map_attribute "OTFProportionalMetrics", to: :otf_proportional_metrics
        map_attribute "OTFHVKana", to: :otfhv_kana
        map_attribute "OTFRomanItalics", to: :otf_roman_italics
        map_attribute "ScaleAffectsLineHeight", to: :scale_affects_line_height
        map_attribute "CjkGridTracking", to: :cjk_grid_tracking
        map_attribute "GlyphForm", to: :glyph_form
        map_attribute "RubyAutoTcyDigits", to: :ruby_auto_tcy_digits
        map_attribute "RubyAutoTcyIncludeRoman", to: :ruby_auto_tcy_include_roman
        map_attribute "RubyAutoTcyAutoScale", to: :ruby_auto_tcy_auto_scale
      end
    end
  end
end
