# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Color>`. Every
    # attribute from `Color_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (16 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Color < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :model, :string
      attribute :space, :string
      attribute :color_value, :string
      attribute :color_override, :string
      attribute :base_color, :string
      attribute :convert_to_hsb, :boolean
      attribute :spot_ink_alias_spot_color_reference, :string
      attribute :alternate_space, :string
      attribute :alternate_color_value, :string
      attribute :name, :string
      attribute :color_editable, :boolean
      attribute :color_removable, :boolean
      attribute :visible, :boolean
      attribute :swatch_creator_id, :integer
      attribute :swatch_color_group_reference, :string

      xml do
        root "Color"
        map_attribute "Self", to: :self_attr
        map_attribute "Model", to: :model
        map_attribute "Space", to: :space
        map_attribute "ColorValue", to: :color_value
        map_attribute "ColorOverride", to: :color_override
        map_attribute "BaseColor", to: :base_color
        map_attribute "ConvertToHsb", to: :convert_to_hsb
        map_attribute "SpotInkAliasSpotColorReference", to: :spot_ink_alias_spot_color_reference
        map_attribute "AlternateSpace", to: :alternate_space
        map_attribute "AlternateColorValue", to: :alternate_color_value
        map_attribute "Name", to: :name
        map_attribute "ColorEditable", to: :color_editable
        map_attribute "ColorRemovable", to: :color_removable
        map_attribute "Visible", to: :visible
        map_attribute "SwatchCreatorID", to: :swatch_creator_id
        map_attribute "SwatchColorGroupReference", to: :swatch_color_group_reference
      end
    end
  end
end
