# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ContentTransparencySetting>`. Every
    # attribute from `ContentTransparencySetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ContentTransparencySetting < Lutaml::Model::Serializable
      xml do
        root "ContentTransparencySetting"
      end
    end
  end
end
