# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ContourOption>`. Every
    # attribute from `ContourOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ContourOption < Lutaml::Model::Serializable
      attribute :contour_type, :string
      attribute :include_inside_edges, :boolean
      attribute :contour_path_name, :string
      attribute :contour_tolerance, :float
      attribute :contour_threshold, :integer
      attribute :contour_alpha_index, :integer
      attribute :contour_path_index, :integer

      xml do
        root "ContourOption"
        map_attribute "ContourType", to: :contour_type
        map_attribute "IncludeInsideEdges", to: :include_inside_edges
        map_attribute "ContourPathName", to: :contour_path_name
        map_attribute "ContourTolerance", to: :contour_tolerance
        map_attribute "ContourThreshold", to: :contour_threshold
        map_attribute "ContourAlphaIndex", to: :contour_alpha_index
        map_attribute "ContourPathIndex", to: :contour_path_index
      end
    end
  end
end
