# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DashedStrokeStyle>`. Every
    # attribute from `DashedStrokeStyle_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DashedStrokeStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :dash_array, :string
      attribute :stroke_corner_adjustment, :string
      attribute :end_cap, :string
      attribute :name, :string

      xml do
        root "DashedStrokeStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "DashArray", to: :dash_array
        map_attribute "StrokeCornerAdjustment", to: :stroke_corner_adjustment
        map_attribute "EndCap", to: :end_cap
        map_attribute "Name", to: :name
      end
    end
  end
end
