# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DirectionalFeatherSetting>`. Every
    # attribute from `DirectionalFeatherSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (9 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DirectionalFeatherSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :left_width, :float
      attribute :right_width, :float
      attribute :top_width, :float
      attribute :bottom_width, :float
      attribute :choke_amount, :float
      attribute :angle, :float
      attribute :follow_shape_mode, :string
      attribute :noise, :float

      xml do
        root "DirectionalFeatherSetting"
        map_attribute "Applied", to: :applied
        map_attribute "LeftWidth", to: :left_width
        map_attribute "RightWidth", to: :right_width
        map_attribute "TopWidth", to: :top_width
        map_attribute "BottomWidth", to: :bottom_width
        map_attribute "ChokeAmount", to: :choke_amount
        map_attribute "Angle", to: :angle
        map_attribute "FollowShapeMode", to: :follow_shape_mode
        map_attribute "Noise", to: :noise
      end
    end
  end
end
