# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DottedStrokeStyle>`. Every
    # attribute from `DottedStrokeStyle_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DottedStrokeStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :dot_array, :string
      attribute :stroke_corner_adjustment, :string
      attribute :name, :string

      xml do
        root "DottedStrokeStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "DotArray", to: :dot_array
        map_attribute "StrokeCornerAdjustment", to: :stroke_corner_adjustment
        map_attribute "Name", to: :name
      end
    end
  end
end
