# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DropShadowSetting>`. Every
    # attribute from `DropShadowSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (14 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DropShadowSetting < Lutaml::Model::Serializable
      attribute :mode, :string
      attribute :blend_mode, :string
      attribute :opacity, :float
      attribute :x_offset, :float
      attribute :y_offset, :float
      attribute :size, :float
      attribute :effect_color, :string
      attribute :noise, :float
      attribute :spread, :float
      attribute :use_global_light, :boolean
      attribute :knocked_out, :boolean
      attribute :honor_other_effects, :boolean
      attribute :distance, :float
      attribute :angle, :float

      xml do
        root "DropShadowSetting"
        map_attribute "Mode", to: :mode
        map_attribute "BlendMode", to: :blend_mode
        map_attribute "Opacity", to: :opacity
        map_attribute "XOffset", to: :x_offset
        map_attribute "YOffset", to: :y_offset
        map_attribute "Size", to: :size
        map_attribute "EffectColor", to: :effect_color
        map_attribute "Noise", to: :noise
        map_attribute "Spread", to: :spread
        map_attribute "UseGlobalLight", to: :use_global_light
        map_attribute "KnockedOut", to: :knocked_out
        map_attribute "HonorOtherEffects", to: :honor_other_effects
        map_attribute "Distance", to: :distance
        map_attribute "Angle", to: :angle
      end
    end
  end
end
