# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FeatherSetting>`. Every
    # attribute from `FeatherSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FeatherSetting < Lutaml::Model::Serializable
      attribute :mode, :string
      attribute :width, :float
      attribute :corner_type, :string
      attribute :noise, :float
      attribute :choke_amount, :float

      xml do
        root "FeatherSetting"
        map_attribute "Mode", to: :mode
        map_attribute "Width", to: :width
        map_attribute "CornerType", to: :corner_type
        map_attribute "Noise", to: :noise
        map_attribute "ChokeAmount", to: :choke_amount
      end
    end
  end
end
