# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FillTransparencySetting>`. Every
    # attribute from `FillTransparencySetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FillTransparencySetting < Lutaml::Model::Serializable
      xml do
        root "FillTransparencySetting"
      end
    end
  end
end
