# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FlexLayoutAttributeOption>`. Every
    # attribute from `FlexLayoutAttributeOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (13 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FlexLayoutAttributeOption < Lutaml::Model::Serializable
      attribute :flex_width_mode, :string
      attribute :flex_height_mode, :string
      attribute :flex_direction, :string
      attribute :flex_wrap, :string
      attribute :justify_content, :string
      attribute :align_items, :string
      attribute :flex_padding_top, :float
      attribute :flex_padding_right, :float
      attribute :flex_padding_bottom, :float
      attribute :flex_padding_left, :float
      attribute :flex_gap_row, :float
      attribute :align_content, :string
      attribute :flex_gap_column, :float

      xml do
        root "FlexLayoutAttributeOption"
        map_attribute "FlexWidthMode", to: :flex_width_mode
        map_attribute "FlexHeightMode", to: :flex_height_mode
        map_attribute "FlexDirection", to: :flex_direction
        map_attribute "FlexWrap", to: :flex_wrap
        map_attribute "JustifyContent", to: :justify_content
        map_attribute "AlignItems", to: :align_items
        map_attribute "FlexPaddingTop", to: :flex_padding_top
        map_attribute "FlexPaddingRight", to: :flex_padding_right
        map_attribute "FlexPaddingBottom", to: :flex_padding_bottom
        map_attribute "FlexPaddingLeft", to: :flex_padding_left
        map_attribute "FlexGapRow", to: :flex_gap_row
        map_attribute "AlignContent", to: :align_content
        map_attribute "FlexGapColumn", to: :flex_gap_column
      end
    end
  end
end
