# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Font>`. Every
    # attribute from `Font_Object` in
    # `reference-docs/schemas/package/Resources/Fonts.rnc` is declared (17 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Font < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :font_family, :string
      attribute :name, :string
      attribute :post_script_name, :string
      attribute :status, :string
      attribute :font_style_name, :string
      attribute :font_type, :string
      attribute :writing_script, :integer
      attribute :full_name, :string
      attribute :full_name_native, :string
      attribute :font_style_name_native, :string
      attribute :platform_name, :string
      attribute :version, :string
      attribute :typekit_id, :string
      attribute :num_design_axes, :integer
      attribute :design_axes_name, :string
      attribute :design_axes_values, :string

      xml do
        root "Font"
        map_attribute "Self", to: :self_attr
        map_attribute "FontFamily", to: :font_family
        map_attribute "Name", to: :name
        map_attribute "PostScriptName", to: :post_script_name
        map_attribute "Status", to: :status
        map_attribute "FontStyleName", to: :font_style_name
        map_attribute "FontType", to: :font_type
        map_attribute "WritingScript", to: :writing_script
        map_attribute "FullName", to: :full_name
        map_attribute "FullNameNative", to: :full_name_native
        map_attribute "FontStyleNameNative", to: :font_style_name_native
        map_attribute "PlatformName", to: :platform_name
        map_attribute "Version", to: :version
        map_attribute "TypekitID", to: :typekit_id
        map_attribute "NumDesignAxes", to: :num_design_axes
        map_attribute "DesignAxesName", to: :design_axes_name
        map_attribute "DesignAxesValues", to: :design_axes_values
      end
    end
  end
end
