# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FontFamily>`. Every
    # attribute from `FontFamily_Object` in
    # `reference-docs/schemas/package/Resources/Fonts.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FontFamily < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string

      attribute :font, Idml::Elements::Font, collection: true

      xml do
        root "FontFamily"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_element "Font", to: :font
      end
    end
  end
end
