# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FrameFittingOption>`. Every
    # attribute from `FrameFittingOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FrameFittingOption < Lutaml::Model::Serializable
      attribute :auto_fit, :boolean
      attribute :left_crop, :float
      attribute :top_crop, :float
      attribute :right_crop, :float
      attribute :bottom_crop, :float
      attribute :fitting_on_empty_frame, :string
      attribute :fitting_alignment, :string

      xml do
        root "FrameFittingOption"
        map_attribute "AutoFit", to: :auto_fit
        map_attribute "LeftCrop", to: :left_crop
        map_attribute "TopCrop", to: :top_crop
        map_attribute "RightCrop", to: :right_crop
        map_attribute "BottomCrop", to: :bottom_crop
        map_attribute "FittingOnEmptyFrame", to: :fitting_on_empty_frame
        map_attribute "FittingAlignment", to: :fitting_alignment
      end
    end
  end
end
