# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<GradientFeatherSetting>`. Every
    # attribute from `GradientFeatherSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class GradientFeatherSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :type, :string
      attribute :angle, :float
      attribute :length, :float
      attribute :gradient_start, :string
      attribute :hilite_angle, :float
      attribute :hilite_length, :float

      xml do
        root "GradientFeatherSetting"
        map_attribute "Applied", to: :applied
        map_attribute "Type", to: :type
        map_attribute "Angle", to: :angle
        map_attribute "Length", to: :length
        map_attribute "GradientStart", to: :gradient_start
        map_attribute "HiliteAngle", to: :hilite_angle
        map_attribute "HiliteLength", to: :hilite_length
      end
    end
  end
end
