# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<GradientStop>`. Every
    # attribute from `GradientStop_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class GradientStop < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :stop_color, :string
      attribute :location, :float
      attribute :midpoint, :float

      xml do
        root "GradientStop"
        map_attribute "Self", to: :self_attr
        map_attribute "StopColor", to: :stop_color
        map_attribute "Location", to: :location
        map_attribute "Midpoint", to: :midpoint
      end
    end
  end
end
