# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Gradient>`. Every
    # attribute from `Gradient_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (8 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Gradient < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :type, :string
      attribute :name, :string
      attribute :color_editable, :boolean
      attribute :color_removable, :boolean
      attribute :visible, :boolean
      attribute :swatch_creator_id, :integer
      attribute :swatch_color_group_reference, :string

      xml do
        root "Gradient"
        map_attribute "Self", to: :self_attr
        map_attribute "Type", to: :type
        map_attribute "Name", to: :name
        map_attribute "ColorEditable", to: :color_editable
        map_attribute "ColorRemovable", to: :color_removable
        map_attribute "Visible", to: :visible
        map_attribute "SwatchCreatorID", to: :swatch_creator_id
        map_attribute "SwatchColorGroupReference", to: :swatch_color_group_reference
      end
    end
  end
end
