# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Ink>`. Every
    # attribute from `Ink_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (10 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Ink < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :alias_ink_name, :string
      attribute :angle, :float
      attribute :convert_to_process, :boolean
      attribute :frequency, :float
      attribute :neutral_density, :float
      attribute :print_ink, :boolean
      attribute :trap_order, :integer
      attribute :ink_type, :string

      xml do
        root "Ink"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "AliasInkName", to: :alias_ink_name
        map_attribute "Angle", to: :angle
        map_attribute "ConvertToProcess", to: :convert_to_process
        map_attribute "Frequency", to: :frequency
        map_attribute "NeutralDensity", to: :neutral_density
        map_attribute "PrintInk", to: :print_ink
        map_attribute "TrapOrder", to: :trap_order
        map_attribute "InkType", to: :ink_type
      end
    end
  end
end
