# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<InnerShadowSetting>`. Every
    # attribute from `InnerShadowSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class InnerShadowSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :effect_color, :string
      attribute :blend_mode, :string
      attribute :opacity, :float
      attribute :angle, :float
      attribute :distance, :float
      attribute :use_global_light, :boolean
      attribute :choke_amount, :float
      attribute :size, :float
      attribute :noise, :float
      attribute :x_offset, :float
      attribute :y_offset, :float

      xml do
        root "InnerShadowSetting"
        map_attribute "Applied", to: :applied
        map_attribute "EffectColor", to: :effect_color
        map_attribute "BlendMode", to: :blend_mode
        map_attribute "Opacity", to: :opacity
        map_attribute "Angle", to: :angle
        map_attribute "Distance", to: :distance
        map_attribute "UseGlobalLight", to: :use_global_light
        map_attribute "ChokeAmount", to: :choke_amount
        map_attribute "Size", to: :size
        map_attribute "Noise", to: :noise
        map_attribute "XOffset", to: :x_offset
        map_attribute "YOffset", to: :y_offset
      end
    end
  end
end
