# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<MasterSpread>`. Every
    # attribute from `MasterSpread_Object` in
    # `reference-docs/schemas/package/MasterSpreads/MasterSpread.rnc` is declared (9 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class MasterSpreadObject < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :name_prefix, :string
      attribute :base_name, :string
      attribute :show_master_items, :boolean
      attribute :page_count, :integer
      attribute :overridden_page_item_props, :string
      attribute :primary_text_frame, :string
      attribute :item_transform, :string

      xml do
        root "MasterSpread"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "NamePrefix", to: :name_prefix
        map_attribute "BaseName", to: :base_name
        map_attribute "ShowMasterItems", to: :show_master_items
        map_attribute "PageCount", to: :page_count
        map_attribute "OverriddenPageItemProps", to: :overridden_page_item_props
        map_attribute "PrimaryTextFrame", to: :primary_text_frame
        map_attribute "ItemTransform", to: :item_transform
      end
    end
  end
end
