# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<MixedInkGroup>`. Every
    # attribute from `MixedInkGroup_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class MixedInkGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :model, :string
      attribute :ink_list, :string
      attribute :ink_name_list, :string
      attribute :mixed_ink_spot_color_name_list, :string
      attribute :mixed_ink_spot_color_list, :string
      attribute :name, :string
      attribute :color_editable, :boolean
      attribute :color_removable, :boolean
      attribute :visible, :boolean
      attribute :swatch_creator_id, :integer
      attribute :swatch_color_group_reference, :string

      xml do
        root "MixedInkGroup"
        map_attribute "Self", to: :self_attr
        map_attribute "Model", to: :model
        map_attribute "InkList", to: :ink_list
        map_attribute "InkNameList", to: :ink_name_list
        map_attribute "MixedInkSpotColorNameList", to: :mixed_ink_spot_color_name_list
        map_attribute "MixedInkSpotColorList", to: :mixed_ink_spot_color_list
        map_attribute "Name", to: :name
        map_attribute "ColorEditable", to: :color_editable
        map_attribute "ColorRemovable", to: :color_removable
        map_attribute "Visible", to: :visible
        map_attribute "SwatchCreatorID", to: :swatch_creator_id
        map_attribute "SwatchColorGroupReference", to: :swatch_color_group_reference
      end
    end
  end
end
