# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ObjectStyleStrokeEffectsCategorySettings>`. Every
    # attribute from `ObjectStyleStrokeEffectsCategorySettings_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (10 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ObjectStyleStrokeEffectsCategorySettings < Lutaml::Model::Serializable
      attribute :enable_transparency, :boolean
      attribute :enable_drop_shadow, :boolean
      attribute :enable_feather, :boolean
      attribute :enable_inner_shadow, :boolean
      attribute :enable_outer_glow, :boolean
      attribute :enable_inner_glow, :boolean
      attribute :enable_bevel_emboss, :boolean
      attribute :enable_satin, :boolean
      attribute :enable_directional_feather, :boolean
      attribute :enable_gradient_feather, :boolean

      xml do
        root "ObjectStyleStrokeEffectsCategorySettings"
        map_attribute "EnableTransparency", to: :enable_transparency
        map_attribute "EnableDropShadow", to: :enable_drop_shadow
        map_attribute "EnableFeather", to: :enable_feather
        map_attribute "EnableInnerShadow", to: :enable_inner_shadow
        map_attribute "EnableOuterGlow", to: :enable_outer_glow
        map_attribute "EnableInnerGlow", to: :enable_inner_glow
        map_attribute "EnableBevelEmboss", to: :enable_bevel_emboss
        map_attribute "EnableSatin", to: :enable_satin
        map_attribute "EnableDirectionalFeather", to: :enable_directional_feather
        map_attribute "EnableGradientFeather", to: :enable_gradient_feather
      end
    end
  end
end
