# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ObjectStyle>`. Every
    # attribute from `ObjectStyle_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (66 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ObjectStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :enable_transform_attributes, :boolean
      attribute :enable_flex_layout_attributes, :boolean
      attribute :top_left_corner_option, :string
      attribute :top_right_corner_option, :string
      attribute :bottom_left_corner_option, :string
      attribute :bottom_right_corner_option, :string
      attribute :top_left_corner_radius, :float
      attribute :top_right_corner_radius, :float
      attribute :bottom_left_corner_radius, :float
      attribute :bottom_right_corner_radius, :float
      attribute :emit_css, :boolean
      attribute :include_class, :boolean
      attribute :epub_aria_role, :string
      attribute :enable_text_frame_auto_sizing_options, :boolean
      attribute :epub_aria_label, :string
      attribute :epub_aria_label_source_type, :string
      attribute :extended_keyboard_shortcut, :string
      attribute :enable_text_frame_column_rule_options, :boolean
      attribute :enable_export_tagging, :boolean
      attribute :enable_object_export_alt_text_options, :boolean
      attribute :enable_object_export_tagged_pdf_options, :boolean
      attribute :enable_object_export_epub_options, :boolean
      attribute :name, :string
      attribute :applied_paragraph_style, :string
      attribute :apply_next_paragraph_style, :boolean
      attribute :enable_fill, :boolean
      attribute :enable_stroke, :boolean
      attribute :enable_paragraph_style, :boolean
      attribute :enable_text_frame_general_options, :boolean
      attribute :enable_text_frame_baseline_options, :boolean
      attribute :enable_story_options, :boolean
      attribute :enable_text_wrap_and_others, :boolean
      attribute :enable_anchored_object_options, :boolean
      attribute :corner_radius, :float
      attribute :fill_color, :string
      attribute :fill_tint, :float
      attribute :overprint_fill, :boolean
      attribute :stroke_weight, :float
      attribute :miter_limit, :float
      attribute :end_cap, :string
      attribute :end_join, :string
      attribute :stroke_type, :string
      attribute :left_line_end, :string
      attribute :right_line_end, :string
      attribute :stroke_color, :string
      attribute :stroke_tint, :float
      attribute :overprint_stroke, :boolean
      attribute :gap_color, :string
      attribute :gap_tint, :float
      attribute :overprint_gap, :boolean
      attribute :stroke_alignment, :string
      attribute :nonprinting, :boolean
      attribute :gradient_fill_angle, :float
      attribute :gradient_stroke_angle, :float
      attribute :stroke_corner_adjustment, :string
      attribute :stroke_dash_and_gap, :string
      attribute :applied_named_grid, :string
      attribute :keyboard_shortcut, :string
      attribute :enable_frame_fitting_options, :boolean
      attribute :corner_option, :string
      attribute :enable_stroke_and_corner_options, :boolean
      attribute :arrow_head_alignment, :string
      attribute :left_arrow_head_scale, :float
      attribute :right_arrow_head_scale, :float
      attribute :enable_text_frame_footnote_options, :boolean

      xml do
        root "ObjectStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "EnableTransformAttributes", to: :enable_transform_attributes
        map_attribute "EnableFlexLayoutAttributes", to: :enable_flex_layout_attributes
        map_attribute "TopLeftCornerOption", to: :top_left_corner_option
        map_attribute "TopRightCornerOption", to: :top_right_corner_option
        map_attribute "BottomLeftCornerOption", to: :bottom_left_corner_option
        map_attribute "BottomRightCornerOption", to: :bottom_right_corner_option
        map_attribute "TopLeftCornerRadius", to: :top_left_corner_radius
        map_attribute "TopRightCornerRadius", to: :top_right_corner_radius
        map_attribute "BottomLeftCornerRadius", to: :bottom_left_corner_radius
        map_attribute "BottomRightCornerRadius", to: :bottom_right_corner_radius
        map_attribute "EmitCss", to: :emit_css
        map_attribute "IncludeClass", to: :include_class
        map_attribute "EpubAriaRole", to: :epub_aria_role
        map_attribute "EnableTextFrameAutoSizingOptions", to: :enable_text_frame_auto_sizing_options
        map_attribute "EpubAriaLabel", to: :epub_aria_label
        map_attribute "EpubAriaLabelSourceType", to: :epub_aria_label_source_type
        map_attribute "ExtendedKeyboardShortcut", to: :extended_keyboard_shortcut
        map_attribute "EnableTextFrameColumnRuleOptions", to: :enable_text_frame_column_rule_options
        map_attribute "EnableExportTagging", to: :enable_export_tagging
        map_attribute "EnableObjectExportAltTextOptions", to: :enable_object_export_alt_text_options
        map_attribute "EnableObjectExportTaggedPdfOptions", to: :enable_object_export_tagged_pdf_options
        map_attribute "EnableObjectExportEpubOptions", to: :enable_object_export_epub_options
        map_attribute "Name", to: :name
        map_attribute "AppliedParagraphStyle", to: :applied_paragraph_style
        map_attribute "ApplyNextParagraphStyle", to: :apply_next_paragraph_style
        map_attribute "EnableFill", to: :enable_fill
        map_attribute "EnableStroke", to: :enable_stroke
        map_attribute "EnableParagraphStyle", to: :enable_paragraph_style
        map_attribute "EnableTextFrameGeneralOptions", to: :enable_text_frame_general_options
        map_attribute "EnableTextFrameBaselineOptions", to: :enable_text_frame_baseline_options
        map_attribute "EnableStoryOptions", to: :enable_story_options
        map_attribute "EnableTextWrapAndOthers", to: :enable_text_wrap_and_others
        map_attribute "EnableAnchoredObjectOptions", to: :enable_anchored_object_options
        map_attribute "CornerRadius", to: :corner_radius
        map_attribute "FillColor", to: :fill_color
        map_attribute "FillTint", to: :fill_tint
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "StrokeWeight", to: :stroke_weight
        map_attribute "MiterLimit", to: :miter_limit
        map_attribute "EndCap", to: :end_cap
        map_attribute "EndJoin", to: :end_join
        map_attribute "StrokeType", to: :stroke_type
        map_attribute "LeftLineEnd", to: :left_line_end
        map_attribute "RightLineEnd", to: :right_line_end
        map_attribute "StrokeColor", to: :stroke_color
        map_attribute "StrokeTint", to: :stroke_tint
        map_attribute "OverprintStroke", to: :overprint_stroke
        map_attribute "GapColor", to: :gap_color
        map_attribute "GapTint", to: :gap_tint
        map_attribute "OverprintGap", to: :overprint_gap
        map_attribute "StrokeAlignment", to: :stroke_alignment
        map_attribute "Nonprinting", to: :nonprinting
        map_attribute "GradientFillAngle", to: :gradient_fill_angle
        map_attribute "GradientStrokeAngle", to: :gradient_stroke_angle
        map_attribute "StrokeCornerAdjustment", to: :stroke_corner_adjustment
        map_attribute "StrokeDashAndGap", to: :stroke_dash_and_gap
        map_attribute "AppliedNamedGrid", to: :applied_named_grid
        map_attribute "KeyboardShortcut", to: :keyboard_shortcut
        map_attribute "EnableFrameFittingOptions", to: :enable_frame_fitting_options
        map_attribute "CornerOption", to: :corner_option
        map_attribute "EnableStrokeAndCornerOptions", to: :enable_stroke_and_corner_options
        map_attribute "ArrowHeadAlignment", to: :arrow_head_alignment
        map_attribute "LeftArrowHeadScale", to: :left_arrow_head_scale
        map_attribute "RightArrowHeadScale", to: :right_arrow_head_scale
        map_attribute "EnableTextFrameFootnoteOptions", to: :enable_text_frame_footnote_options
      end
    end
  end
end
