# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ObjectExportOption>`. Every
    # attribute from `ObjectExportOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (42 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ObjectExportOption < Lutaml::Model::Serializable
      attribute :alt_text_source_type, :string
      attribute :actual_text_source_type, :string
      attribute :custom_alt_text, :string
      attribute :custom_actual_text, :string
      attribute :apply_tag_type, :string
      attribute :image_conversion_type, :string
      attribute :image_export_resolution, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string
      attribute :image_alignment, :string
      attribute :image_space_before, :float
      attribute :image_space_after, :float
      attribute :use_image_page_break, :boolean
      attribute :image_page_break, :string
      attribute :custom_image_alignment, :boolean
      attribute :space_unit, :string
      attribute :custom_image_size_option, :string
      attribute :custom_image_conversion, :boolean
      attribute :custom_layout, :boolean
      attribute :custom_layout_type, :string
      attribute :use_original_image, :boolean
      attribute :epub_type, :string
      attribute :custom_height_type, :string
      attribute :custom_height, :string
      attribute :custom_width_type, :string
      attribute :custom_width, :string
      attribute :use_existing_image, :boolean
      attribute :size_type, :string
      attribute :custom_size, :string
      attribute :preserve_appearance_from_layout, :string
      attribute :epub_aria_role, :string
      attribute :epub_aria_label, :string
      attribute :epub_aria_label_source_type, :string
      attribute :alt_text_generation_error, :boolean
      attribute :alt_text_crop_sync_rect, :string
      attribute :ai_generated_alt_text, :boolean
      attribute :namespace_prefix, :string
      attribute :property_path, :string
      attribute :namespace_prefix, :string
      attribute :property_path, :string

      xml do
        root "ObjectExportOption"
        map_attribute "AltTextSourceType", to: :alt_text_source_type
        map_attribute "ActualTextSourceType", to: :actual_text_source_type
        map_attribute "CustomAltText", to: :custom_alt_text
        map_attribute "CustomActualText", to: :custom_actual_text
        map_attribute "ApplyTagType", to: :apply_tag_type
        map_attribute "ImageConversionType", to: :image_conversion_type
        map_attribute "ImageExportResolution", to: :image_export_resolution
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
        map_attribute "ImageAlignment", to: :image_alignment
        map_attribute "ImageSpaceBefore", to: :image_space_before
        map_attribute "ImageSpaceAfter", to: :image_space_after
        map_attribute "UseImagePageBreak", to: :use_image_page_break
        map_attribute "ImagePageBreak", to: :image_page_break
        map_attribute "CustomImageAlignment", to: :custom_image_alignment
        map_attribute "SpaceUnit", to: :space_unit
        map_attribute "CustomImageSizeOption", to: :custom_image_size_option
        map_attribute "CustomImageConversion", to: :custom_image_conversion
        map_attribute "CustomLayout", to: :custom_layout
        map_attribute "CustomLayoutType", to: :custom_layout_type
        map_attribute "UseOriginalImage", to: :use_original_image
        map_attribute "EpubType", to: :epub_type
        map_attribute "CustomHeightType", to: :custom_height_type
        map_attribute "CustomHeight", to: :custom_height
        map_attribute "CustomWidthType", to: :custom_width_type
        map_attribute "CustomWidth", to: :custom_width
        map_attribute "UseExistingImage", to: :use_existing_image
        map_attribute "SizeType", to: :size_type
        map_attribute "CustomSize", to: :custom_size
        map_attribute "PreserveAppearanceFromLayout", to: :preserve_appearance_from_layout
        map_attribute "EpubAriaRole", to: :epub_aria_role
        map_attribute "EpubAriaLabel", to: :epub_aria_label
        map_attribute "EpubAriaLabelSourceType", to: :epub_aria_label_source_type
        map_attribute "AltTextGenerationError", to: :alt_text_generation_error
        map_attribute "AltTextCropSyncRect", to: :alt_text_crop_sync_rect
        map_attribute "AIGeneratedAltText", to: :ai_generated_alt_text
        map_attribute "NamespacePrefix", to: :namespace_prefix
        map_attribute "PropertyPath", to: :property_path
        map_attribute "NamespacePrefix", to: :namespace_prefix
        map_attribute "PropertyPath", to: :property_path
      end
    end
  end
end
