# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<OpacityGradientStop>`. Every
    # attribute from `OpacityGradientStop_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class OpacityGradientStop < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :opacity, :float
      attribute :location, :float
      attribute :midpoint, :float

      xml do
        root "OpacityGradientStop"
        map_attribute "Self", to: :self_attr
        map_attribute "Opacity", to: :opacity
        map_attribute "Location", to: :location
        map_attribute "Midpoint", to: :midpoint
      end
    end
  end
end
