# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<OuterGlowSetting>`. Every
    # attribute from `OuterGlowSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (8 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class OuterGlowSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :blend_mode, :string
      attribute :opacity, :float
      attribute :noise, :float
      attribute :effect_color, :string
      attribute :technique, :string
      attribute :spread, :float
      attribute :size, :float

      xml do
        root "OuterGlowSetting"
        map_attribute "Applied", to: :applied
        map_attribute "BlendMode", to: :blend_mode
        map_attribute "Opacity", to: :opacity
        map_attribute "Noise", to: :noise
        map_attribute "EffectColor", to: :effect_color
        map_attribute "Technique", to: :technique
        map_attribute "Spread", to: :spread
        map_attribute "Size", to: :size
      end
    end
  end
end
