# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<PastedSmoothShade>`. Every
    # attribute from `PastedSmoothShade_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class PastedSmoothShade < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :contents_version, :integer
      attribute :contents_type, :string
      attribute :spot_color_list, :string
      attribute :contents_encoding, :string
      attribute :contents_matrix, :string
      attribute :name, :string
      attribute :color_editable, :boolean
      attribute :color_removable, :boolean
      attribute :visible, :boolean
      attribute :swatch_creator_id, :integer
      attribute :swatch_color_group_reference, :string

      xml do
        root "PastedSmoothShade"
        map_attribute "Self", to: :self_attr
        map_attribute "ContentsVersion", to: :contents_version
        map_attribute "ContentsType", to: :contents_type
        map_attribute "SpotColorList", to: :spot_color_list
        map_attribute "ContentsEncoding", to: :contents_encoding
        map_attribute "ContentsMatrix", to: :contents_matrix
        map_attribute "Name", to: :name
        map_attribute "ColorEditable", to: :color_editable
        map_attribute "ColorRemovable", to: :color_removable
        map_attribute "Visible", to: :visible
        map_attribute "SwatchCreatorID", to: :swatch_creator_id
        map_attribute "SwatchColorGroupReference", to: :swatch_color_group_reference
      end
    end
  end
end
