# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<CjkGridPreference>`. Every
    # attribute from `CjkGridPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (9 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class CjkGridPreference < Lutaml::Model::Serializable
      attribute :show_all_layout_grids, :boolean
      attribute :show_all_frame_grids, :boolean
      attribute :minimum_scale, :float
      attribute :snap_to_layout_grid, :boolean
      attribute :color_every_nth_cell, :integer
      attribute :single_line_color_mode, :boolean
      attribute :icf_mode, :boolean
      attribute :use_circular_cells, :boolean
      attribute :show_character_count, :boolean

      xml do
        root "CjkGridPreference"
        map_attribute "ShowAllLayoutGrids", to: :show_all_layout_grids
        map_attribute "ShowAllFrameGrids", to: :show_all_frame_grids
        map_attribute "MinimumScale", to: :minimum_scale
        map_attribute "SnapToLayoutGrid", to: :snap_to_layout_grid
        map_attribute "ColorEveryNthCell", to: :color_every_nth_cell
        map_attribute "SingleLineColorMode", to: :single_line_color_mode
        map_attribute "ICFMode", to: :icf_mode
        map_attribute "UseCircularCells", to: :use_circular_cells
        map_attribute "ShowCharacterCount", to: :show_character_count
      end
    end
  end
end
