# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TextPreference>`. Every
    # attribute from `TextPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (34 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TextPreference < Lutaml::Model::Serializable
      attribute :typographers_quotes, :boolean
      attribute :highlight_hj_violations, :boolean
      attribute :highlight_keeps, :boolean
      attribute :highlight_substituted_glyphs, :boolean
      attribute :highlight_custom_spacing, :boolean
      attribute :highlight_substituted_fonts, :boolean
      attribute :use_optical_size, :boolean
      attribute :use_paragraph_leading, :boolean
      attribute :superscript_size, :float
      attribute :superscript_position, :float
      attribute :subscript_size, :float
      attribute :subscript_position, :float
      attribute :small_cap, :float
      attribute :leading_key_increment, :float
      attribute :baseline_shift_key_increment, :float
      attribute :kerning_key_increment, :float
      attribute :show_invisibles, :boolean
      attribute :justify_text_wraps, :boolean
      attribute :abut_text_to_text_wrap, :boolean
      attribute :z_order_text_wrap, :boolean
      attribute :link_text_files_when_importing, :boolean
      attribute :highlight_kinsoku, :boolean
      attribute :quote_characters_rotated_in_vertical, :boolean
      attribute :smart_text_reflow_sync, :boolean
      attribute :shape_indic_and_latin_with_harbuzz, :boolean
      attribute :use_new_vertical_scaling, :boolean
      attribute :use_cid_mojikumi, :boolean
      attribute :honour_text_indents_with_text_wrap, :boolean
      attribute :enable_style_preview_mode, :boolean
      attribute :smart_text_reflow, :boolean
      attribute :add_pages, :string
      attribute :limit_to_master_text_frames, :boolean
      attribute :preserve_facing_page_spreads, :boolean
      attribute :delete_empty_pages, :boolean

      xml do
        root "TextPreference"
        map_attribute "TypographersQuotes", to: :typographers_quotes
        map_attribute "HighlightHjViolations", to: :highlight_hj_violations
        map_attribute "HighlightKeeps", to: :highlight_keeps
        map_attribute "HighlightSubstitutedGlyphs", to: :highlight_substituted_glyphs
        map_attribute "HighlightCustomSpacing", to: :highlight_custom_spacing
        map_attribute "HighlightSubstitutedFonts", to: :highlight_substituted_fonts
        map_attribute "UseOpticalSize", to: :use_optical_size
        map_attribute "UseParagraphLeading", to: :use_paragraph_leading
        map_attribute "SuperscriptSize", to: :superscript_size
        map_attribute "SuperscriptPosition", to: :superscript_position
        map_attribute "SubscriptSize", to: :subscript_size
        map_attribute "SubscriptPosition", to: :subscript_position
        map_attribute "SmallCap", to: :small_cap
        map_attribute "LeadingKeyIncrement", to: :leading_key_increment
        map_attribute "BaselineShiftKeyIncrement", to: :baseline_shift_key_increment
        map_attribute "KerningKeyIncrement", to: :kerning_key_increment
        map_attribute "ShowInvisibles", to: :show_invisibles
        map_attribute "JustifyTextWraps", to: :justify_text_wraps
        map_attribute "AbutTextToTextWrap", to: :abut_text_to_text_wrap
        map_attribute "ZOrderTextWrap", to: :z_order_text_wrap
        map_attribute "LinkTextFilesWhenImporting", to: :link_text_files_when_importing
        map_attribute "HighlightKinsoku", to: :highlight_kinsoku
        map_attribute "QuoteCharactersRotatedInVertical", to: :quote_characters_rotated_in_vertical
        map_attribute "SmartTextReflowSync", to: :smart_text_reflow_sync
        map_attribute "ShapeIndicAndLatinWithHarbuzz", to: :shape_indic_and_latin_with_harbuzz
        map_attribute "UseNewVerticalScaling", to: :use_new_vertical_scaling
        map_attribute "UseCidMojikumi", to: :use_cid_mojikumi
        map_attribute "HonourTextIndentsWithTextWrap", to: :honour_text_indents_with_text_wrap
        map_attribute "EnableStylePreviewMode", to: :enable_style_preview_mode
        map_attribute "SmartTextReflow", to: :smart_text_reflow
        map_attribute "AddPages", to: :add_pages
        map_attribute "LimitToMasterTextFrames", to: :limit_to_master_text_frames
        map_attribute "PreserveFacingPageSpreads", to: :preserve_facing_page_spreads
        map_attribute "DeleteEmptyPages", to: :delete_empty_pages
      end
    end
  end
end
