# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StoryGridDataInformation>`. Every
    # attribute from `StoryGridDataInformation_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StoryGridDataInformation < Lutaml::Model::Serializable
      attribute :font_style, :string
      attribute :point_size, :float
      attribute :character_aki, :float
      attribute :line_aki, :float
      attribute :horizontal_scale, :float
      attribute :vertical_scale, :float
      attribute :line_alignment, :string
      attribute :grid_alignment, :string
      attribute :character_alignment, :string
      attribute :grid_view, :string
      attribute :character_count_location, :string
      attribute :character_count_size, :float

      xml do
        root "StoryGridDataInformation"
        map_attribute "FontStyle", to: :font_style
        map_attribute "PointSize", to: :point_size
        map_attribute "CharacterAki", to: :character_aki
        map_attribute "LineAki", to: :line_aki
        map_attribute "HorizontalScale", to: :horizontal_scale
        map_attribute "VerticalScale", to: :vertical_scale
        map_attribute "LineAlignment", to: :line_alignment
        map_attribute "GridAlignment", to: :grid_alignment
        map_attribute "CharacterAlignment", to: :character_alignment
        map_attribute "GridView", to: :grid_view
        map_attribute "CharacterCountLocation", to: :character_count_location
        map_attribute "CharacterCountSize", to: :character_count_size
      end
    end
  end
end
