# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<GridPreference>`. Every
    # attribute from `GridPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class GridPreference < Lutaml::Model::Serializable
      attribute :document_grid_shown, :boolean
      attribute :document_grid_snapto, :boolean
      attribute :horizontal_gridline_division, :float
      attribute :vertical_gridline_division, :float
      attribute :horizontal_grid_subdivision, :integer
      attribute :vertical_grid_subdivision, :integer
      attribute :grids_in_back, :boolean
      attribute :baseline_grid_shown, :boolean
      attribute :baseline_start, :float
      attribute :baseline_division, :float
      attribute :baseline_view_threshold, :float
      attribute :baseline_grid_relative_option, :string

      xml do
        root "GridPreference"
        map_attribute "DocumentGridShown", to: :document_grid_shown
        map_attribute "DocumentGridSnapto", to: :document_grid_snapto
        map_attribute "HorizontalGridlineDivision", to: :horizontal_gridline_division
        map_attribute "VerticalGridlineDivision", to: :vertical_gridline_division
        map_attribute "HorizontalGridSubdivision", to: :horizontal_grid_subdivision
        map_attribute "VerticalGridSubdivision", to: :vertical_grid_subdivision
        map_attribute "GridsInBack", to: :grids_in_back
        map_attribute "BaselineGridShown", to: :baseline_grid_shown
        map_attribute "BaselineStart", to: :baseline_start
        map_attribute "BaselineDivision", to: :baseline_division
        map_attribute "BaselineViewThreshold", to: :baseline_view_threshold
        map_attribute "BaselineGridRelativeOption", to: :baseline_grid_relative_option
      end
    end
  end
end
