# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ExportForWebPreference>`. Every
    # attribute from `ExportForWebPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (8 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ExportForWebPreference < Lutaml::Model::Serializable
      attribute :copy_formatted_images, :boolean
      attribute :copy_optimized_images, :boolean
      attribute :copy_original_images, :boolean
      attribute :image_conversion, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string

      xml do
        root "ExportForWebPreference"
        map_attribute "CopyFormattedImages", to: :copy_formatted_images
        map_attribute "CopyOptimizedImages", to: :copy_optimized_images
        map_attribute "CopyOriginalImages", to: :copy_original_images
        map_attribute "ImageConversion", to: :image_conversion
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
      end
    end
  end
end
