# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<PrintBookletOption>`. Every
    # attribute from `PrintBookletOption_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class PrintBookletOption < Lutaml::Model::Serializable
      attribute :booklet_type, :string
      attribute :space_between_pages, :float
      attribute :bleed_between_pages, :float
      attribute :creep, :float
      attribute :signature_size, :string
      attribute :top_margin, :float
      attribute :bottom_margin, :float
      attribute :left_margin, :float
      attribute :right_margin, :float
      attribute :auto_adjust_margins, :boolean
      attribute :margins_uniform_size, :boolean
      attribute :print_blank_printer_spreads, :boolean

      xml do
        root "PrintBookletOption"
        map_attribute "BookletType", to: :booklet_type
        map_attribute "SpaceBetweenPages", to: :space_between_pages
        map_attribute "BleedBetweenPages", to: :bleed_between_pages
        map_attribute "Creep", to: :creep
        map_attribute "SignatureSize", to: :signature_size
        map_attribute "TopMargin", to: :top_margin
        map_attribute "BottomMargin", to: :bottom_margin
        map_attribute "LeftMargin", to: :left_margin
        map_attribute "RightMargin", to: :right_margin
        map_attribute "AutoAdjustMargins", to: :auto_adjust_margins
        map_attribute "MarginsUniformSize", to: :margins_uniform_size
        map_attribute "PrintBlankPrinterSpreads", to: :print_blank_printer_spreads
      end
    end
  end
end
