# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<EPubFixedLayoutExportPreference>`. Every
    # attribute from `EPubFixedLayoutExportPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (33 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class EPubFixedLayoutExportPreference < Lutaml::Model::Serializable
      attribute :level, :integer
      attribute :epub_publisher, :string
      attribute :id, :string
      attribute :epub_cover, :string
      attribute :cover_image_file, :string
      attribute :image_export_resolution, :string
      attribute :image_conversion, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string
      attribute :toc_style_name, :string
      attribute :external_style_sheets, :string
      attribute :javascripts, :string
      attribute :epub_title, :string
      attribute :epub_creator, :string
      attribute :epub_subject, :string
      attribute :epub_description, :string
      attribute :epub_date, :string
      attribute :epub_rights, :string
      attribute :epub_page_range, :string
      attribute :epub_page_range_format, :string
      attribute :epub_spread_control_options, :string
      attribute :epub_navigation_styles, :string
      attribute :epub_accessibility_feature, :string
      attribute :epub_accessibility_hazard, :string
      attribute :epub_accessibility_mode, :string
      attribute :epub_accessibility_mode_sufficient, :string
      attribute :epub_accessibility_summary, :string
      attribute :epub_accessibility_conforms_to, :string
      attribute :epub_accessibility_certified_by, :string
      attribute :epub_accessibility_credentials, :string
      attribute :epub_accessibility_report_link, :string

      xml do
        root "EPubFixedLayoutExportPreference"
        map_attribute "Level", to: :level
        map_attribute "EpubPublisher", to: :epub_publisher
        map_attribute "Id", to: :id
        map_attribute "EpubCover", to: :epub_cover
        map_attribute "CoverImageFile", to: :cover_image_file
        map_attribute "ImageExportResolution", to: :image_export_resolution
        map_attribute "ImageConversion", to: :image_conversion
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
        map_attribute "TocStyleName", to: :toc_style_name
        map_attribute "ExternalStyleSheets", to: :external_style_sheets
        map_attribute "Javascripts", to: :javascripts
        map_attribute "EpubTitle", to: :epub_title
        map_attribute "EpubCreator", to: :epub_creator
        map_attribute "EpubSubject", to: :epub_subject
        map_attribute "EpubDescription", to: :epub_description
        map_attribute "EpubDate", to: :epub_date
        map_attribute "EpubRights", to: :epub_rights
        map_attribute "EpubPageRange", to: :epub_page_range
        map_attribute "EpubPageRangeFormat", to: :epub_page_range_format
        map_attribute "EpubSpreadControlOptions", to: :epub_spread_control_options
        map_attribute "EpubNavigationStyles", to: :epub_navigation_styles
        map_attribute "EpubAccessibilityFeature", to: :epub_accessibility_feature
        map_attribute "EpubAccessibilityHazard", to: :epub_accessibility_hazard
        map_attribute "EpubAccessibilityMode", to: :epub_accessibility_mode
        map_attribute "EpubAccessibilityModeSufficient", to: :epub_accessibility_mode_sufficient
        map_attribute "EpubAccessibilitySummary", to: :epub_accessibility_summary
        map_attribute "EpubAccessibilityConformsTo", to: :epub_accessibility_conforms_to
        map_attribute "EpubAccessibilityCertifiedBy", to: :epub_accessibility_certified_by
        map_attribute "EpubAccessibilityCredentials", to: :epub_accessibility_credentials
        map_attribute "EpubAccessibilityReportLink", to: :epub_accessibility_report_link
      end
    end
  end
end
