# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ButtonPreference>`. Every
    # attribute from `ButtonPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ButtonPreference < Lutaml::Model::Serializable
      attribute :name, :string

      xml do
        root "ButtonPreference"
        map_attribute "Name", to: :name
      end
    end
  end
end
