# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<EPubExportPreference>`. Every
    # attribute from `EPubExportPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (68 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class EPubExportPreference < Lutaml::Model::Serializable
      attribute :epub_publisher, :string
      attribute :id, :string
      attribute :export_order, :string
      attribute :epub_cover, :string
      attribute :cover_image_file, :string
      attribute :bullet_export_option, :string
      attribute :numbered_list_export_option, :string
      attribute :left_margin, :float
      attribute :right_margin, :float
      attribute :top_margin, :float
      attribute :bottom_margin, :float
      attribute :image_export_resolution, :string
      attribute :custom_image_size_option, :string
      attribute :preserve_layout_appearence, :boolean
      attribute :image_alignment, :string
      attribute :image_space_before, :float
      attribute :image_space_after, :float
      attribute :use_image_page_break, :boolean
      attribute :image_page_break, :string
      attribute :image_conversion, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string
      attribute :ignore_object_conversion_settings, :boolean
      attribute :toc_style_name, :string
      attribute :break_document, :boolean
      attribute :paragraph_style_name, :string
      attribute :strip_soft_return, :boolean
      attribute :preserve_local_override, :boolean
      attribute :embed_font, :boolean
      attribute :include_document_metadata, :boolean
      attribute :level, :integer
      attribute :view_document_after_export, :boolean
      attribute :margin_unit, :string
      attribute :space_unit, :string
      attribute :css_export_option, :string
      attribute :format, :boolean
      attribute :use_toc_style, :boolean
      attribute :external_css_path, :string
      attribute :include_css_definition, :boolean
      attribute :apply_image_alignment_to_anchored_object_settings, :boolean
      attribute :footnote_follow_paragraph, :boolean
      attribute :external_style_sheets, :string
      attribute :javascripts, :string
      attribute :version, :string
      attribute :generate_cascade_style_sheet, :boolean
      attribute :footnote_placement, :string
      attribute :use_original_image_on_export, :boolean
      attribute :epub_title, :string
      attribute :epub_creator, :string
      attribute :epub_subject, :string
      attribute :epub_description, :string
      attribute :epub_date, :string
      attribute :epub_rights, :string
      attribute :use_existing_image_on_export, :boolean
      attribute :include_classes_in_html, :boolean
      attribute :use_svg_as, :string
      attribute :epub_accessibility_feature, :string
      attribute :epub_accessibility_hazard, :string
      attribute :epub_accessibility_mode, :string
      attribute :epub_accessibility_mode_sufficient, :string
      attribute :epub_accessibility_summary, :string
      attribute :epub_accessibility_conforms_to, :string
      attribute :epub_accessibility_certified_by, :string
      attribute :epub_accessibility_credentials, :string
      attribute :epub_accessibility_report_link, :string
      attribute :epub_create_page_navigation, :boolean

      xml do
        root "EPubExportPreference"
        map_attribute "EpubPublisher", to: :epub_publisher
        map_attribute "Id", to: :id
        map_attribute "ExportOrder", to: :export_order
        map_attribute "EpubCover", to: :epub_cover
        map_attribute "CoverImageFile", to: :cover_image_file
        map_attribute "BulletExportOption", to: :bullet_export_option
        map_attribute "NumberedListExportOption", to: :numbered_list_export_option
        map_attribute "LeftMargin", to: :left_margin
        map_attribute "RightMargin", to: :right_margin
        map_attribute "TopMargin", to: :top_margin
        map_attribute "BottomMargin", to: :bottom_margin
        map_attribute "ImageExportResolution", to: :image_export_resolution
        map_attribute "CustomImageSizeOption", to: :custom_image_size_option
        map_attribute "PreserveLayoutAppearence", to: :preserve_layout_appearence
        map_attribute "ImageAlignment", to: :image_alignment
        map_attribute "ImageSpaceBefore", to: :image_space_before
        map_attribute "ImageSpaceAfter", to: :image_space_after
        map_attribute "UseImagePageBreak", to: :use_image_page_break
        map_attribute "ImagePageBreak", to: :image_page_break
        map_attribute "ImageConversion", to: :image_conversion
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
        map_attribute "IgnoreObjectConversionSettings", to: :ignore_object_conversion_settings
        map_attribute "TocStyleName", to: :toc_style_name
        map_attribute "BreakDocument", to: :break_document
        map_attribute "ParagraphStyleName", to: :paragraph_style_name
        map_attribute "StripSoftReturn", to: :strip_soft_return
        map_attribute "PreserveLocalOverride", to: :preserve_local_override
        map_attribute "EmbedFont", to: :embed_font
        map_attribute "IncludeDocumentMetadata", to: :include_document_metadata
        map_attribute "Level", to: :level
        map_attribute "ViewDocumentAfterExport", to: :view_document_after_export
        map_attribute "MarginUnit", to: :margin_unit
        map_attribute "SpaceUnit", to: :space_unit
        map_attribute "CSSExportOption", to: :css_export_option
        map_attribute "Format", to: :format
        map_attribute "UseTocStyle", to: :use_toc_style
        map_attribute "ExternalCSSPath", to: :external_css_path
        map_attribute "IncludeCSSDefinition", to: :include_css_definition
        map_attribute "ApplyImageAlignmentToAnchoredObjectSettings", to: :apply_image_alignment_to_anchored_object_settings
        map_attribute "FootnoteFollowParagraph", to: :footnote_follow_paragraph
        map_attribute "ExternalStyleSheets", to: :external_style_sheets
        map_attribute "Javascripts", to: :javascripts
        map_attribute "Version", to: :version
        map_attribute "GenerateCascadeStyleSheet", to: :generate_cascade_style_sheet
        map_attribute "FootnotePlacement", to: :footnote_placement
        map_attribute "UseOriginalImageOnExport", to: :use_original_image_on_export
        map_attribute "EpubTitle", to: :epub_title
        map_attribute "EpubCreator", to: :epub_creator
        map_attribute "EpubSubject", to: :epub_subject
        map_attribute "EpubDescription", to: :epub_description
        map_attribute "EpubDate", to: :epub_date
        map_attribute "EpubRights", to: :epub_rights
        map_attribute "UseExistingImageOnExport", to: :use_existing_image_on_export
        map_attribute "IncludeClassesInHTML", to: :include_classes_in_html
        map_attribute "UseSVGAs", to: :use_svg_as
        map_attribute "EpubAccessibilityFeature", to: :epub_accessibility_feature
        map_attribute "EpubAccessibilityHazard", to: :epub_accessibility_hazard
        map_attribute "EpubAccessibilityMode", to: :epub_accessibility_mode
        map_attribute "EpubAccessibilityModeSufficient", to: :epub_accessibility_mode_sufficient
        map_attribute "EpubAccessibilitySummary", to: :epub_accessibility_summary
        map_attribute "EpubAccessibilityConformsTo", to: :epub_accessibility_conforms_to
        map_attribute "EpubAccessibilityCertifiedBy", to: :epub_accessibility_certified_by
        map_attribute "EpubAccessibilityCredentials", to: :epub_accessibility_credentials
        map_attribute "EpubAccessibilityReportLink", to: :epub_accessibility_report_link
        map_attribute "EpubCreatePageNavigation", to: :epub_create_page_navigation
      end
    end
  end
end
