# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TransparencyPreference>`. Every
    # attribute from `TransparencyPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (3 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TransparencyPreference < Lutaml::Model::Serializable
      attribute :blending_space, :string
      attribute :global_light_angle, :float
      attribute :global_light_altitude, :float

      xml do
        root "TransparencyPreference"
        map_attribute "BlendingSpace", to: :blending_space
        map_attribute "GlobalLightAngle", to: :global_light_angle
        map_attribute "GlobalLightAltitude", to: :global_light_altitude
      end
    end
  end
end
