# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TransparencyDefaultContainerObject>`. Every
    # attribute from `TransparencyDefaultContainerObject_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TransparencyDefaultContainerObject < Lutaml::Model::Serializable
      xml do
        root "TransparencyDefaultContainerObject"
      end
    end
  end
end
