# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<PageItemDefault>`. Every
    # attribute from `PageItemDefault_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (36 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class PageItemDefault < Lutaml::Model::Serializable
      attribute :top_left_corner_option, :string
      attribute :top_right_corner_option, :string
      attribute :bottom_left_corner_option, :string
      attribute :bottom_right_corner_option, :string
      attribute :top_left_corner_radius, :float
      attribute :top_right_corner_radius, :float
      attribute :bottom_left_corner_radius, :float
      attribute :bottom_right_corner_radius, :float
      attribute :applied_graphic_object_style, :string
      attribute :applied_text_object_style, :string
      attribute :applied_grid_object_style, :string
      attribute :corner_option, :string
      attribute :corner_radius, :float
      attribute :fill_color, :string
      attribute :fill_tint, :float
      attribute :stroke_weight, :float
      attribute :miter_limit, :float
      attribute :end_cap, :string
      attribute :end_join, :string
      attribute :stroke_type, :string
      attribute :left_line_end, :string
      attribute :right_line_end, :string
      attribute :stroke_color, :string
      attribute :stroke_tint, :float
      attribute :gradient_fill_angle, :float
      attribute :gradient_stroke_angle, :float
      attribute :overprint_stroke, :boolean
      attribute :overprint_fill, :boolean
      attribute :gap_color, :string
      attribute :gap_tint, :float
      attribute :overprint_gap, :boolean
      attribute :stroke_alignment, :string
      attribute :nonprinting, :boolean
      attribute :arrow_head_alignment, :string
      attribute :left_arrow_head_scale, :float
      attribute :right_arrow_head_scale, :float

      xml do
        root "PageItemDefault"
        map_attribute "TopLeftCornerOption", to: :top_left_corner_option
        map_attribute "TopRightCornerOption", to: :top_right_corner_option
        map_attribute "BottomLeftCornerOption", to: :bottom_left_corner_option
        map_attribute "BottomRightCornerOption", to: :bottom_right_corner_option
        map_attribute "TopLeftCornerRadius", to: :top_left_corner_radius
        map_attribute "TopRightCornerRadius", to: :top_right_corner_radius
        map_attribute "BottomLeftCornerRadius", to: :bottom_left_corner_radius
        map_attribute "BottomRightCornerRadius", to: :bottom_right_corner_radius
        map_attribute "AppliedGraphicObjectStyle", to: :applied_graphic_object_style
        map_attribute "AppliedTextObjectStyle", to: :applied_text_object_style
        map_attribute "AppliedGridObjectStyle", to: :applied_grid_object_style
        map_attribute "CornerOption", to: :corner_option
        map_attribute "CornerRadius", to: :corner_radius
        map_attribute "FillColor", to: :fill_color
        map_attribute "FillTint", to: :fill_tint
        map_attribute "StrokeWeight", to: :stroke_weight
        map_attribute "MiterLimit", to: :miter_limit
        map_attribute "EndCap", to: :end_cap
        map_attribute "EndJoin", to: :end_join
        map_attribute "StrokeType", to: :stroke_type
        map_attribute "LeftLineEnd", to: :left_line_end
        map_attribute "RightLineEnd", to: :right_line_end
        map_attribute "StrokeColor", to: :stroke_color
        map_attribute "StrokeTint", to: :stroke_tint
        map_attribute "GradientFillAngle", to: :gradient_fill_angle
        map_attribute "GradientStrokeAngle", to: :gradient_stroke_angle
        map_attribute "OverprintStroke", to: :overprint_stroke
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "GapColor", to: :gap_color
        map_attribute "GapTint", to: :gap_tint
        map_attribute "OverprintGap", to: :overprint_gap
        map_attribute "StrokeAlignment", to: :stroke_alignment
        map_attribute "Nonprinting", to: :nonprinting
        map_attribute "ArrowHeadAlignment", to: :arrow_head_alignment
        map_attribute "LeftArrowHeadScale", to: :left_arrow_head_scale
        map_attribute "RightArrowHeadScale", to: :right_arrow_head_scale
      end
    end
  end
end
