# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<GuidePreference>`. Every
    # attribute from `GuidePreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class GuidePreference < Lutaml::Model::Serializable
      attribute :guides_in_back, :boolean
      attribute :guides_shown, :boolean
      attribute :guides_locked, :boolean
      attribute :guides_snapto, :boolean
      attribute :ruler_guides_view_threshold, :float

      xml do
        root "GuidePreference"
        map_attribute "GuidesInBack", to: :guides_in_back
        map_attribute "GuidesShown", to: :guides_shown
        map_attribute "GuidesLocked", to: :guides_locked
        map_attribute "GuidesSnapto", to: :guides_snapto
        map_attribute "RulerGuidesViewThreshold", to: :ruler_guides_view_threshold
      end
    end
  end
end
