# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<IndexOptions>`. Every
    # attribute from `IndexOptions_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (22 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class IndexOptions < Lutaml::Model::Serializable
      attribute :title, :string
      attribute :title_style, :string
      attribute :replace_existing_index, :boolean
      attribute :include_book_documents, :boolean
      attribute :include_hidden_entries, :boolean
      attribute :index_format, :string
      attribute :include_section_headings, :boolean
      attribute :include_empty_index_sections, :boolean
      attribute :level1_style, :string
      attribute :level2_style, :string
      attribute :level3_style, :string
      attribute :level4_style, :string
      attribute :section_heading_style, :string
      attribute :page_number_style, :string
      attribute :cross_reference_style, :string
      attribute :cross_reference_topic_style, :string
      attribute :following_topic_separator, :string
      attribute :between_entries_separator, :string
      attribute :page_range_separator, :string
      attribute :between_page_numbers_separator, :string
      attribute :before_cross_reference_separator, :string
      attribute :entry_end_separator, :string

      xml do
        root "IndexOptions"
        map_attribute "Title", to: :title
        map_attribute "TitleStyle", to: :title_style
        map_attribute "ReplaceExistingIndex", to: :replace_existing_index
        map_attribute "IncludeBookDocuments", to: :include_book_documents
        map_attribute "IncludeHiddenEntries", to: :include_hidden_entries
        map_attribute "IndexFormat", to: :index_format
        map_attribute "IncludeSectionHeadings", to: :include_section_headings
        map_attribute "IncludeEmptyIndexSections", to: :include_empty_index_sections
        map_attribute "Level1Style", to: :level1_style
        map_attribute "Level2Style", to: :level2_style
        map_attribute "Level3Style", to: :level3_style
        map_attribute "Level4Style", to: :level4_style
        map_attribute "SectionHeadingStyle", to: :section_heading_style
        map_attribute "PageNumberStyle", to: :page_number_style
        map_attribute "CrossReferenceStyle", to: :cross_reference_style
        map_attribute "CrossReferenceTopicStyle", to: :cross_reference_topic_style
        map_attribute "FollowingTopicSeparator", to: :following_topic_separator
        map_attribute "BetweenEntriesSeparator", to: :between_entries_separator
        map_attribute "PageRangeSeparator", to: :page_range_separator
        map_attribute "BetweenPageNumbersSeparator", to: :between_page_numbers_separator
        map_attribute "BeforeCrossReferenceSeparator", to: :before_cross_reference_separator
        map_attribute "EntryEndSeparator", to: :entry_end_separator
      end
    end
  end
end
