# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DictionaryPreference>`. Every
    # attribute from `DictionaryPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (3 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DictionaryPreference < Lutaml::Model::Serializable
      attribute :composition, :string
      attribute :merge_user_dictionary, :boolean
      attribute :recompose_when_changed, :boolean

      xml do
        root "DictionaryPreference"
        map_attribute "Composition", to: :composition
        map_attribute "MergeUserDictionary", to: :merge_user_dictionary
        map_attribute "RecomposeWhenChanged", to: :recompose_when_changed
      end
    end
  end
end
