# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<MojikumiUiPreference>`. Every
    # attribute from `MojikumiUiPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class MojikumiUiPreference < Lutaml::Model::Serializable
      attribute :mojikumi_ui_settings, :integer

      xml do
        root "MojikumiUiPreference"
        map_attribute "MojikumiUiSettings", to: :mojikumi_ui_settings
      end
    end
  end
end
