# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<MarginPreference>`. Every
    # attribute from `MarginPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (8 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class MarginPreference < Lutaml::Model::Serializable
      attribute :column_count, :integer
      attribute :column_gutter, :float
      attribute :top, :float
      attribute :bottom, :float
      attribute :left, :float
      attribute :right, :float
      attribute :column_direction, :string
      attribute :columns_positions, :string

      xml do
        root "MarginPreference"
        map_attribute "ColumnCount", to: :column_count
        map_attribute "ColumnGutter", to: :column_gutter
        map_attribute "Top", to: :top
        map_attribute "Bottom", to: :bottom
        map_attribute "Left", to: :left
        map_attribute "Right", to: :right
        map_attribute "ColumnDirection", to: :column_direction
        map_attribute "ColumnsPositions", to: :columns_positions
      end
    end
  end
end
