# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ChapterNumberPreference>`. Every
    # attribute from `ChapterNumberPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ChapterNumberPreference < Lutaml::Model::Serializable
      attribute :chapter_number, :integer
      attribute :chapter_number_source, :string

      xml do
        root "ChapterNumberPreference"
        map_attribute "ChapterNumber", to: :chapter_number
        map_attribute "ChapterNumberSource", to: :chapter_number_source
      end
    end
  end
end
