# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<FootnoteOption>`. Every
    # attribute from `FootnoteOption_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (31 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class FootnoteOption < Lutaml::Model::Serializable
      attribute :enable_straddling, :boolean
      attribute :start_at, :integer
      attribute :prefix, :string
      attribute :suffix, :string
      attribute :footnote_text_style, :string
      attribute :footnote_marker_style, :string
      attribute :separator_text, :string
      attribute :space_between, :float
      attribute :spacer, :float
      attribute :footnote_first_baseline_offset, :string
      attribute :footnote_minimum_first_baseline_offset, :float
      attribute :eos_placement, :boolean
      attribute :no_splitting, :boolean
      attribute :rule_on, :boolean
      attribute :rule_line_weight, :float
      attribute :rule_tint, :float
      attribute :rule_gap_tint, :float
      attribute :rule_gap_overprint, :boolean
      attribute :rule_overprint, :boolean
      attribute :rule_left_indent, :float
      attribute :rule_width, :float
      attribute :rule_offset, :float
      attribute :continuing_rule_on, :boolean
      attribute :continuing_rule_line_weight, :float
      attribute :continuing_rule_tint, :float
      attribute :continuing_rule_gap_tint, :float
      attribute :continuing_rule_overprint, :boolean
      attribute :continuing_rule_gap_overprint, :boolean
      attribute :continuing_rule_left_indent, :float
      attribute :continuing_rule_width, :float
      attribute :continuing_rule_offset, :float

      xml do
        root "FootnoteOption"
        map_attribute "EnableStraddling", to: :enable_straddling
        map_attribute "StartAt", to: :start_at
        map_attribute "Prefix", to: :prefix
        map_attribute "Suffix", to: :suffix
        map_attribute "FootnoteTextStyle", to: :footnote_text_style
        map_attribute "FootnoteMarkerStyle", to: :footnote_marker_style
        map_attribute "SeparatorText", to: :separator_text
        map_attribute "SpaceBetween", to: :space_between
        map_attribute "Spacer", to: :spacer
        map_attribute "FootnoteFirstBaselineOffset", to: :footnote_first_baseline_offset
        map_attribute "FootnoteMinimumFirstBaselineOffset", to: :footnote_minimum_first_baseline_offset
        map_attribute "EosPlacement", to: :eos_placement
        map_attribute "NoSplitting", to: :no_splitting
        map_attribute "RuleOn", to: :rule_on
        map_attribute "RuleLineWeight", to: :rule_line_weight
        map_attribute "RuleTint", to: :rule_tint
        map_attribute "RuleGapTint", to: :rule_gap_tint
        map_attribute "RuleGapOverprint", to: :rule_gap_overprint
        map_attribute "RuleOverprint", to: :rule_overprint
        map_attribute "RuleLeftIndent", to: :rule_left_indent
        map_attribute "RuleWidth", to: :rule_width
        map_attribute "RuleOffset", to: :rule_offset
        map_attribute "ContinuingRuleOn", to: :continuing_rule_on
        map_attribute "ContinuingRuleLineWeight", to: :continuing_rule_line_weight
        map_attribute "ContinuingRuleTint", to: :continuing_rule_tint
        map_attribute "ContinuingRuleGapTint", to: :continuing_rule_gap_tint
        map_attribute "ContinuingRuleOverprint", to: :continuing_rule_overprint
        map_attribute "ContinuingRuleGapOverprint", to: :continuing_rule_gap_overprint
        map_attribute "ContinuingRuleLeftIndent", to: :continuing_rule_left_indent
        map_attribute "ContinuingRuleWidth", to: :continuing_rule_width
        map_attribute "ContinuingRuleOffset", to: :continuing_rule_offset
      end
    end
  end
end
