# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<LayoutAdjustmentPreference>`. Every
    # attribute from `LayoutAdjustmentPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (6 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class LayoutAdjustmentPreference < Lutaml::Model::Serializable
      attribute :enable_layout_adjustment, :boolean
      attribute :snap_zone, :float
      attribute :allow_graphics_to_resize, :boolean
      attribute :allow_ruler_guides_to_move, :boolean
      attribute :ignore_ruler_guide_alignments, :boolean
      attribute :ignore_object_or_layer_locks, :boolean

      xml do
        root "LayoutAdjustmentPreference"
        map_attribute "EnableLayoutAdjustment", to: :enable_layout_adjustment
        map_attribute "SnapZone", to: :snap_zone
        map_attribute "AllowGraphicsToResize", to: :allow_graphics_to_resize
        map_attribute "AllowRulerGuidesToMove", to: :allow_ruler_guides_to_move
        map_attribute "IgnoreRulerGuideAlignments", to: :ignore_ruler_guide_alignments
        map_attribute "IgnoreObjectOrLayerLocks", to: :ignore_object_or_layer_locks
      end
    end
  end
end
