# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<AnchoredObjectDefault>`. Every
    # attribute from `AnchoredObjectDefault_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class AnchoredObjectDefault < Lutaml::Model::Serializable
      attribute :anchor_content, :string
      attribute :initial_anchor_height, :float
      attribute :initial_anchor_width, :float
      attribute :anchored_paragraph_style, :string
      attribute :anchored_object_style, :string

      xml do
        root "AnchoredObjectDefault"
        map_attribute "AnchorContent", to: :anchor_content
        map_attribute "InitialAnchorHeight", to: :initial_anchor_height
        map_attribute "InitialAnchorWidth", to: :initial_anchor_width
        map_attribute "AnchoredParagraphStyle", to: :anchored_paragraph_style
        map_attribute "AnchoredObjectStyle", to: :anchored_object_style
      end
    end
  end
end
