# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<HTMLExportPreference>`. Every
    # attribute from `HTMLExportPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (39 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class HTMLExportPreference < Lutaml::Model::Serializable
      attribute :export_selection, :boolean
      attribute :export_order, :string
      attribute :bullet_export_option, :string
      attribute :numbered_list_export_option, :string
      attribute :view_document_after_export, :boolean
      attribute :image_export_option, :string
      attribute :image_export_resolution, :string
      attribute :custom_image_size_option, :string
      attribute :preserve_layout_appearence, :boolean
      attribute :image_alignment, :string
      attribute :image_space_before, :float
      attribute :image_space_after, :float
      attribute :image_conversion, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string
      attribute :level, :integer
      attribute :ignore_object_conversion_settings, :boolean
      attribute :server_path, :string
      attribute :image_extension, :string
      attribute :preserve_local_override, :boolean
      attribute :left_margin, :float
      attribute :right_margin, :float
      attribute :top_margin, :float
      attribute :bottom_margin, :float
      attribute :margin_unit, :string
      attribute :space_unit, :string
      attribute :external_css_path, :string
      attribute :link_to_javascript, :boolean
      attribute :javascript_url, :string
      attribute :include_css_definition, :boolean
      attribute :css_export_option, :string
      attribute :apply_image_alignment_to_anchored_object_settings, :boolean
      attribute :external_style_sheets, :string
      attribute :javascripts, :string
      attribute :generate_cascade_style_sheet, :boolean
      attribute :include_classes_in_html, :boolean
      attribute :use_svg_as, :string

      xml do
        root "HTMLExportPreference"
        map_attribute "ExportSelection", to: :export_selection
        map_attribute "ExportOrder", to: :export_order
        map_attribute "BulletExportOption", to: :bullet_export_option
        map_attribute "NumberedListExportOption", to: :numbered_list_export_option
        map_attribute "ViewDocumentAfterExport", to: :view_document_after_export
        map_attribute "ImageExportOption", to: :image_export_option
        map_attribute "ImageExportResolution", to: :image_export_resolution
        map_attribute "CustomImageSizeOption", to: :custom_image_size_option
        map_attribute "PreserveLayoutAppearence", to: :preserve_layout_appearence
        map_attribute "ImageAlignment", to: :image_alignment
        map_attribute "ImageSpaceBefore", to: :image_space_before
        map_attribute "ImageSpaceAfter", to: :image_space_after
        map_attribute "ImageConversion", to: :image_conversion
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
        map_attribute "Level", to: :level
        map_attribute "IgnoreObjectConversionSettings", to: :ignore_object_conversion_settings
        map_attribute "ServerPath", to: :server_path
        map_attribute "ImageExtension", to: :image_extension
        map_attribute "PreserveLocalOverride", to: :preserve_local_override
        map_attribute "LeftMargin", to: :left_margin
        map_attribute "RightMargin", to: :right_margin
        map_attribute "TopMargin", to: :top_margin
        map_attribute "BottomMargin", to: :bottom_margin
        map_attribute "MarginUnit", to: :margin_unit
        map_attribute "SpaceUnit", to: :space_unit
        map_attribute "ExternalCSSPath", to: :external_css_path
        map_attribute "LinkToJavascript", to: :link_to_javascript
        map_attribute "JavascriptURL", to: :javascript_url
        map_attribute "IncludeCSSDefinition", to: :include_css_definition
        map_attribute "CSSExportOption", to: :css_export_option
        map_attribute "ApplyImageAlignmentToAnchoredObjectSettings", to: :apply_image_alignment_to_anchored_object_settings
        map_attribute "ExternalStyleSheets", to: :external_style_sheets
        map_attribute "Javascripts", to: :javascripts
        map_attribute "GenerateCascadeStyleSheet", to: :generate_cascade_style_sheet
        map_attribute "IncludeClassesInHTML", to: :include_classes_in_html
        map_attribute "UseSVGAs", to: :use_svg_as
      end
    end
  end
end
