# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DataMerge>`. Every
    # attribute from `DataMerge_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DataMerge < Lutaml::Model::Serializable
      attribute :data_source_file_type, :string
      attribute :data_source_file, :string

      xml do
        root "DataMerge"
        map_attribute "DataSourceFileType", to: :data_source_file_type
        map_attribute "DataSourceFile", to: :data_source_file
      end
    end
  end
end
