# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TinDocumentDataObject>`. Every
    # attribute from `TinDocumentDataObject_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TinDocumentDataObject < Lutaml::Model::Serializable
      xml do
        root "TinDocumentDataObject"
      end
    end
  end
end
