# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DataMergeField>`. Every
    # attribute from `DataMergeField_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DataMergeField < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :field_name, :string

      xml do
        root "DataMergeField"
        map_attribute "Self", to: :self_attr
        map_attribute "FieldName", to: :field_name
      end
    end
  end
end
