# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<IndexHeaderSetting>`. Every
    # attribute from `IndexHeaderSetting_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class IndexHeaderSetting < Lutaml::Model::Serializable
      attribute :header_set_name, :string
      attribute :header_set_language, :integer
      attribute :index_header_set_handler, :integer
      attribute :index_header_set_group_value, :integer
      attribute :index_header_set_group_option_value, :integer

      xml do
        root "IndexHeaderSetting"
        map_attribute "HeaderSetName", to: :header_set_name
        map_attribute "HeaderSetLanguage", to: :header_set_language
        map_attribute "IndexHeaderSetHandler", to: :index_header_set_handler
        map_attribute "IndexHeaderSetGroupValue", to: :index_header_set_group_value
        map_attribute "IndexHeaderSetGroupOptionValue", to: :index_header_set_group_option_value
      end
    end
  end
end
