# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<ViewPreference>`. Every
    # attribute from `ViewPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (17 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class ViewPreference < Lutaml::Model::Serializable
      attribute :show_notes, :boolean
      attribute :guide_snapto_zone, :integer
      attribute :cursor_key_increment, :float
      attribute :horizontal_measurement_units, :string
      attribute :vertical_measurement_units, :string
      attribute :ruler_origin, :string
      attribute :show_rulers, :boolean
      attribute :show_frame_edges, :boolean
      attribute :line_measurement_units, :string
      attribute :typographic_measurement_units, :string
      attribute :text_size_measurement_units, :string
      attribute :print_dialog_measurement_units, :string
      attribute :stroke_measurement_units, :string
      attribute :show_text_threads, :boolean
      attribute :points_per_inch, :float
      attribute :horizontal_custom_points, :float
      attribute :vertical_custom_points, :float

      xml do
        root "ViewPreference"
        map_attribute "ShowNotes", to: :show_notes
        map_attribute "GuideSnaptoZone", to: :guide_snapto_zone
        map_attribute "CursorKeyIncrement", to: :cursor_key_increment
        map_attribute "HorizontalMeasurementUnits", to: :horizontal_measurement_units
        map_attribute "VerticalMeasurementUnits", to: :vertical_measurement_units
        map_attribute "RulerOrigin", to: :ruler_origin
        map_attribute "ShowRulers", to: :show_rulers
        map_attribute "ShowFrameEdges", to: :show_frame_edges
        map_attribute "LineMeasurementUnits", to: :line_measurement_units
        map_attribute "TypographicMeasurementUnits", to: :typographic_measurement_units
        map_attribute "TextSizeMeasurementUnits", to: :text_size_measurement_units
        map_attribute "PrintDialogMeasurementUnits", to: :print_dialog_measurement_units
        map_attribute "StrokeMeasurementUnits", to: :stroke_measurement_units
        map_attribute "ShowTextThreads", to: :show_text_threads
        map_attribute "PointsPerInch", to: :points_per_inch
        map_attribute "HorizontalCustomPoints", to: :horizontal_custom_points
        map_attribute "VerticalCustomPoints", to: :vertical_custom_points
      end
    end
  end
end
