# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLImportPreference>`. Every
    # attribute from `XMLImportPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (10 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XMLImportPreference < Lutaml::Model::Serializable
      attribute :import_to_selected, :boolean
      attribute :import_style, :string
      attribute :create_link_to_xml, :boolean
      attribute :repeat_text_elements, :boolean
      attribute :ignore_unmatched_incoming, :boolean
      attribute :import_text_into_tables, :boolean
      attribute :ignore_whitespace, :boolean
      attribute :remove_unmatched_existing, :boolean
      attribute :allow_transform, :boolean
      attribute :import_cals_tables, :boolean

      xml do
        root "XMLImportPreference"
        map_attribute "ImportToSelected", to: :import_to_selected
        map_attribute "ImportStyle", to: :import_style
        map_attribute "CreateLinkToXML", to: :create_link_to_xml
        map_attribute "RepeatTextElements", to: :repeat_text_elements
        map_attribute "IgnoreUnmatchedIncoming", to: :ignore_unmatched_incoming
        map_attribute "ImportTextIntoTables", to: :import_text_into_tables
        map_attribute "IgnoreWhitespace", to: :ignore_whitespace
        map_attribute "RemoveUnmatchedExisting", to: :remove_unmatched_existing
        map_attribute "AllowTransform", to: :allow_transform
        map_attribute "ImportCALSTables", to: :import_cals_tables
      end
    end
  end
end
