# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<PrintBookletPrintPreference>`. Every
    # attribute from `PrintBookletPrintPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (86 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class PrintBookletPrintPreference < Lutaml::Model::Serializable
      attribute :printer_list, :string
      attribute :ppd_list, :string
      attribute :paper_size_list, :string
      attribute :screening_list, :string
      attribute :print_file, :string
      attribute :copies, :integer
      attribute :collating, :boolean
      attribute :reverse_order, :boolean
      attribute :print_nonprinting, :boolean
      attribute :print_blank_pages, :boolean
      attribute :print_guides_grids, :boolean
      attribute :paper_offset, :float
      attribute :paper_gap, :float
      attribute :paper_transverse, :boolean
      attribute :print_page_orientation, :string
      attribute :page_position, :string
      attribute :scale_mode, :string
      attribute :scale_width, :float
      attribute :scale_height, :float
      attribute :scale_proportional, :boolean
      attribute :print_layers, :string
      attribute :all_printer_marks, :boolean
      attribute :crop_marks, :boolean
      attribute :bleed_marks, :boolean
      attribute :registration_marks, :boolean
      attribute :color_bars, :boolean
      attribute :page_information_marks, :boolean
      attribute :mark_line_weight, :string
      attribute :mark_offset, :float
      attribute :use_document_bleed_to_print, :boolean
      attribute :bleed_top, :float
      attribute :bleed_bottom, :float
      attribute :bleed_inside, :float
      attribute :bleed_outside, :float
      attribute :bleed_chain, :boolean
      attribute :color_output, :string
      attribute :text_as_black, :boolean
      attribute :trapping, :string
      attribute :flip, :string
      attribute :negative, :boolean
      attribute :composite_angle, :float
      attribute :composite_frequency, :float
      attribute :simulate_overprint, :boolean
      attribute :print_cyan, :boolean
      attribute :cyan_angle, :float
      attribute :cyan_frequency, :float
      attribute :print_magenta, :boolean
      attribute :magenta_angle, :float
      attribute :magenta_frequency, :float
      attribute :print_yellow, :boolean
      attribute :yellow_angle, :float
      attribute :yellow_frequency, :float
      attribute :print_black, :boolean
      attribute :black_angle, :float
      attribute :black_frequency, :float
      attribute :send_image_data, :string
      attribute :font_downloading, :string
      attribute :download_ppd_fonts, :boolean
      attribute :post_script_level, :string
      attribute :data_format, :string
      attribute :source_space, :string
      attribute :intent, :string
      attribute :preserve_color_numbers, :boolean
      attribute :opi_image_replacement, :boolean
      attribute :omit_eps, :boolean
      attribute :omit_pdf, :boolean
      attribute :omit_bitmaps, :boolean
      attribute :flattener_preset_name, :string
      attribute :ignore_spread_overrides, :boolean
      attribute :bitmap_printing, :boolean
      attribute :bitmap_resolution, :integer
      attribute :device_type, :integer
      attribute :print_to, :integer
      attribute :ppd_file, :string
      attribute :print_to_disk, :boolean
      attribute :print_record, :string
      attribute :print_resolution, :float
      attribute :paper_size_selector, :string
      attribute :paper_height_range, :string
      attribute :paper_width_range, :string
      attribute :paper_offset_range, :string
      attribute :separation_screening, :string
      attribute :composite_screening, :string
      attribute :spot_angle, :float
      attribute :spot_frequency, :float
      attribute :pdf_passthrough, :boolean

      xml do
        root "PrintBookletPrintPreference"
        map_attribute "PrinterList", to: :printer_list
        map_attribute "PPDList", to: :ppd_list
        map_attribute "PaperSizeList", to: :paper_size_list
        map_attribute "ScreeningList", to: :screening_list
        map_attribute "PrintFile", to: :print_file
        map_attribute "Copies", to: :copies
        map_attribute "Collating", to: :collating
        map_attribute "ReverseOrder", to: :reverse_order
        map_attribute "PrintNonprinting", to: :print_nonprinting
        map_attribute "PrintBlankPages", to: :print_blank_pages
        map_attribute "PrintGuidesGrids", to: :print_guides_grids
        map_attribute "PaperOffset", to: :paper_offset
        map_attribute "PaperGap", to: :paper_gap
        map_attribute "PaperTransverse", to: :paper_transverse
        map_attribute "PrintPageOrientation", to: :print_page_orientation
        map_attribute "PagePosition", to: :page_position
        map_attribute "ScaleMode", to: :scale_mode
        map_attribute "ScaleWidth", to: :scale_width
        map_attribute "ScaleHeight", to: :scale_height
        map_attribute "ScaleProportional", to: :scale_proportional
        map_attribute "PrintLayers", to: :print_layers
        map_attribute "AllPrinterMarks", to: :all_printer_marks
        map_attribute "CropMarks", to: :crop_marks
        map_attribute "BleedMarks", to: :bleed_marks
        map_attribute "RegistrationMarks", to: :registration_marks
        map_attribute "ColorBars", to: :color_bars
        map_attribute "PageInformationMarks", to: :page_information_marks
        map_attribute "MarkLineWeight", to: :mark_line_weight
        map_attribute "MarkOffset", to: :mark_offset
        map_attribute "UseDocumentBleedToPrint", to: :use_document_bleed_to_print
        map_attribute "BleedTop", to: :bleed_top
        map_attribute "BleedBottom", to: :bleed_bottom
        map_attribute "BleedInside", to: :bleed_inside
        map_attribute "BleedOutside", to: :bleed_outside
        map_attribute "BleedChain", to: :bleed_chain
        map_attribute "ColorOutput", to: :color_output
        map_attribute "TextAsBlack", to: :text_as_black
        map_attribute "Trapping", to: :trapping
        map_attribute "Flip", to: :flip
        map_attribute "Negative", to: :negative
        map_attribute "CompositeAngle", to: :composite_angle
        map_attribute "CompositeFrequency", to: :composite_frequency
        map_attribute "SimulateOverprint", to: :simulate_overprint
        map_attribute "PrintCyan", to: :print_cyan
        map_attribute "CyanAngle", to: :cyan_angle
        map_attribute "CyanFrequency", to: :cyan_frequency
        map_attribute "PrintMagenta", to: :print_magenta
        map_attribute "MagentaAngle", to: :magenta_angle
        map_attribute "MagentaFrequency", to: :magenta_frequency
        map_attribute "PrintYellow", to: :print_yellow
        map_attribute "YellowAngle", to: :yellow_angle
        map_attribute "YellowFrequency", to: :yellow_frequency
        map_attribute "PrintBlack", to: :print_black
        map_attribute "BlackAngle", to: :black_angle
        map_attribute "BlackFrequency", to: :black_frequency
        map_attribute "SendImageData", to: :send_image_data
        map_attribute "FontDownloading", to: :font_downloading
        map_attribute "DownloadPPDFonts", to: :download_ppd_fonts
        map_attribute "PostScriptLevel", to: :post_script_level
        map_attribute "DataFormat", to: :data_format
        map_attribute "SourceSpace", to: :source_space
        map_attribute "Intent", to: :intent
        map_attribute "PreserveColorNumbers", to: :preserve_color_numbers
        map_attribute "OPIImageReplacement", to: :opi_image_replacement
        map_attribute "OmitEPS", to: :omit_eps
        map_attribute "OmitPDF", to: :omit_pdf
        map_attribute "OmitBitmaps", to: :omit_bitmaps
        map_attribute "FlattenerPresetName", to: :flattener_preset_name
        map_attribute "IgnoreSpreadOverrides", to: :ignore_spread_overrides
        map_attribute "BitmapPrinting", to: :bitmap_printing
        map_attribute "BitmapResolution", to: :bitmap_resolution
        map_attribute "DeviceType", to: :device_type
        map_attribute "PrintTo", to: :print_to
        map_attribute "PPDFile", to: :ppd_file
        map_attribute "PrintToDisk", to: :print_to_disk
        map_attribute "PrintRecord", to: :print_record
        map_attribute "PrintResolution", to: :print_resolution
        map_attribute "PaperSizeSelector", to: :paper_size_selector
        map_attribute "PaperHeightRange", to: :paper_height_range
        map_attribute "PaperWidthRange", to: :paper_width_range
        map_attribute "PaperOffsetRange", to: :paper_offset_range
        map_attribute "SeparationScreening", to: :separation_screening
        map_attribute "CompositeScreening", to: :composite_screening
        map_attribute "SpotAngle", to: :spot_angle
        map_attribute "SpotFrequency", to: :spot_frequency
        map_attribute "PDFPassthrough", to: :pdf_passthrough
      end
    end
  end
end
