# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<LayoutGridDataInformation>`. Every
    # attribute from `LayoutGridDataInformation_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (6 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class LayoutGridDataInformation < Lutaml::Model::Serializable
      attribute :font_style, :string
      attribute :point_size, :float
      attribute :character_aki, :float
      attribute :line_aki, :float
      attribute :horizontal_scale, :float
      attribute :vertical_scale, :float

      xml do
        root "LayoutGridDataInformation"
        map_attribute "FontStyle", to: :font_style
        map_attribute "PointSize", to: :point_size
        map_attribute "CharacterAki", to: :character_aki
        map_attribute "LineAki", to: :line_aki
        map_attribute "HorizontalScale", to: :horizontal_scale
        map_attribute "VerticalScale", to: :vertical_scale
      end
    end
  end
end
