# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLExportPreference>`. Every
    # attribute from `XMLExportPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (16 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XMLExportPreference < Lutaml::Model::Serializable
      attribute :view_after_export, :boolean
      attribute :export_from_selected, :boolean
      attribute :file_encoding, :string
      attribute :ruby, :boolean
      attribute :exclude_dtd, :boolean
      attribute :copy_original_images, :boolean
      attribute :copy_optimized_images, :boolean
      attribute :copy_formatted_images, :boolean
      attribute :image_conversion, :string
      attribute :gif_options_palette, :string
      attribute :gif_options_interlaced, :boolean
      attribute :jpeg_options_quality, :string
      attribute :jpeg_options_format, :string
      attribute :allow_transform, :boolean
      attribute :character_references, :boolean
      attribute :export_untagged_tables_format, :string

      xml do
        root "XMLExportPreference"
        map_attribute "ViewAfterExport", to: :view_after_export
        map_attribute "ExportFromSelected", to: :export_from_selected
        map_attribute "FileEncoding", to: :file_encoding
        map_attribute "Ruby", to: :ruby
        map_attribute "ExcludeDtd", to: :exclude_dtd
        map_attribute "CopyOriginalImages", to: :copy_original_images
        map_attribute "CopyOptimizedImages", to: :copy_optimized_images
        map_attribute "CopyFormattedImages", to: :copy_formatted_images
        map_attribute "ImageConversion", to: :image_conversion
        map_attribute "GIFOptionsPalette", to: :gif_options_palette
        map_attribute "GIFOptionsInterlaced", to: :gif_options_interlaced
        map_attribute "JPEGOptionsQuality", to: :jpeg_options_quality
        map_attribute "JPEGOptionsFormat", to: :jpeg_options_format
        map_attribute "AllowTransform", to: :allow_transform
        map_attribute "CharacterReferences", to: :character_references
        map_attribute "ExportUntaggedTablesFormat", to: :export_untagged_tables_format
      end
    end
  end
end
