# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DataMergeOption>`. Every
    # attribute from `DataMergeOption_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (6 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DataMergeOption < Lutaml::Model::Serializable
      attribute :fitting_option, :string
      attribute :center_image, :boolean
      attribute :link_images, :boolean
      attribute :remove_blank_lines, :boolean
      attribute :create_new_document, :boolean
      attribute :document_size, :integer

      xml do
        root "DataMergeOption"
        map_attribute "FittingOption", to: :fitting_option
        map_attribute "CenterImage", to: :center_image
        map_attribute "LinkImages", to: :link_images
        map_attribute "RemoveBlankLines", to: :remove_blank_lines
        map_attribute "CreateNewDocument", to: :create_new_document
        map_attribute "DocumentSize", to: :document_size
      end
    end
  end
end
