# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<PasteboardPreference>`. Every
    # attribute from `PasteboardPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (3 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class PasteboardPreference < Lutaml::Model::Serializable
      attribute :minimum_space_above_and_below, :float
      attribute :pasteboard_margins, :string
      attribute :match_preview_background_to_theme_color, :boolean

      xml do
        root "PasteboardPreference"
        map_attribute "MinimumSpaceAboveAndBelow", to: :minimum_space_above_and_below
        map_attribute "PasteboardMargins", to: :pasteboard_margins
        map_attribute "MatchPreviewBackgroundToThemeColor", to: :match_preview_background_to_theme_color
      end
    end
  end
end
