# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLPreference>`. Every
    # attribute from `XMLPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XMLPreference < Lutaml::Model::Serializable
      attribute :delete_element_on_content_deletion, :boolean
      attribute :default_story_tag_name, :string
      attribute :default_table_tag_name, :string
      attribute :default_cell_tag_name, :string
      attribute :default_image_tag_name, :string

      xml do
        root "XMLPreference"
        map_attribute "DeleteElementOnContentDeletion", to: :delete_element_on_content_deletion
        map_attribute "DefaultStoryTagName", to: :default_story_tag_name
        map_attribute "DefaultTableTagName", to: :default_table_tag_name
        map_attribute "DefaultCellTagName", to: :default_cell_tag_name
        map_attribute "DefaultImageTagName", to: :default_image_tag_name
      end
    end
  end
end
