# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<DocumentPreference>`. Every
    # attribute from `DocumentPreference_Object` in
    # `reference-docs/schemas/package/Resources/Preferences.rnc` is declared (25 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class DocumentPreference < Lutaml::Model::Serializable
      attribute :page_height, :float
      attribute :page_width, :float
      attribute :pages_per_document, :integer
      attribute :facing_pages, :boolean
      attribute :document_bleed_top_offset, :float
      attribute :document_bleed_bottom_offset, :float
      attribute :document_bleed_inside_or_left_offset, :float
      attribute :document_bleed_outside_or_right_offset, :float
      attribute :document_bleed_uniform_size, :boolean
      attribute :slug_top_offset, :float
      attribute :slug_bottom_offset, :float
      attribute :slug_inside_or_left_offset, :float
      attribute :slug_right_or_outside_offset, :float
      attribute :document_slug_uniform_size, :boolean
      attribute :preserve_layout_when_shuffling, :boolean
      attribute :allow_page_shuffle, :boolean
      attribute :overprint_black, :boolean
      attribute :page_binding, :string
      attribute :column_direction, :string
      attribute :spread_hidden_visibility, :boolean
      attribute :intent, :string
      attribute :create_primary_text_frame, :boolean
      attribute :column_guide_locked, :boolean
      attribute :master_text_frame, :boolean
      attribute :snippet_import_uses_original_location, :boolean

      xml do
        root "DocumentPreference"
        map_attribute "PageHeight", to: :page_height
        map_attribute "PageWidth", to: :page_width
        map_attribute "PagesPerDocument", to: :pages_per_document
        map_attribute "FacingPages", to: :facing_pages
        map_attribute "DocumentBleedTopOffset", to: :document_bleed_top_offset
        map_attribute "DocumentBleedBottomOffset", to: :document_bleed_bottom_offset
        map_attribute "DocumentBleedInsideOrLeftOffset", to: :document_bleed_inside_or_left_offset
        map_attribute "DocumentBleedOutsideOrRightOffset", to: :document_bleed_outside_or_right_offset
        map_attribute "DocumentBleedUniformSize", to: :document_bleed_uniform_size
        map_attribute "SlugTopOffset", to: :slug_top_offset
        map_attribute "SlugBottomOffset", to: :slug_bottom_offset
        map_attribute "SlugInsideOrLeftOffset", to: :slug_inside_or_left_offset
        map_attribute "SlugRightOrOutsideOffset", to: :slug_right_or_outside_offset
        map_attribute "DocumentSlugUniformSize", to: :document_slug_uniform_size
        map_attribute "PreserveLayoutWhenShuffling", to: :preserve_layout_when_shuffling
        map_attribute "AllowPageShuffle", to: :allow_page_shuffle
        map_attribute "OverprintBlack", to: :overprint_black
        map_attribute "PageBinding", to: :page_binding
        map_attribute "ColumnDirection", to: :column_direction
        map_attribute "SpreadHiddenVisibility", to: :spread_hidden_visibility
        map_attribute "Intent", to: :intent
        map_attribute "CreatePrimaryTextFrame", to: :create_primary_text_frame
        map_attribute "ColumnGuideLocked", to: :column_guide_locked
        map_attribute "MasterTextFrame", to: :master_text_frame
        map_attribute "SnippetImportUsesOriginalLocation", to: :snippet_import_uses_original_location
      end
    end
  end
end
