# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<RootObjectStyleGroup>`. Every
    # attribute from `RootObjectStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class RootObjectStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      attribute :object_style, Idml::Elements::ObjectStyle, collection: true

      xml do
        root "RootObjectStyleGroup"
        map_attribute "Self", to: :self_attr
        map_element "ObjectStyle", to: :object_style
      end
    end
  end
end
