# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<RootParagraphStyleGroup>`. Every
    # attribute from `RootParagraphStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class RootParagraphStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      attribute :paragraph_style, Idml::Elements::ParagraphStyle, collection: true

      xml do
        root "RootParagraphStyleGroup"
        map_attribute "Self", to: :self_attr
        map_element "ParagraphStyle", to: :paragraph_style
      end
    end
  end
end
