# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<RootCellStyleGroup>`. Every
    # attribute from `RootCellStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class RootCellStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      attribute :cell_style, Idml::Elements::CellStyle, collection: true

      xml do
        root "RootCellStyleGroup"
        map_attribute "Self", to: :self_attr
        map_element "CellStyle", to: :cell_style
      end
    end
  end
end
