# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<RootTableStyleGroup>`. Every
    # attribute from `RootTableStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class RootTableStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      attribute :table_style, Idml::Elements::TableStyle, collection: true

      xml do
        root "RootTableStyleGroup"
        map_attribute "Self", to: :self_attr
        map_element "TableStyle", to: :table_style
      end
    end
  end
end
