# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<RootCharacterStyleGroup>`. Every
    # attribute from `RootCharacterStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class RootCharacterStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      attribute :character_style, Idml::Elements::CharacterStyle, collection: true

      xml do
        root "RootCharacterStyleGroup"
        map_attribute "Self", to: :self_attr
        map_element "CharacterStyle", to: :character_style
      end
    end
  end
end
