# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<SatinSetting>`. Every
    # attribute from `SatinSetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (8 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class SatinSetting < Lutaml::Model::Serializable
      attribute :applied, :boolean
      attribute :effect_color, :string
      attribute :blend_mode, :string
      attribute :opacity, :float
      attribute :angle, :float
      attribute :distance, :float
      attribute :size, :float
      attribute :invert_effect, :boolean

      xml do
        root "SatinSetting"
        map_attribute "Applied", to: :applied
        map_attribute "EffectColor", to: :effect_color
        map_attribute "BlendMode", to: :blend_mode
        map_attribute "Opacity", to: :opacity
        map_attribute "Angle", to: :angle
        map_attribute "Distance", to: :distance
        map_attribute "Size", to: :size
        map_attribute "InvertEffect", to: :invert_effect
      end
    end
  end
end
