# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Spread>`. Every
    # attribute from `Spread_Object` in
    # `reference-docs/schemas/package/Spreads/Spread.rnc` is declared (11 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class SpreadObject < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :page_transition_type, :string
      attribute :page_transition_direction, :string
      attribute :page_transition_duration, :string
      attribute :show_master_items, :boolean
      attribute :page_count, :integer
      attribute :binding_location, :integer
      attribute :spread_hidden, :boolean
      attribute :allow_page_shuffle, :boolean
      attribute :item_transform, :string
      attribute :flattener_override, :string

      xml do
        root "Spread"
        map_attribute "Self", to: :self_attr
        map_attribute "PageTransitionType", to: :page_transition_type
        map_attribute "PageTransitionDirection", to: :page_transition_direction
        map_attribute "PageTransitionDuration", to: :page_transition_duration
        map_attribute "ShowMasterItems", to: :show_master_items
        map_attribute "PageCount", to: :page_count
        map_attribute "BindingLocation", to: :binding_location
        map_attribute "SpreadHidden", to: :spread_hidden
        map_attribute "AllowPageShuffle", to: :allow_page_shuffle
        map_attribute "ItemTransform", to: :item_transform
        map_attribute "FlattenerOverride", to: :flattener_override
      end
    end
  end
end
