# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StoryPreference>`. Every
    # attribute from `StoryPreference_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (5 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StoryPreference < Lutaml::Model::Serializable
      attribute :optical_margin_alignment, :boolean
      attribute :optical_margin_size, :float
      attribute :frame_type, :string
      attribute :story_orientation, :string
      attribute :story_direction, :string

      xml do
        root "StoryPreference"
        map_attribute "OpticalMarginAlignment", to: :optical_margin_alignment
        map_attribute "OpticalMarginSize", to: :optical_margin_size
        map_attribute "FrameType", to: :frame_type
        map_attribute "StoryOrientation", to: :story_orientation
        map_attribute "StoryDirection", to: :story_direction
      end
    end
  end
end
