# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StripedStrokeStyle>`. Every
    # attribute from `StripedStrokeStyle_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (3 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StripedStrokeStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :stripe_array, :string
      attribute :name, :string

      xml do
        root "StripedStrokeStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "StripeArray", to: :stripe_array
        map_attribute "Name", to: :name
      end
    end
  end
end
