# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StrokeTransparencySetting>`. Every
    # attribute from `StrokeTransparencySetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StrokeTransparencySetting < Lutaml::Model::Serializable
      xml do
        root "StrokeTransparencySetting"
      end
    end
  end
end
