# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StrokeStyle>`. Every
    # attribute from `StrokeStyle_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StrokeStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string

      xml do
        root "StrokeStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
      end
    end
  end
end
