# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<StyleExportTagMap>`. Every
    # attribute from `StyleExportTagMap_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class StyleExportTagMap < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :export_type, :string
      attribute :export_tag, :string
      attribute :export_class, :string
      attribute :export_attributes, :string
      attribute :split_document, :boolean
      attribute :emit_css, :boolean

      xml do
        root "StyleExportTagMap"
        map_attribute "Self", to: :self_attr
        map_attribute "ExportType", to: :export_type
        map_attribute "ExportTag", to: :export_tag
        map_attribute "ExportClass", to: :export_class
        map_attribute "ExportAttributes", to: :export_attributes
        map_attribute "SplitDocument", to: :split_document
        map_attribute "EmitCss", to: :emit_css
      end
    end
  end
end
