# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<Swatch>`. Every
    # attribute from `Swatch_Object` in
    # `reference-docs/schemas/package/Resources/Graphic.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class Swatch < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :color_editable, :boolean
      attribute :color_removable, :boolean
      attribute :visible, :boolean
      attribute :swatch_creator_id, :integer
      attribute :swatch_color_group_reference, :string

      xml do
        root "Swatch"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "ColorEditable", to: :color_editable
        map_attribute "ColorRemovable", to: :color_removable
        map_attribute "Visible", to: :visible
        map_attribute "SwatchCreatorID", to: :swatch_creator_id
        map_attribute "SwatchColorGroupReference",
                      to: :swatch_color_group_reference
      end
    end
  end
end
