# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TableStyle>`. Every
    # attribute from `TableStyle_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (122 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TableStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :caption_paragraph_count, :integer
      attribute :caption_position, :string
      attribute :header_column_cell_style, :string
      attribute :extended_keyboard_shortcut, :string
      attribute :graphic_left_inset, :float
      attribute :graphic_top_inset, :float
      attribute :graphic_right_inset, :float
      attribute :graphic_bottom_inset, :float
      attribute :clip_content_to_graphic_cell, :boolean
      attribute :text_top_inset, :float
      attribute :text_left_inset, :float
      attribute :text_bottom_inset, :float
      attribute :text_right_inset, :float
      attribute :clip_content_to_text_cell, :boolean
      attribute :name, :string
      attribute :stroke_order, :string
      attribute :top_border_stroke_weight, :float
      attribute :top_border_stroke_type, :string
      attribute :top_border_stroke_color, :string
      attribute :top_border_stroke_tint, :float
      attribute :top_border_stroke_overprint, :boolean
      attribute :top_border_stroke_gap_color, :string
      attribute :top_border_stroke_gap_tint, :float
      attribute :top_border_stroke_gap_overprint, :boolean
      attribute :left_border_stroke_weight, :float
      attribute :left_border_stroke_type, :string
      attribute :left_border_stroke_color, :string
      attribute :left_border_stroke_tint, :float
      attribute :left_border_stroke_overprint, :boolean
      attribute :left_border_stroke_gap_color, :string
      attribute :left_border_stroke_gap_tint, :float
      attribute :left_border_stroke_gap_overprint, :boolean
      attribute :bottom_border_stroke_weight, :float
      attribute :bottom_border_stroke_type, :string
      attribute :bottom_border_stroke_color, :string
      attribute :bottom_border_stroke_tint, :float
      attribute :bottom_border_stroke_overprint, :boolean
      attribute :bottom_border_stroke_gap_color, :string
      attribute :bottom_border_stroke_gap_tint, :float
      attribute :bottom_border_stroke_gap_overprint, :boolean
      attribute :right_border_stroke_weight, :float
      attribute :right_border_stroke_type, :string
      attribute :right_border_stroke_color, :string
      attribute :right_border_stroke_tint, :float
      attribute :right_border_stroke_overprint, :boolean
      attribute :right_border_stroke_gap_color, :string
      attribute :right_border_stroke_gap_tint, :float
      attribute :right_border_stroke_gap_overprint, :boolean
      attribute :space_before, :float
      attribute :space_after, :float
      attribute :skip_first_alternating_stroke_rows, :integer
      attribute :skip_last_alternating_stroke_rows, :integer
      attribute :start_row_stroke_count, :integer
      attribute :start_row_stroke_color, :string
      attribute :start_row_stroke_weight, :float
      attribute :start_row_stroke_type, :string
      attribute :start_row_stroke_tint, :float
      attribute :start_row_stroke_gap_overprint, :boolean
      attribute :start_row_stroke_gap_color, :string
      attribute :start_row_stroke_gap_tint, :float
      attribute :start_row_stroke_overprint, :boolean
      attribute :end_row_stroke_count, :integer
      attribute :end_row_stroke_color, :string
      attribute :end_row_stroke_weight, :float
      attribute :end_row_stroke_type, :string
      attribute :end_row_stroke_tint, :float
      attribute :end_row_stroke_overprint, :boolean
      attribute :end_row_stroke_gap_color, :string
      attribute :end_row_stroke_gap_tint, :float
      attribute :end_row_stroke_gap_overprint, :boolean
      attribute :skip_first_alternating_stroke_columns, :integer
      attribute :skip_last_alternating_stroke_columns, :integer
      attribute :start_column_stroke_count, :integer
      attribute :start_column_stroke_color, :string
      attribute :start_column_stroke_weight, :float
      attribute :start_column_stroke_type, :string
      attribute :start_column_stroke_tint, :float
      attribute :start_column_stroke_overprint, :boolean
      attribute :start_column_stroke_gap_color, :string
      attribute :start_column_stroke_gap_tint, :float
      attribute :start_column_stroke_gap_overprint, :boolean
      attribute :end_column_stroke_count, :integer
      attribute :end_column_stroke_color, :string
      attribute :end_column_stroke_weight, :float
      attribute :end_column_line_style, :string
      attribute :end_column_stroke_tint, :float
      attribute :end_column_stroke_overprint, :boolean
      attribute :end_column_stroke_gap_color, :string
      attribute :end_column_stroke_gap_tint, :float
      attribute :end_column_stroke_gap_overprint, :boolean
      attribute :column_fills_priority, :boolean
      attribute :skip_first_alternating_fill_rows, :integer
      attribute :skip_last_alternating_fill_rows, :integer
      attribute :start_row_fill_color, :string
      attribute :start_row_fill_count, :integer
      attribute :start_row_fill_tint, :float
      attribute :start_row_fill_overprint, :boolean
      attribute :end_row_fill_count, :integer
      attribute :end_row_fill_color, :string
      attribute :end_row_fill_tint, :float
      attribute :end_row_fill_overprint, :boolean
      attribute :skip_first_alternating_fill_columns, :integer
      attribute :skip_last_alternating_fill_columns, :integer
      attribute :start_column_fill_count, :integer
      attribute :start_column_fill_color, :string
      attribute :start_column_fill_tint, :float
      attribute :start_column_fill_overprint, :boolean
      attribute :end_column_fill_count, :integer
      attribute :end_column_fill_color, :string
      attribute :end_column_fill_tint, :float
      attribute :end_column_fill_overprint, :boolean
      attribute :header_region_same_as_body_region, :boolean
      attribute :footer_region_same_as_body_region, :boolean
      attribute :left_column_region_same_as_body_region, :boolean
      attribute :right_column_region_same_as_body_region, :boolean
      attribute :header_region_cell_style, :string
      attribute :footer_region_cell_style, :string
      attribute :left_column_region_cell_style, :string
      attribute :right_column_region_cell_style, :string
      attribute :body_region_cell_style, :string
      attribute :keyboard_shortcut, :string

      xml do
        root "TableStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "CaptionParagraphCount", to: :caption_paragraph_count
        map_attribute "CaptionPosition", to: :caption_position
        map_attribute "HeaderColumnCellStyle", to: :header_column_cell_style
        map_attribute "ExtendedKeyboardShortcut", to: :extended_keyboard_shortcut
        map_attribute "GraphicLeftInset", to: :graphic_left_inset
        map_attribute "GraphicTopInset", to: :graphic_top_inset
        map_attribute "GraphicRightInset", to: :graphic_right_inset
        map_attribute "GraphicBottomInset", to: :graphic_bottom_inset
        map_attribute "ClipContentToGraphicCell", to: :clip_content_to_graphic_cell
        map_attribute "TextTopInset", to: :text_top_inset
        map_attribute "TextLeftInset", to: :text_left_inset
        map_attribute "TextBottomInset", to: :text_bottom_inset
        map_attribute "TextRightInset", to: :text_right_inset
        map_attribute "ClipContentToTextCell", to: :clip_content_to_text_cell
        map_attribute "Name", to: :name
        map_attribute "StrokeOrder", to: :stroke_order
        map_attribute "TopBorderStrokeWeight", to: :top_border_stroke_weight
        map_attribute "TopBorderStrokeType", to: :top_border_stroke_type
        map_attribute "TopBorderStrokeColor", to: :top_border_stroke_color
        map_attribute "TopBorderStrokeTint", to: :top_border_stroke_tint
        map_attribute "TopBorderStrokeOverprint", to: :top_border_stroke_overprint
        map_attribute "TopBorderStrokeGapColor", to: :top_border_stroke_gap_color
        map_attribute "TopBorderStrokeGapTint", to: :top_border_stroke_gap_tint
        map_attribute "TopBorderStrokeGapOverprint", to: :top_border_stroke_gap_overprint
        map_attribute "LeftBorderStrokeWeight", to: :left_border_stroke_weight
        map_attribute "LeftBorderStrokeType", to: :left_border_stroke_type
        map_attribute "LeftBorderStrokeColor", to: :left_border_stroke_color
        map_attribute "LeftBorderStrokeTint", to: :left_border_stroke_tint
        map_attribute "LeftBorderStrokeOverprint", to: :left_border_stroke_overprint
        map_attribute "LeftBorderStrokeGapColor", to: :left_border_stroke_gap_color
        map_attribute "LeftBorderStrokeGapTint", to: :left_border_stroke_gap_tint
        map_attribute "LeftBorderStrokeGapOverprint", to: :left_border_stroke_gap_overprint
        map_attribute "BottomBorderStrokeWeight", to: :bottom_border_stroke_weight
        map_attribute "BottomBorderStrokeType", to: :bottom_border_stroke_type
        map_attribute "BottomBorderStrokeColor", to: :bottom_border_stroke_color
        map_attribute "BottomBorderStrokeTint", to: :bottom_border_stroke_tint
        map_attribute "BottomBorderStrokeOverprint", to: :bottom_border_stroke_overprint
        map_attribute "BottomBorderStrokeGapColor", to: :bottom_border_stroke_gap_color
        map_attribute "BottomBorderStrokeGapTint", to: :bottom_border_stroke_gap_tint
        map_attribute "BottomBorderStrokeGapOverprint", to: :bottom_border_stroke_gap_overprint
        map_attribute "RightBorderStrokeWeight", to: :right_border_stroke_weight
        map_attribute "RightBorderStrokeType", to: :right_border_stroke_type
        map_attribute "RightBorderStrokeColor", to: :right_border_stroke_color
        map_attribute "RightBorderStrokeTint", to: :right_border_stroke_tint
        map_attribute "RightBorderStrokeOverprint", to: :right_border_stroke_overprint
        map_attribute "RightBorderStrokeGapColor", to: :right_border_stroke_gap_color
        map_attribute "RightBorderStrokeGapTint", to: :right_border_stroke_gap_tint
        map_attribute "RightBorderStrokeGapOverprint", to: :right_border_stroke_gap_overprint
        map_attribute "SpaceBefore", to: :space_before
        map_attribute "SpaceAfter", to: :space_after
        map_attribute "SkipFirstAlternatingStrokeRows", to: :skip_first_alternating_stroke_rows
        map_attribute "SkipLastAlternatingStrokeRows", to: :skip_last_alternating_stroke_rows
        map_attribute "StartRowStrokeCount", to: :start_row_stroke_count
        map_attribute "StartRowStrokeColor", to: :start_row_stroke_color
        map_attribute "StartRowStrokeWeight", to: :start_row_stroke_weight
        map_attribute "StartRowStrokeType", to: :start_row_stroke_type
        map_attribute "StartRowStrokeTint", to: :start_row_stroke_tint
        map_attribute "StartRowStrokeGapOverprint", to: :start_row_stroke_gap_overprint
        map_attribute "StartRowStrokeGapColor", to: :start_row_stroke_gap_color
        map_attribute "StartRowStrokeGapTint", to: :start_row_stroke_gap_tint
        map_attribute "StartRowStrokeOverprint", to: :start_row_stroke_overprint
        map_attribute "EndRowStrokeCount", to: :end_row_stroke_count
        map_attribute "EndRowStrokeColor", to: :end_row_stroke_color
        map_attribute "EndRowStrokeWeight", to: :end_row_stroke_weight
        map_attribute "EndRowStrokeType", to: :end_row_stroke_type
        map_attribute "EndRowStrokeTint", to: :end_row_stroke_tint
        map_attribute "EndRowStrokeOverprint", to: :end_row_stroke_overprint
        map_attribute "EndRowStrokeGapColor", to: :end_row_stroke_gap_color
        map_attribute "EndRowStrokeGapTint", to: :end_row_stroke_gap_tint
        map_attribute "EndRowStrokeGapOverprint", to: :end_row_stroke_gap_overprint
        map_attribute "SkipFirstAlternatingStrokeColumns", to: :skip_first_alternating_stroke_columns
        map_attribute "SkipLastAlternatingStrokeColumns", to: :skip_last_alternating_stroke_columns
        map_attribute "StartColumnStrokeCount", to: :start_column_stroke_count
        map_attribute "StartColumnStrokeColor", to: :start_column_stroke_color
        map_attribute "StartColumnStrokeWeight", to: :start_column_stroke_weight
        map_attribute "StartColumnStrokeType", to: :start_column_stroke_type
        map_attribute "StartColumnStrokeTint", to: :start_column_stroke_tint
        map_attribute "StartColumnStrokeOverprint", to: :start_column_stroke_overprint
        map_attribute "StartColumnStrokeGapColor", to: :start_column_stroke_gap_color
        map_attribute "StartColumnStrokeGapTint", to: :start_column_stroke_gap_tint
        map_attribute "StartColumnStrokeGapOverprint", to: :start_column_stroke_gap_overprint
        map_attribute "EndColumnStrokeCount", to: :end_column_stroke_count
        map_attribute "EndColumnStrokeColor", to: :end_column_stroke_color
        map_attribute "EndColumnStrokeWeight", to: :end_column_stroke_weight
        map_attribute "EndColumnLineStyle", to: :end_column_line_style
        map_attribute "EndColumnStrokeTint", to: :end_column_stroke_tint
        map_attribute "EndColumnStrokeOverprint", to: :end_column_stroke_overprint
        map_attribute "EndColumnStrokeGapColor", to: :end_column_stroke_gap_color
        map_attribute "EndColumnStrokeGapTint", to: :end_column_stroke_gap_tint
        map_attribute "EndColumnStrokeGapOverprint", to: :end_column_stroke_gap_overprint
        map_attribute "ColumnFillsPriority", to: :column_fills_priority
        map_attribute "SkipFirstAlternatingFillRows", to: :skip_first_alternating_fill_rows
        map_attribute "SkipLastAlternatingFillRows", to: :skip_last_alternating_fill_rows
        map_attribute "StartRowFillColor", to: :start_row_fill_color
        map_attribute "StartRowFillCount", to: :start_row_fill_count
        map_attribute "StartRowFillTint", to: :start_row_fill_tint
        map_attribute "StartRowFillOverprint", to: :start_row_fill_overprint
        map_attribute "EndRowFillCount", to: :end_row_fill_count
        map_attribute "EndRowFillColor", to: :end_row_fill_color
        map_attribute "EndRowFillTint", to: :end_row_fill_tint
        map_attribute "EndRowFillOverprint", to: :end_row_fill_overprint
        map_attribute "SkipFirstAlternatingFillColumns", to: :skip_first_alternating_fill_columns
        map_attribute "SkipLastAlternatingFillColumns", to: :skip_last_alternating_fill_columns
        map_attribute "StartColumnFillCount", to: :start_column_fill_count
        map_attribute "StartColumnFillColor", to: :start_column_fill_color
        map_attribute "StartColumnFillTint", to: :start_column_fill_tint
        map_attribute "StartColumnFillOverprint", to: :start_column_fill_overprint
        map_attribute "EndColumnFillCount", to: :end_column_fill_count
        map_attribute "EndColumnFillColor", to: :end_column_fill_color
        map_attribute "EndColumnFillTint", to: :end_column_fill_tint
        map_attribute "EndColumnFillOverprint", to: :end_column_fill_overprint
        map_attribute "HeaderRegionSameAsBodyRegion", to: :header_region_same_as_body_region
        map_attribute "FooterRegionSameAsBodyRegion", to: :footer_region_same_as_body_region
        map_attribute "LeftColumnRegionSameAsBodyRegion", to: :left_column_region_same_as_body_region
        map_attribute "RightColumnRegionSameAsBodyRegion", to: :right_column_region_same_as_body_region
        map_attribute "HeaderRegionCellStyle", to: :header_region_cell_style
        map_attribute "FooterRegionCellStyle", to: :footer_region_cell_style
        map_attribute "LeftColumnRegionCellStyle", to: :left_column_region_cell_style
        map_attribute "RightColumnRegionCellStyle", to: :right_column_region_cell_style
        map_attribute "BodyRegionCellStyle", to: :body_region_cell_style
        map_attribute "KeyboardShortcut", to: :keyboard_shortcut
      end
    end
  end
end
