# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TableStyleGroup>`. Every
    # attribute from `TableStyleGroup_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (1 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TableStyleGroup < Lutaml::Model::Serializable
      attribute :self_attr, :string

      xml do
        root "TableStyleGroup"
        map_attribute "Self", to: :self_attr
      end
    end
  end
end
