# frozen_string_literal: true

module Idml
  module Elements
    # `<Table>` — a table page item. Carries geometry, body/header
    # row counts, column layout, and border styling. Declares every
    # attribute of Table_Object in Stories/Story.rnc (171 schema
    # attributes). Two child
    # collections hold the table's content:
    #
    # - `row` — schema-faithful `<Row>` siblings (real IDML).
    # - `cell` — schema-faithful `<Cell>` siblings (real IDML).
    # - `table_row` — legacy nested `<TableRow><TableCell>` form
    #   (synthetic test fixture only; see TODO 84).
    #
    # The renderer auto-detects which layout is present.
    class Table < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :content_type, :string
      attribute :item_transform, :string
      attribute :visible, :boolean
      attribute :fill_color, :string
      attribute :stroke_color, :string
      attribute :stroke_weight, :float

      # Schema-faithful layout attributes (from Table_Object in
      # Stories/Story.rnc). The renderer consults these to compute
      # column widths and to clip body/header/footer regions.
      attribute :header_row_count, :integer
      attribute :footer_row_count, :integer
      attribute :body_row_count, :integer
      attribute :column_count, :integer
      attribute :single_column_width, :float
      attribute :table_direction, :string

      # Outer-border strokes (TopBorderStrokeWeight, etc.). Useful
      # when the renderer draws the table's bounding rectangle.
      attribute :top_border_stroke_weight, :float
      attribute :top_border_stroke_color, :string
      attribute :left_border_stroke_weight, :float
      attribute :left_border_stroke_color, :string
      attribute :bottom_border_stroke_weight, :float
      attribute :bottom_border_stroke_color, :string
      attribute :right_border_stroke_weight, :float
      attribute :right_border_stroke_color, :string

      # The remaining Table_Object attributes (border tints/gaps/
      # overprints, default row/column strokes, alternating fills,
      # cell insets, diagonal lines, caption settings, …) in schema
      # order — generated by `scripts/rnc_to_lutaml.rb` from
      # reference-docs/schemas/package/Stories/Story.rnc.
      attribute :top_border_stroke_type, :string
      attribute :top_border_stroke_tint, :float
      attribute :top_border_stroke_overprint, :boolean
      attribute :top_border_stroke_gap_color, :string
      attribute :top_border_stroke_gap_tint, :float
      attribute :top_border_stroke_gap_overprint, :boolean
      attribute :left_border_stroke_type, :string
      attribute :left_border_stroke_tint, :float
      attribute :left_border_stroke_overprint, :boolean
      attribute :left_border_stroke_gap_color, :string
      attribute :left_border_stroke_gap_tint, :float
      attribute :left_border_stroke_gap_overprint, :boolean
      attribute :bottom_border_stroke_type, :string
      attribute :bottom_border_stroke_tint, :float
      attribute :bottom_border_stroke_overprint, :boolean
      attribute :bottom_border_stroke_gap_color, :string
      attribute :bottom_border_stroke_gap_tint, :float
      attribute :bottom_border_stroke_gap_overprint, :boolean
      attribute :right_border_stroke_type, :string
      attribute :right_border_stroke_tint, :float
      attribute :right_border_stroke_overprint, :boolean
      attribute :right_border_stroke_gap_color, :string
      attribute :right_border_stroke_gap_tint, :float
      attribute :right_border_stroke_gap_overprint, :boolean
      attribute :space_before, :float
      attribute :space_after, :float
      attribute :skip_first_alternating_stroke_rows, :integer
      attribute :skip_last_alternating_stroke_rows, :integer
      attribute :start_row_stroke_count, :integer
      attribute :start_row_stroke_color, :string
      attribute :start_row_stroke_weight, :float
      attribute :start_row_stroke_type, :string
      attribute :start_row_stroke_tint, :float
      attribute :start_row_stroke_gap_overprint, :boolean
      attribute :start_row_stroke_gap_color, :string
      attribute :start_row_stroke_gap_tint, :float
      attribute :start_row_stroke_overprint, :boolean
      attribute :end_row_stroke_count, :integer
      attribute :end_row_stroke_color, :string
      attribute :end_row_stroke_weight, :float
      attribute :end_row_stroke_type, :string
      attribute :end_row_stroke_tint, :float
      attribute :end_row_stroke_overprint, :boolean
      attribute :end_row_stroke_gap_color, :string
      attribute :end_row_stroke_gap_tint, :float
      attribute :end_row_stroke_gap_overprint, :boolean
      attribute :skip_first_alternating_stroke_columns, :integer
      attribute :skip_last_alternating_stroke_columns, :integer
      attribute :start_column_stroke_count, :integer
      attribute :start_column_stroke_color, :string
      attribute :start_column_stroke_weight, :float
      attribute :start_column_stroke_type, :string
      attribute :start_column_stroke_tint, :float
      attribute :start_column_stroke_overprint, :boolean
      attribute :start_column_stroke_gap_color, :string
      attribute :start_column_stroke_gap_tint, :float
      attribute :start_column_stroke_gap_overprint, :boolean
      attribute :end_column_stroke_count, :integer
      attribute :end_column_stroke_color, :string
      attribute :end_column_stroke_weight, :float
      attribute :end_column_line_style, :string
      attribute :end_column_stroke_tint, :float
      attribute :end_column_stroke_overprint, :boolean
      attribute :end_column_stroke_gap_color, :string
      attribute :end_column_stroke_gap_tint, :float
      attribute :end_column_stroke_gap_overprint, :boolean
      attribute :column_fills_priority, :boolean
      attribute :skip_first_alternating_fill_rows, :integer
      attribute :skip_last_alternating_fill_rows, :integer
      attribute :start_row_fill_color, :string
      attribute :start_row_fill_count, :integer
      attribute :start_row_fill_tint, :float
      attribute :start_row_fill_overprint, :boolean
      attribute :end_row_fill_count, :integer
      attribute :end_row_fill_color, :string
      attribute :end_row_fill_tint, :float
      attribute :end_row_fill_overprint, :boolean
      attribute :skip_first_alternating_fill_columns, :integer
      attribute :skip_last_alternating_fill_columns, :integer
      attribute :start_column_fill_count, :integer
      attribute :start_column_fill_color, :string
      attribute :start_column_fill_tint, :float
      attribute :start_column_fill_overprint, :boolean
      attribute :end_column_fill_count, :integer
      attribute :end_column_fill_color, :string
      attribute :end_column_fill_tint, :float
      attribute :end_column_fill_overprint, :boolean
      attribute :break_headers, :string
      attribute :break_footers, :string
      attribute :skip_first_header, :boolean
      attribute :skip_last_footer, :boolean
      attribute :stroke_order, :string
      attribute :default_row_stroke_weight, :float
      attribute :default_row_stroke_type, :string
      attribute :default_row_stroke_color, :string
      attribute :default_row_stroke_tint, :float
      attribute :default_row_stroke_overprint, :boolean
      attribute :default_row_stroke_gap_color, :string
      attribute :default_row_stroke_gap_tint, :float
      attribute :default_row_stroke_gap_overprint, :boolean
      attribute :default_column_stroke_weight, :float
      attribute :default_column_stroke_type, :string
      attribute :default_column_stroke_color, :string
      attribute :default_column_stroke_tint, :float
      attribute :default_column_stroke_overprint, :boolean
      attribute :default_column_stroke_gap_color, :string
      attribute :default_column_stroke_gap_tint, :float
      attribute :default_column_stroke_gap_overprint, :boolean
      attribute :top_inset, :float
      attribute :left_inset, :float
      attribute :bottom_inset, :float
      attribute :right_inset, :float
      attribute :fill_tint, :float
      attribute :overprint_fill, :boolean
      attribute :top_left_diagonal_line, :boolean
      attribute :top_right_diagonal_line, :boolean
      attribute :diagonal_line_in_front, :boolean
      attribute :diagonal_line_stroke_weight, :float
      attribute :diagonal_line_stroke_type, :string
      attribute :diagonal_line_stroke_color, :string
      attribute :diagonal_line_stroke_tint, :float
      attribute :diagonal_line_stroke_overprint, :boolean
      attribute :diagonal_line_stroke_gap_color, :string
      attribute :diagonal_line_stroke_gap_tint, :float
      attribute :diagonal_line_stroke_gap_overprint, :boolean
      attribute :clip_content_to_cell, :boolean
      attribute :first_baseline_offset, :string
      attribute :vertical_justification, :string
      attribute :paragraph_spacing_limit, :float
      attribute :minimum_first_baseline_offset, :float
      attribute :rotation_angle, :float
      attribute :writing_direction, :boolean
      attribute :minimum_height, :float
      attribute :maximum_height, :float
      attribute :keep_with_next_row, :boolean
      attribute :start_row, :string
      attribute :auto_grow, :boolean
      attribute :num_header_columns, :integer
      attribute :header_columns_position, :string
      attribute :caption_paragraph_count, :integer
      attribute :caption_position, :string
      attribute :graphic_left_inset, :float
      attribute :graphic_top_inset, :float
      attribute :graphic_right_inset, :float
      attribute :graphic_bottom_inset, :float
      attribute :clip_content_to_graphic_cell, :boolean
      attribute :text_top_inset, :float
      attribute :text_left_inset, :float
      attribute :text_bottom_inset, :float
      attribute :text_right_inset, :float
      attribute :clip_content_to_text_cell, :boolean
      attribute :single_row_height, :float
      attribute :applied_table_style, :string
      attribute :display_collapsed, :boolean
      attribute :display_order, :string

      attribute :table_row, Idml::Elements::TableRow, collection: true
      attribute :cell, Idml::Elements::Cell, collection: true
      attribute :row, Idml::Elements::Row, collection: true
      attribute :column, Idml::Elements::Column, collection: true
      attribute :properties, Idml::Elements::Properties, collection: true

      xml do
        root "Table"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "ContentType", to: :content_type
        map_attribute "ItemTransform", to: :item_transform
        map_attribute "Visible", to: :visible
        map_attribute "FillColor", to: :fill_color
        map_attribute "StrokeColor", to: :stroke_color
        map_attribute "StrokeWeight", to: :stroke_weight
        map_attribute "HeaderRowCount", to: :header_row_count
        map_attribute "FooterRowCount", to: :footer_row_count
        map_attribute "BodyRowCount", to: :body_row_count
        map_attribute "ColumnCount", to: :column_count
        map_attribute "SingleColumnWidth", to: :single_column_width
        map_attribute "TableDirection", to: :table_direction
        map_attribute "TopBorderStrokeWeight", to: :top_border_stroke_weight
        map_attribute "TopBorderStrokeColor", to: :top_border_stroke_color
        map_attribute "LeftBorderStrokeWeight", to: :left_border_stroke_weight
        map_attribute "LeftBorderStrokeColor", to: :left_border_stroke_color
        map_attribute "BottomBorderStrokeWeight",
                      to: :bottom_border_stroke_weight
        map_attribute "BottomBorderStrokeColor",
                      to: :bottom_border_stroke_color
        map_attribute "RightBorderStrokeWeight", to: :right_border_stroke_weight
        map_attribute "RightBorderStrokeColor", to: :right_border_stroke_color
        map_attribute "TopBorderStrokeType", to: :top_border_stroke_type
        map_attribute "TopBorderStrokeTint", to: :top_border_stroke_tint
        map_attribute "TopBorderStrokeOverprint",
                      to: :top_border_stroke_overprint
        map_attribute "TopBorderStrokeGapColor",
                      to: :top_border_stroke_gap_color
        map_attribute "TopBorderStrokeGapTint", to: :top_border_stroke_gap_tint
        map_attribute "TopBorderStrokeGapOverprint",
                      to: :top_border_stroke_gap_overprint
        map_attribute "LeftBorderStrokeType", to: :left_border_stroke_type
        map_attribute "LeftBorderStrokeTint", to: :left_border_stroke_tint
        map_attribute "LeftBorderStrokeOverprint",
                      to: :left_border_stroke_overprint
        map_attribute "LeftBorderStrokeGapColor",
                      to: :left_border_stroke_gap_color
        map_attribute "LeftBorderStrokeGapTint",
                      to: :left_border_stroke_gap_tint
        map_attribute "LeftBorderStrokeGapOverprint",
                      to: :left_border_stroke_gap_overprint
        map_attribute "BottomBorderStrokeType", to: :bottom_border_stroke_type
        map_attribute "BottomBorderStrokeTint", to: :bottom_border_stroke_tint
        map_attribute "BottomBorderStrokeOverprint",
                      to: :bottom_border_stroke_overprint
        map_attribute "BottomBorderStrokeGapColor",
                      to: :bottom_border_stroke_gap_color
        map_attribute "BottomBorderStrokeGapTint",
                      to: :bottom_border_stroke_gap_tint
        map_attribute "BottomBorderStrokeGapOverprint",
                      to: :bottom_border_stroke_gap_overprint
        map_attribute "RightBorderStrokeType", to: :right_border_stroke_type
        map_attribute "RightBorderStrokeTint", to: :right_border_stroke_tint
        map_attribute "RightBorderStrokeOverprint",
                      to: :right_border_stroke_overprint
        map_attribute "RightBorderStrokeGapColor",
                      to: :right_border_stroke_gap_color
        map_attribute "RightBorderStrokeGapTint",
                      to: :right_border_stroke_gap_tint
        map_attribute "RightBorderStrokeGapOverprint",
                      to: :right_border_stroke_gap_overprint
        map_attribute "SpaceBefore", to: :space_before
        map_attribute "SpaceAfter", to: :space_after
        map_attribute "SkipFirstAlternatingStrokeRows",
                      to: :skip_first_alternating_stroke_rows
        map_attribute "SkipLastAlternatingStrokeRows",
                      to: :skip_last_alternating_stroke_rows
        map_attribute "StartRowStrokeCount", to: :start_row_stroke_count
        map_attribute "StartRowStrokeColor", to: :start_row_stroke_color
        map_attribute "StartRowStrokeWeight", to: :start_row_stroke_weight
        map_attribute "StartRowStrokeType", to: :start_row_stroke_type
        map_attribute "StartRowStrokeTint", to: :start_row_stroke_tint
        map_attribute "StartRowStrokeGapOverprint",
                      to: :start_row_stroke_gap_overprint
        map_attribute "StartRowStrokeGapColor", to: :start_row_stroke_gap_color
        map_attribute "StartRowStrokeGapTint", to: :start_row_stroke_gap_tint
        map_attribute "StartRowStrokeOverprint", to: :start_row_stroke_overprint
        map_attribute "EndRowStrokeCount", to: :end_row_stroke_count
        map_attribute "EndRowStrokeColor", to: :end_row_stroke_color
        map_attribute "EndRowStrokeWeight", to: :end_row_stroke_weight
        map_attribute "EndRowStrokeType", to: :end_row_stroke_type
        map_attribute "EndRowStrokeTint", to: :end_row_stroke_tint
        map_attribute "EndRowStrokeOverprint", to: :end_row_stroke_overprint
        map_attribute "EndRowStrokeGapColor", to: :end_row_stroke_gap_color
        map_attribute "EndRowStrokeGapTint", to: :end_row_stroke_gap_tint
        map_attribute "EndRowStrokeGapOverprint",
                      to: :end_row_stroke_gap_overprint
        map_attribute "SkipFirstAlternatingStrokeColumns",
                      to: :skip_first_alternating_stroke_columns
        map_attribute "SkipLastAlternatingStrokeColumns",
                      to: :skip_last_alternating_stroke_columns
        map_attribute "StartColumnStrokeCount", to: :start_column_stroke_count
        map_attribute "StartColumnStrokeColor", to: :start_column_stroke_color
        map_attribute "StartColumnStrokeWeight", to: :start_column_stroke_weight
        map_attribute "StartColumnStrokeType", to: :start_column_stroke_type
        map_attribute "StartColumnStrokeTint", to: :start_column_stroke_tint
        map_attribute "StartColumnStrokeOverprint",
                      to: :start_column_stroke_overprint
        map_attribute "StartColumnStrokeGapColor",
                      to: :start_column_stroke_gap_color
        map_attribute "StartColumnStrokeGapTint",
                      to: :start_column_stroke_gap_tint
        map_attribute "StartColumnStrokeGapOverprint",
                      to: :start_column_stroke_gap_overprint
        map_attribute "EndColumnStrokeCount", to: :end_column_stroke_count
        map_attribute "EndColumnStrokeColor", to: :end_column_stroke_color
        map_attribute "EndColumnStrokeWeight", to: :end_column_stroke_weight
        map_attribute "EndColumnLineStyle", to: :end_column_line_style
        map_attribute "EndColumnStrokeTint", to: :end_column_stroke_tint
        map_attribute "EndColumnStrokeOverprint",
                      to: :end_column_stroke_overprint
        map_attribute "EndColumnStrokeGapColor",
                      to: :end_column_stroke_gap_color
        map_attribute "EndColumnStrokeGapTint", to: :end_column_stroke_gap_tint
        map_attribute "EndColumnStrokeGapOverprint",
                      to: :end_column_stroke_gap_overprint
        map_attribute "ColumnFillsPriority", to: :column_fills_priority
        map_attribute "SkipFirstAlternatingFillRows",
                      to: :skip_first_alternating_fill_rows
        map_attribute "SkipLastAlternatingFillRows",
                      to: :skip_last_alternating_fill_rows
        map_attribute "StartRowFillColor", to: :start_row_fill_color
        map_attribute "StartRowFillCount", to: :start_row_fill_count
        map_attribute "StartRowFillTint", to: :start_row_fill_tint
        map_attribute "StartRowFillOverprint", to: :start_row_fill_overprint
        map_attribute "EndRowFillCount", to: :end_row_fill_count
        map_attribute "EndRowFillColor", to: :end_row_fill_color
        map_attribute "EndRowFillTint", to: :end_row_fill_tint
        map_attribute "EndRowFillOverprint", to: :end_row_fill_overprint
        map_attribute "SkipFirstAlternatingFillColumns",
                      to: :skip_first_alternating_fill_columns
        map_attribute "SkipLastAlternatingFillColumns",
                      to: :skip_last_alternating_fill_columns
        map_attribute "StartColumnFillCount", to: :start_column_fill_count
        map_attribute "StartColumnFillColor", to: :start_column_fill_color
        map_attribute "StartColumnFillTint", to: :start_column_fill_tint
        map_attribute "StartColumnFillOverprint",
                      to: :start_column_fill_overprint
        map_attribute "EndColumnFillCount", to: :end_column_fill_count
        map_attribute "EndColumnFillColor", to: :end_column_fill_color
        map_attribute "EndColumnFillTint", to: :end_column_fill_tint
        map_attribute "EndColumnFillOverprint", to: :end_column_fill_overprint
        map_attribute "BreakHeaders", to: :break_headers
        map_attribute "BreakFooters", to: :break_footers
        map_attribute "SkipFirstHeader", to: :skip_first_header
        map_attribute "SkipLastFooter", to: :skip_last_footer
        map_attribute "StrokeOrder", to: :stroke_order
        map_attribute "DefaultRowStrokeWeight", to: :default_row_stroke_weight
        map_attribute "DefaultRowStrokeType", to: :default_row_stroke_type
        map_attribute "DefaultRowStrokeColor", to: :default_row_stroke_color
        map_attribute "DefaultRowStrokeTint", to: :default_row_stroke_tint
        map_attribute "DefaultRowStrokeOverprint",
                      to: :default_row_stroke_overprint
        map_attribute "DefaultRowStrokeGapColor",
                      to: :default_row_stroke_gap_color
        map_attribute "DefaultRowStrokeGapTint",
                      to: :default_row_stroke_gap_tint
        map_attribute "DefaultRowStrokeGapOverprint",
                      to: :default_row_stroke_gap_overprint
        map_attribute "DefaultColumnStrokeWeight",
                      to: :default_column_stroke_weight
        map_attribute "DefaultColumnStrokeType", to: :default_column_stroke_type
        map_attribute "DefaultColumnStrokeColor",
                      to: :default_column_stroke_color
        map_attribute "DefaultColumnStrokeTint", to: :default_column_stroke_tint
        map_attribute "DefaultColumnStrokeOverprint",
                      to: :default_column_stroke_overprint
        map_attribute "DefaultColumnStrokeGapColor",
                      to: :default_column_stroke_gap_color
        map_attribute "DefaultColumnStrokeGapTint",
                      to: :default_column_stroke_gap_tint
        map_attribute "DefaultColumnStrokeGapOverprint",
                      to: :default_column_stroke_gap_overprint
        map_attribute "TopInset", to: :top_inset
        map_attribute "LeftInset", to: :left_inset
        map_attribute "BottomInset", to: :bottom_inset
        map_attribute "RightInset", to: :right_inset
        map_attribute "FillTint", to: :fill_tint
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "TopLeftDiagonalLine", to: :top_left_diagonal_line
        map_attribute "TopRightDiagonalLine", to: :top_right_diagonal_line
        map_attribute "DiagonalLineInFront", to: :diagonal_line_in_front
        map_attribute "DiagonalLineStrokeWeight",
                      to: :diagonal_line_stroke_weight
        map_attribute "DiagonalLineStrokeType", to: :diagonal_line_stroke_type
        map_attribute "DiagonalLineStrokeColor", to: :diagonal_line_stroke_color
        map_attribute "DiagonalLineStrokeTint", to: :diagonal_line_stroke_tint
        map_attribute "DiagonalLineStrokeOverprint",
                      to: :diagonal_line_stroke_overprint
        map_attribute "DiagonalLineStrokeGapColor",
                      to: :diagonal_line_stroke_gap_color
        map_attribute "DiagonalLineStrokeGapTint",
                      to: :diagonal_line_stroke_gap_tint
        map_attribute "DiagonalLineStrokeGapOverprint",
                      to: :diagonal_line_stroke_gap_overprint
        map_attribute "ClipContentToCell", to: :clip_content_to_cell
        map_attribute "FirstBaselineOffset", to: :first_baseline_offset
        map_attribute "VerticalJustification", to: :vertical_justification
        map_attribute "ParagraphSpacingLimit", to: :paragraph_spacing_limit
        map_attribute "MinimumFirstBaselineOffset",
                      to: :minimum_first_baseline_offset
        map_attribute "RotationAngle", to: :rotation_angle
        map_attribute "WritingDirection", to: :writing_direction
        map_attribute "MinimumHeight", to: :minimum_height
        map_attribute "MaximumHeight", to: :maximum_height
        map_attribute "KeepWithNextRow", to: :keep_with_next_row
        map_attribute "StartRow", to: :start_row
        map_attribute "AutoGrow", to: :auto_grow
        map_attribute "NumHeaderColumns", to: :num_header_columns
        map_attribute "HeaderColumnsPosition", to: :header_columns_position
        map_attribute "CaptionParagraphCount", to: :caption_paragraph_count
        map_attribute "CaptionPosition", to: :caption_position
        map_attribute "GraphicLeftInset", to: :graphic_left_inset
        map_attribute "GraphicTopInset", to: :graphic_top_inset
        map_attribute "GraphicRightInset", to: :graphic_right_inset
        map_attribute "GraphicBottomInset", to: :graphic_bottom_inset
        map_attribute "ClipContentToGraphicCell",
                      to: :clip_content_to_graphic_cell
        map_attribute "TextTopInset", to: :text_top_inset
        map_attribute "TextLeftInset", to: :text_left_inset
        map_attribute "TextBottomInset", to: :text_bottom_inset
        map_attribute "TextRightInset", to: :text_right_inset
        map_attribute "ClipContentToTextCell", to: :clip_content_to_text_cell
        map_attribute "SingleRowHeight", to: :single_row_height
        map_attribute "AppliedTableStyle", to: :applied_table_style
        map_attribute "DisplayCollapsed", to: :display_collapsed
        map_attribute "DisplayOrder", to: :display_order
        map_element "TableRow", to: :table_row
        map_element "Cell", to: :cell
        map_element "Row", to: :row
        map_element "Column", to: :column
        map_element "Properties", to: :properties
      end

      def geometric_bounds
        @geometric_bounds ||= properties.first&.first_geometry&.bounding_box
      end
    end
  end
end
