# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TextFrameFootnoteOptionsObject>`. Every
    # attribute from `TextFrameFootnoteOptionsObject_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TextFrameFootnoteOptionsObject < Lutaml::Model::Serializable
      attribute :enable_overrides, :boolean
      attribute :span_footnotes_across, :boolean
      attribute :minimum_spacing_option, :float
      attribute :space_between_footnotes, :float

      xml do
        root "TextFrameFootnoteOptionsObject"
        map_attribute "EnableOverrides", to: :enable_overrides
        map_attribute "SpanFootnotesAcross", to: :span_footnotes_across
        map_attribute "MinimumSpacingOption", to: :minimum_spacing_option
        map_attribute "SpaceBetweenFootnotes", to: :space_between_footnotes
      end
    end
  end
end
