# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TextWrapPreference>`. Every
    # attribute from `TextWrapPreference_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TextWrapPreference < Lutaml::Model::Serializable
      attribute :inverse, :boolean
      attribute :apply_to_master_page_only, :boolean
      attribute :text_wrap_side, :string
      attribute :text_wrap_mode, :string
      attribute :properties, Idml::Elements::Properties, collection: true

      xml do
        root "TextWrapPreference"
        map_attribute "Inverse", to: :inverse
        map_attribute "ApplyToMasterPageOnly", to: :apply_to_master_page_only
        map_attribute "TextWrapSide", to: :text_wrap_side
        map_attribute "TextWrapMode", to: :text_wrap_mode
        map_element "Properties", to: :properties
      end
    end
  end
end
