# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TextFramePreference>`. Every
    # attribute from `TextFramePreference_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (33 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`. Insets live in the
    # Properties > InsetSpacing child (spec examples 31/32).
    class TextFramePreference < Lutaml::Model::Serializable
      attribute :properties, Idml::Elements::Properties, collection: true
      attribute :footnotes_enable_overrides, :boolean
      attribute :footnotes_span_across_columns, :boolean
      attribute :footnotes_minimum_spacing, :float
      attribute :footnotes_space_between, :float
      attribute :text_column_count, :integer
      attribute :text_column_gutter, :float
      attribute :text_column_fixed_width, :float
      attribute :use_fixed_column_width, :boolean
      attribute :first_baseline_offset, :string
      attribute :minimum_first_baseline_offset, :float
      attribute :vertical_justification, :string
      attribute :vertical_threshold, :float
      attribute :ignore_wrap, :boolean
      attribute :vertical_balance_columns, :boolean
      attribute :use_flexible_column_width, :boolean
      attribute :text_column_max_width, :float
      attribute :auto_sizing_type, :string
      attribute :auto_sizing_reference_point, :string
      attribute :use_minimum_height_for_auto_sizing, :boolean
      attribute :minimum_height_for_auto_sizing, :float
      attribute :use_minimum_width_for_auto_sizing, :boolean
      attribute :minimum_width_for_auto_sizing, :float
      attribute :use_no_line_breaks_for_auto_sizing, :boolean
      attribute :column_rule_override, :boolean
      attribute :column_rule_offset, :float
      attribute :column_rule_top_inset, :float
      attribute :column_rule_inset_chain_override, :boolean
      attribute :column_rule_bottom_inset, :float
      attribute :column_rule_stroke_width, :float
      attribute :column_rule_stroke_color, :string
      attribute :column_rule_stroke_type, :string
      attribute :column_rule_stroke_tint, :float
      attribute :column_rule_overprint_override, :boolean

      xml do
        root "TextFramePreference"
        map_element "Properties", to: :properties
        map_attribute "FootnotesEnableOverrides", to: :footnotes_enable_overrides
        map_attribute "FootnotesSpanAcrossColumns", to: :footnotes_span_across_columns
        map_attribute "FootnotesMinimumSpacing", to: :footnotes_minimum_spacing
        map_attribute "FootnotesSpaceBetween", to: :footnotes_space_between
        map_attribute "TextColumnCount", to: :text_column_count
        map_attribute "TextColumnGutter", to: :text_column_gutter
        map_attribute "TextColumnFixedWidth", to: :text_column_fixed_width
        map_attribute "UseFixedColumnWidth", to: :use_fixed_column_width
        map_attribute "FirstBaselineOffset", to: :first_baseline_offset
        map_attribute "MinimumFirstBaselineOffset", to: :minimum_first_baseline_offset
        map_attribute "VerticalJustification", to: :vertical_justification
        map_attribute "VerticalThreshold", to: :vertical_threshold
        map_attribute "IgnoreWrap", to: :ignore_wrap
        map_attribute "VerticalBalanceColumns", to: :vertical_balance_columns
        map_attribute "UseFlexibleColumnWidth", to: :use_flexible_column_width
        map_attribute "TextColumnMaxWidth", to: :text_column_max_width
        map_attribute "AutoSizingType", to: :auto_sizing_type
        map_attribute "AutoSizingReferencePoint", to: :auto_sizing_reference_point
        map_attribute "UseMinimumHeightForAutoSizing", to: :use_minimum_height_for_auto_sizing
        map_attribute "MinimumHeightForAutoSizing", to: :minimum_height_for_auto_sizing
        map_attribute "UseMinimumWidthForAutoSizing", to: :use_minimum_width_for_auto_sizing
        map_attribute "MinimumWidthForAutoSizing", to: :minimum_width_for_auto_sizing
        map_attribute "UseNoLineBreaksForAutoSizing", to: :use_no_line_breaks_for_auto_sizing
        map_attribute "ColumnRuleOverride", to: :column_rule_override
        map_attribute "ColumnRuleOffset", to: :column_rule_offset
        map_attribute "ColumnRuleTopInset", to: :column_rule_top_inset
        map_attribute "ColumnRuleInsetChainOverride", to: :column_rule_inset_chain_override
        map_attribute "ColumnRuleBottomInset", to: :column_rule_bottom_inset
        map_attribute "ColumnRuleStrokeWidth", to: :column_rule_stroke_width
        map_attribute "ColumnRuleStrokeColor", to: :column_rule_stroke_color
        map_attribute "ColumnRuleStrokeType", to: :column_rule_stroke_type
        map_attribute "ColumnRuleStrokeTint", to: :column_rule_stroke_tint
        map_attribute "ColumnRuleOverprintOverride", to: :column_rule_overprint_override
      end
    end
  end
end
