# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TOCStyle>`. Every
    # attribute from `TOCStyle_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (12 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TOCStyle < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :title_style, :string
      attribute :title, :string
      attribute :name, :string
      attribute :run_in, :boolean
      attribute :include_hidden, :boolean
      attribute :include_book_documents, :boolean
      attribute :create_bookmarks, :boolean
      attribute :set_story_direction, :string
      attribute :numbered_paragraphs, :string
      attribute :make_anchor, :boolean
      attribute :remove_forced_line_break, :boolean

      xml do
        root "TOCStyle"
        map_attribute "Self", to: :self_attr
        map_attribute "TitleStyle", to: :title_style
        map_attribute "Title", to: :title
        map_attribute "Name", to: :name
        map_attribute "RunIn", to: :run_in
        map_attribute "IncludeHidden", to: :include_hidden
        map_attribute "IncludeBookDocuments", to: :include_book_documents
        map_attribute "CreateBookmarks", to: :create_bookmarks
        map_attribute "SetStoryDirection", to: :set_story_direction
        map_attribute "NumberedParagraphs", to: :numbered_paragraphs
        map_attribute "MakeAnchor", to: :make_anchor
        map_attribute "RemoveForcedLineBreak", to: :remove_forced_line_break
      end
    end
  end
end
