# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TOCStyleEntry>`. Every
    # attribute from `TOCStyleEntry_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (6 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TOCStyleEntry < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :level, :integer
      attribute :page_number_position, :string
      attribute :separator, :string
      attribute :sort_alphabet, :boolean

      xml do
        root "TOCStyleEntry"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "Level", to: :level
        map_attribute "PageNumberPosition", to: :page_number_position
        map_attribute "Separator", to: :separator
        map_attribute "SortAlphabet", to: :sort_alphabet
      end
    end
  end
end
