# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TransparencySetting>`. Every
    # attribute from `TransparencySetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TransparencySetting < Lutaml::Model::Serializable
      xml do
        root "TransparencySetting"
      end
    end
  end
end
