# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TransparencySetting>`. Every
    # attribute from `TransparencySetting_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (0 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TransparencySetting < Lutaml::Model::Serializable
      attribute :blending_setting, Idml::Elements::BlendingSetting
      attribute :drop_shadow_setting, Idml::Elements::DropShadowSetting
      attribute :feather_setting, Idml::Elements::FeatherSetting
      attribute :inner_shadow_setting, Idml::Elements::InnerShadowSetting
      attribute :outer_glow_setting, Idml::Elements::OuterGlowSetting
      attribute :inner_glow_setting, Idml::Elements::InnerGlowSetting
      attribute :bevel_and_emboss_setting, Idml::Elements::BevelAndEmbossSetting
      attribute :satin_setting, Idml::Elements::SatinSetting
      attribute :directional_feather_setting,
                Idml::Elements::DirectionalFeatherSetting
      attribute :gradient_feather_setting,
                Idml::Elements::GradientFeatherSetting

      xml do
        root "TransparencySetting"
        map_element "BlendingSetting", to: :blending_setting
        map_element "DropShadowSetting", to: :drop_shadow_setting
        map_element "FeatherSetting", to: :feather_setting
        map_element "InnerShadowSetting", to: :inner_shadow_setting
        map_element "OuterGlowSetting", to: :outer_glow_setting
        map_element "InnerGlowSetting", to: :inner_glow_setting
        map_element "BevelAndEmbossSetting", to: :bevel_and_emboss_setting
        map_element "SatinSetting", to: :satin_setting
        map_element "DirectionalFeatherSetting",
                    to: :directional_feather_setting
        map_element "GradientFeatherSetting",
                    to: :gradient_feather_setting
      end
    end
  end
end
