# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TransformAttributeOption>`. Every
    # attribute from `TransformAttributeOption_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (7 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TransformAttributeOption < Lutaml::Model::Serializable
      attribute :transform_attr_x, :float
      attribute :transform_attr_y, :float
      attribute :transform_attr_width, :float
      attribute :transform_attr_height, :float
      attribute :transform_attr_left_reference, :string
      attribute :transform_attr_top_reference, :string
      attribute :transform_attr_ref_anchor_point, :string

      xml do
        root "TransformAttributeOption"
        map_attribute "TransformAttrX", to: :transform_attr_x
        map_attribute "TransformAttrY", to: :transform_attr_y
        map_attribute "TransformAttrWidth", to: :transform_attr_width
        map_attribute "TransformAttrHeight", to: :transform_attr_height
        map_attribute "TransformAttrLeftReference", to: :transform_attr_left_reference
        map_attribute "TransformAttrTopReference", to: :transform_attr_top_reference
        map_attribute "TransformAttrRefAnchorPoint", to: :transform_attr_ref_anchor_point
      end
    end
  end
end
