# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<TrapPreset>`. Every
    # attribute from `TrapPreset_Object` in
    # `reference-docs/schemas/package/Resources/Styles.rnc` is declared (16 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class TrapPreset < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string
      attribute :default_trap_width, :float
      attribute :black_width, :float
      attribute :trap_join, :string
      attribute :trap_end, :string
      attribute :objects_to_images, :boolean
      attribute :images_to_images, :boolean
      attribute :internal_images, :boolean
      attribute :one_bit_images, :boolean
      attribute :image_placement, :string
      attribute :step_threshold, :float
      attribute :black_color_threshold, :float
      attribute :black_density, :float
      attribute :sliding_trap_threshold, :float
      attribute :color_reduction, :float

      xml do
        root "TrapPreset"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
        map_attribute "DefaultTrapWidth", to: :default_trap_width
        map_attribute "BlackWidth", to: :black_width
        map_attribute "TrapJoin", to: :trap_join
        map_attribute "TrapEnd", to: :trap_end
        map_attribute "ObjectsToImages", to: :objects_to_images
        map_attribute "ImagesToImages", to: :images_to_images
        map_attribute "InternalImages", to: :internal_images
        map_attribute "OneBitImages", to: :one_bit_images
        map_attribute "ImagePlacement", to: :image_placement
        map_attribute "StepThreshold", to: :step_threshold
        map_attribute "BlackColorThreshold", to: :black_color_threshold
        map_attribute "BlackDensity", to: :black_density
        map_attribute "SlidingTrapThreshold", to: :sliding_trap_threshold
        map_attribute "ColorReduction", to: :color_reduction
      end
    end
  end
end
