# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XmlStory>`. Every
    # attribute from `XmlStory_Object` in
    # `reference-docs/schemas/package/XML/BackingStory.rnc` is declared (295 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XmlStory < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :first_line_indent, :float
      attribute :left_indent, :float
      attribute :right_indent, :float
      attribute :space_before, :float
      attribute :space_after, :float
      attribute :justification, :string
      attribute :single_word_justification, :string
      attribute :auto_leading, :float
      attribute :drop_cap_lines, :integer
      attribute :drop_cap_characters, :integer
      attribute :keep_lines_together, :boolean
      attribute :keep_all_lines_together, :boolean
      attribute :keep_with_next, :integer
      attribute :keep_first_lines, :integer
      attribute :keep_last_lines, :integer
      attribute :start_paragraph, :string
      attribute :composer, :string
      attribute :minimum_word_spacing, :float
      attribute :maximum_word_spacing, :float
      attribute :desired_word_spacing, :float
      attribute :minimum_letter_spacing, :float
      attribute :maximum_letter_spacing, :float
      attribute :desired_letter_spacing, :float
      attribute :minimum_glyph_scaling, :float
      attribute :maximum_glyph_scaling, :float
      attribute :desired_glyph_scaling, :float
      attribute :rule_above, :boolean
      attribute :rule_above_overprint, :boolean
      attribute :rule_above_line_weight, :float
      attribute :rule_above_tint, :float
      attribute :rule_above_offset, :float
      attribute :rule_above_left_indent, :float
      attribute :rule_above_right_indent, :float
      attribute :rule_above_width, :string
      attribute :rule_above_gap_tint, :float
      attribute :rule_above_gap_overprint, :boolean
      attribute :rule_below, :boolean
      attribute :rule_below_line_weight, :float
      attribute :rule_below_tint, :float
      attribute :rule_below_offset, :float
      attribute :rule_below_left_indent, :float
      attribute :rule_below_right_indent, :float
      attribute :rule_below_width, :string
      attribute :rule_below_gap_tint, :float
      attribute :hyphenate_capitalized_words, :boolean
      attribute :hyphenation, :boolean
      attribute :hyphenate_before_last, :integer
      attribute :hyphenate_after_first, :integer
      attribute :hyphenate_words_longer_than, :integer
      attribute :hyphenate_ladder_limit, :integer
      attribute :hyphenation_zone, :float
      attribute :hyphen_weight, :integer
      attribute :applied_paragraph_style, :string
      attribute :applied_character_style, :string
      attribute :font_style, :string
      attribute :point_size, :float
      attribute :kerning_method, :string
      attribute :tracking, :float
      attribute :capitalization, :string
      attribute :position, :string
      attribute :underline, :boolean
      attribute :strike_thru, :boolean
      attribute :ligatures, :boolean
      attribute :no_break, :boolean
      attribute :horizontal_scale, :float
      attribute :vertical_scale, :float
      attribute :baseline_shift, :float
      attribute :skew, :float
      attribute :fill_tint, :float
      attribute :stroke_tint, :float
      attribute :stroke_weight, :float
      attribute :overprint_stroke, :boolean
      attribute :overprint_fill, :boolean
      attribute :otf_figure_style, :string
      attribute :otf_ordinal, :boolean
      attribute :otf_fraction, :boolean
      attribute :otf_discretionary_ligature, :boolean
      attribute :otf_titling, :boolean
      attribute :otf_contextual_alternate, :boolean
      attribute :otf_swash, :boolean
      attribute :underline_tint, :float
      attribute :underline_gap_tint, :float
      attribute :underline_overprint, :boolean
      attribute :underline_gap_overprint, :boolean
      attribute :underline_offset, :float
      attribute :underline_weight, :float
      attribute :strike_through_tint, :float
      attribute :strike_through_gap_tint, :float
      attribute :strike_through_overprint, :boolean
      attribute :strike_through_gap_overprint, :boolean
      attribute :strike_through_offset, :float
      attribute :strike_through_weight, :float
      attribute :fill_color, :string
      attribute :stroke_color, :string
      attribute :applied_language, :string
      attribute :keep_with_previous, :boolean
      attribute :span_column_type, :string
      attribute :split_column_inside_gutter, :float
      attribute :split_column_outside_gutter, :float
      attribute :span_column_min_space_before, :float
      attribute :span_column_min_space_after, :float
      attribute :paragraph_shading_left_offset, :float
      attribute :paragraph_shading_right_offset, :float
      attribute :paragraph_shading_top_offset, :float
      attribute :paragraph_shading_bottom_offset, :float
      attribute :paragraph_shading_width, :string
      attribute :paragraph_shading_top_origin, :string
      attribute :paragraph_shading_bottom_origin, :string
      attribute :paragraph_shading_clip_to_frame, :boolean
      attribute :paragraph_shading_suppress_printing, :boolean
      attribute :paragraph_shading_on, :boolean
      attribute :paragraph_shading_overprint, :boolean
      attribute :paragraph_shading_tint, :float
      attribute :user_text, :boolean
      attribute :is_endnote_story, :boolean
      attribute :paragraph_border_on, :boolean
      attribute :paragraph_border_overprint, :boolean
      attribute :paragraph_border_tint, :float
      attribute :paragraph_border_gap_overprint, :boolean
      attribute :paragraph_border_gap_tint, :float
      attribute :paragraph_border_left_line_weight, :float
      attribute :paragraph_border_top_line_weight, :float
      attribute :paragraph_border_right_line_weight, :float
      attribute :paragraph_border_bottom_line_weight, :float
      attribute :paragraph_border_stroke_end_cap, :string
      attribute :paragraph_border_stroke_end_join, :string
      attribute :paragraph_shading_top_left_corner_radius, :float
      attribute :paragraph_shading_top_left_corner_option, :string
      attribute :paragraph_shading_top_right_corner_radius, :float
      attribute :paragraph_shading_top_right_corner_option, :string
      attribute :paragraph_shading_bottom_left_corner_radius, :float
      attribute :paragraph_shading_bottom_left_corner_option, :string
      attribute :paragraph_shading_bottom_right_corner_radius, :float
      attribute :paragraph_shading_bottom_right_corner_option, :string
      attribute :paragraph_border_top_left_corner_radius, :float
      attribute :paragraph_border_top_left_corner_option, :string
      attribute :paragraph_border_top_right_corner_radius, :float
      attribute :paragraph_border_top_right_corner_option, :string
      attribute :paragraph_border_bottom_left_corner_radius, :float
      attribute :paragraph_border_bottom_left_corner_option, :string
      attribute :paragraph_border_bottom_right_corner_radius, :float
      attribute :paragraph_border_bottom_right_corner_option, :string
      attribute :paragraph_border_width, :string
      attribute :paragraph_border_top_origin, :string
      attribute :paragraph_border_bottom_origin, :string
      attribute :paragraph_border_left_offset, :float
      attribute :paragraph_border_right_offset, :float
      attribute :paragraph_border_top_offset, :float
      attribute :paragraph_border_bottom_offset, :float
      attribute :paragraph_border_display_if_splits, :boolean
      attribute :provider_hyphenation_style, :string
      attribute :merge_consecutive_para_borders, :boolean
      attribute :paragraph_kashida_width, :float
      attribute :last_line_indent, :float
      attribute :hyphenate_last_word, :boolean
      attribute :otf_slashed_zero, :boolean
      attribute :otf_historical, :boolean
      attribute :otf_stylistic_sets, :integer
      attribute :gradient_fill_length, :float
      attribute :gradient_fill_angle, :float
      attribute :gradient_stroke_length, :float
      attribute :gradient_stroke_angle, :float
      attribute :gradient_fill_start, :string
      attribute :gradient_stroke_start, :string
      attribute :rule_below_overprint, :boolean
      attribute :rule_below_gap_overprint, :boolean
      attribute :dropcap_detail, :integer
      attribute :hyphenate_across_columns, :boolean
      attribute :keep_rule_above_in_frame, :boolean
      attribute :ignore_edge_alignment, :boolean
      attribute :otf_mark, :boolean
      attribute :otf_locale, :boolean
      attribute :positional_form, :string
      attribute :paragraph_direction, :string
      attribute :paragraph_justification, :string
      attribute :miter_limit, :float
      attribute :stroke_alignment, :string
      attribute :end_join, :string
      attribute :otf_overlap_swash, :boolean
      attribute :otf_stylistic_alternate, :boolean
      attribute :otf_justification_alternate, :boolean
      attribute :otf_stretched_alternate, :boolean
      attribute :character_direction, :string
      attribute :keyboard_direction, :string
      attribute :digits_type, :string
      attribute :kashidas, :string
      attribute :diacritic_position, :string
      attribute :x_offset_diacritic, :float
      attribute :y_offset_diacritic, :float
      attribute :paragraph_break_type, :string
      attribute :page_number_type, :string
      attribute :character_alignment, :string
      attribute :tsume, :float
      attribute :leading_aki, :float
      attribute :trailing_aki, :float
      attribute :character_rotation, :float
      attribute :jidori, :integer
      attribute :shatai_magnification, :float
      attribute :shatai_degree_angle, :float
      attribute :shatai_adjust_rotation, :boolean
      attribute :shatai_adjust_tsume, :boolean
      attribute :tatechuyoko, :boolean
      attribute :tatechuyoko_x_offset, :float
      attribute :tatechuyoko_y_offset, :float
      attribute :kenten_tint, :float
      attribute :kenten_stroke_tint, :float
      attribute :kenten_weight, :float
      attribute :kenten_overprint_fill, :string
      attribute :kenten_overprint_stroke, :string
      attribute :kenten_kind, :string
      attribute :kenten_placement, :float
      attribute :kenten_alignment, :string
      attribute :kenten_position, :string
      attribute :kenten_font_size, :float
      attribute :kenten_x_scale, :float
      attribute :kenten_y_scale, :float
      attribute :kenten_custom_character, :string
      attribute :kenten_character_set, :string
      attribute :ruby_tint, :float
      attribute :ruby_weight, :float
      attribute :ruby_overprint_fill, :string
      attribute :ruby_overprint_stroke, :string
      attribute :ruby_stroke_tint, :float
      attribute :ruby_font_size, :float
      attribute :ruby_open_type_pro, :boolean
      attribute :ruby_x_scale, :float
      attribute :ruby_y_scale, :float
      attribute :ruby_type, :string
      attribute :ruby_alignment, :string
      attribute :ruby_position, :string
      attribute :ruby_x_offset, :float
      attribute :ruby_y_offset, :float
      attribute :ruby_parent_spacing, :string
      attribute :ruby_auto_align, :boolean
      attribute :ruby_overhang, :boolean
      attribute :ruby_auto_scaling, :boolean
      attribute :ruby_parent_scaling_percent, :float
      attribute :ruby_parent_overhang_amount, :string
      attribute :warichu, :boolean
      attribute :warichu_size, :float
      attribute :warichu_lines, :integer
      attribute :warichu_line_spacing, :float
      attribute :warichu_alignment, :string
      attribute :warichu_chars_after_break, :integer
      attribute :warichu_chars_before_break, :integer
      attribute :otf_proportional_metrics, :boolean
      attribute :otfhv_kana, :boolean
      attribute :otf_roman_italics, :boolean
      attribute :scale_affects_line_height, :boolean
      attribute :cjk_grid_tracking, :boolean
      attribute :glyph_form, :string
      attribute :ruby_flag, :integer
      attribute :ruby_string, :string
      attribute :grid_align_first_line_only, :boolean
      attribute :grid_alignment, :string
      attribute :grid_gyoudori, :integer
      attribute :auto_tcy, :integer
      attribute :auto_tcy_include_roman, :boolean
      attribute :kinsoku_type, :string
      attribute :kinsoku_hang_type, :string
      attribute :bunri_kinshi, :boolean
      attribute :rensuuji, :boolean
      attribute :rotate_single_byte_characters, :boolean
      attribute :leading_model, :string
      attribute :ruby_auto_tcy_digits, :integer
      attribute :ruby_auto_tcy_include_roman, :boolean
      attribute :ruby_auto_tcy_auto_scale, :boolean
      attribute :treat_ideographic_space_as_space, :boolean
      attribute :allow_arbitrary_hyphenation, :boolean
      attribute :paragraph_gyoudori, :boolean
      attribute :link_resource_id, :integer
      attribute :applied_toc_style, :string
      attribute :bullets_and_numbering_list_type, :string
      attribute :numbering_expression, :string
      attribute :bullets_text_after, :string
      attribute :numbering_level, :integer
      attribute :numbering_continue, :boolean
      attribute :numbering_start_at, :integer
      attribute :numbering_apply_restart_policy, :boolean
      attribute :bullets_alignment, :string
      attribute :numbering_alignment, :string
      attribute :track_changes, :boolean
      attribute :story_title, :string
      attribute :applied_named_grid, :string
      attribute :ai_generated_story, :boolean
      attribute :ai_model_name, :string
      attribute :ai_digital_source_type, :string
      attribute :ai_first_party, :boolean
      attribute :ai_text_content, :string
      attribute :bullet_character_type, :string
      attribute :bullet_character_value, :integer
      attribute :restart_policy, :string
      attribute :lower_level, :integer
      attribute :upper_level, :integer

      attribute :xml_element, Idml::Elements::XmlElement, collection: true

      xml do
        root "XmlStory"
        map_attribute "Self", to: :self_attr
        map_attribute "FirstLineIndent", to: :first_line_indent
        map_attribute "LeftIndent", to: :left_indent
        map_attribute "RightIndent", to: :right_indent
        map_attribute "SpaceBefore", to: :space_before
        map_attribute "SpaceAfter", to: :space_after
        map_attribute "Justification", to: :justification
        map_attribute "SingleWordJustification", to: :single_word_justification
        map_attribute "AutoLeading", to: :auto_leading
        map_attribute "DropCapLines", to: :drop_cap_lines
        map_attribute "DropCapCharacters", to: :drop_cap_characters
        map_attribute "KeepLinesTogether", to: :keep_lines_together
        map_attribute "KeepAllLinesTogether", to: :keep_all_lines_together
        map_attribute "KeepWithNext", to: :keep_with_next
        map_attribute "KeepFirstLines", to: :keep_first_lines
        map_attribute "KeepLastLines", to: :keep_last_lines
        map_attribute "StartParagraph", to: :start_paragraph
        map_attribute "Composer", to: :composer
        map_attribute "MinimumWordSpacing", to: :minimum_word_spacing
        map_attribute "MaximumWordSpacing", to: :maximum_word_spacing
        map_attribute "DesiredWordSpacing", to: :desired_word_spacing
        map_attribute "MinimumLetterSpacing", to: :minimum_letter_spacing
        map_attribute "MaximumLetterSpacing", to: :maximum_letter_spacing
        map_attribute "DesiredLetterSpacing", to: :desired_letter_spacing
        map_attribute "MinimumGlyphScaling", to: :minimum_glyph_scaling
        map_attribute "MaximumGlyphScaling", to: :maximum_glyph_scaling
        map_attribute "DesiredGlyphScaling", to: :desired_glyph_scaling
        map_attribute "RuleAbove", to: :rule_above
        map_attribute "RuleAboveOverprint", to: :rule_above_overprint
        map_attribute "RuleAboveLineWeight", to: :rule_above_line_weight
        map_attribute "RuleAboveTint", to: :rule_above_tint
        map_attribute "RuleAboveOffset", to: :rule_above_offset
        map_attribute "RuleAboveLeftIndent", to: :rule_above_left_indent
        map_attribute "RuleAboveRightIndent", to: :rule_above_right_indent
        map_attribute "RuleAboveWidth", to: :rule_above_width
        map_attribute "RuleAboveGapTint", to: :rule_above_gap_tint
        map_attribute "RuleAboveGapOverprint", to: :rule_above_gap_overprint
        map_attribute "RuleBelow", to: :rule_below
        map_attribute "RuleBelowLineWeight", to: :rule_below_line_weight
        map_attribute "RuleBelowTint", to: :rule_below_tint
        map_attribute "RuleBelowOffset", to: :rule_below_offset
        map_attribute "RuleBelowLeftIndent", to: :rule_below_left_indent
        map_attribute "RuleBelowRightIndent", to: :rule_below_right_indent
        map_attribute "RuleBelowWidth", to: :rule_below_width
        map_attribute "RuleBelowGapTint", to: :rule_below_gap_tint
        map_attribute "HyphenateCapitalizedWords", to: :hyphenate_capitalized_words
        map_attribute "Hyphenation", to: :hyphenation
        map_attribute "HyphenateBeforeLast", to: :hyphenate_before_last
        map_attribute "HyphenateAfterFirst", to: :hyphenate_after_first
        map_attribute "HyphenateWordsLongerThan", to: :hyphenate_words_longer_than
        map_attribute "HyphenateLadderLimit", to: :hyphenate_ladder_limit
        map_attribute "HyphenationZone", to: :hyphenation_zone
        map_attribute "HyphenWeight", to: :hyphen_weight
        map_attribute "AppliedParagraphStyle", to: :applied_paragraph_style
        map_attribute "AppliedCharacterStyle", to: :applied_character_style
        map_attribute "FontStyle", to: :font_style
        map_attribute "PointSize", to: :point_size
        map_attribute "KerningMethod", to: :kerning_method
        map_attribute "Tracking", to: :tracking
        map_attribute "Capitalization", to: :capitalization
        map_attribute "Position", to: :position
        map_attribute "Underline", to: :underline
        map_attribute "StrikeThru", to: :strike_thru
        map_attribute "Ligatures", to: :ligatures
        map_attribute "NoBreak", to: :no_break
        map_attribute "HorizontalScale", to: :horizontal_scale
        map_attribute "VerticalScale", to: :vertical_scale
        map_attribute "BaselineShift", to: :baseline_shift
        map_attribute "Skew", to: :skew
        map_attribute "FillTint", to: :fill_tint
        map_attribute "StrokeTint", to: :stroke_tint
        map_attribute "StrokeWeight", to: :stroke_weight
        map_attribute "OverprintStroke", to: :overprint_stroke
        map_attribute "OverprintFill", to: :overprint_fill
        map_attribute "OTFFigureStyle", to: :otf_figure_style
        map_attribute "OTFOrdinal", to: :otf_ordinal
        map_attribute "OTFFraction", to: :otf_fraction
        map_attribute "OTFDiscretionaryLigature", to: :otf_discretionary_ligature
        map_attribute "OTFTitling", to: :otf_titling
        map_attribute "OTFContextualAlternate", to: :otf_contextual_alternate
        map_attribute "OTFSwash", to: :otf_swash
        map_attribute "UnderlineTint", to: :underline_tint
        map_attribute "UnderlineGapTint", to: :underline_gap_tint
        map_attribute "UnderlineOverprint", to: :underline_overprint
        map_attribute "UnderlineGapOverprint", to: :underline_gap_overprint
        map_attribute "UnderlineOffset", to: :underline_offset
        map_attribute "UnderlineWeight", to: :underline_weight
        map_attribute "StrikeThroughTint", to: :strike_through_tint
        map_attribute "StrikeThroughGapTint", to: :strike_through_gap_tint
        map_attribute "StrikeThroughOverprint", to: :strike_through_overprint
        map_attribute "StrikeThroughGapOverprint", to: :strike_through_gap_overprint
        map_attribute "StrikeThroughOffset", to: :strike_through_offset
        map_attribute "StrikeThroughWeight", to: :strike_through_weight
        map_attribute "FillColor", to: :fill_color
        map_attribute "StrokeColor", to: :stroke_color
        map_attribute "AppliedLanguage", to: :applied_language
        map_attribute "KeepWithPrevious", to: :keep_with_previous
        map_attribute "SpanColumnType", to: :span_column_type
        map_attribute "SplitColumnInsideGutter", to: :split_column_inside_gutter
        map_attribute "SplitColumnOutsideGutter", to: :split_column_outside_gutter
        map_attribute "SpanColumnMinSpaceBefore", to: :span_column_min_space_before
        map_attribute "SpanColumnMinSpaceAfter", to: :span_column_min_space_after
        map_attribute "ParagraphShadingLeftOffset", to: :paragraph_shading_left_offset
        map_attribute "ParagraphShadingRightOffset", to: :paragraph_shading_right_offset
        map_attribute "ParagraphShadingTopOffset", to: :paragraph_shading_top_offset
        map_attribute "ParagraphShadingBottomOffset", to: :paragraph_shading_bottom_offset
        map_attribute "ParagraphShadingWidth", to: :paragraph_shading_width
        map_attribute "ParagraphShadingTopOrigin", to: :paragraph_shading_top_origin
        map_attribute "ParagraphShadingBottomOrigin", to: :paragraph_shading_bottom_origin
        map_attribute "ParagraphShadingClipToFrame", to: :paragraph_shading_clip_to_frame
        map_attribute "ParagraphShadingSuppressPrinting", to: :paragraph_shading_suppress_printing
        map_attribute "ParagraphShadingOn", to: :paragraph_shading_on
        map_attribute "ParagraphShadingOverprint", to: :paragraph_shading_overprint
        map_attribute "ParagraphShadingTint", to: :paragraph_shading_tint
        map_attribute "UserText", to: :user_text
        map_attribute "IsEndnoteStory", to: :is_endnote_story
        map_attribute "ParagraphBorderOn", to: :paragraph_border_on
        map_attribute "ParagraphBorderOverprint", to: :paragraph_border_overprint
        map_attribute "ParagraphBorderTint", to: :paragraph_border_tint
        map_attribute "ParagraphBorderGapOverprint", to: :paragraph_border_gap_overprint
        map_attribute "ParagraphBorderGapTint", to: :paragraph_border_gap_tint
        map_attribute "ParagraphBorderLeftLineWeight", to: :paragraph_border_left_line_weight
        map_attribute "ParagraphBorderTopLineWeight", to: :paragraph_border_top_line_weight
        map_attribute "ParagraphBorderRightLineWeight", to: :paragraph_border_right_line_weight
        map_attribute "ParagraphBorderBottomLineWeight", to: :paragraph_border_bottom_line_weight
        map_attribute "ParagraphBorderStrokeEndCap", to: :paragraph_border_stroke_end_cap
        map_attribute "ParagraphBorderStrokeEndJoin", to: :paragraph_border_stroke_end_join
        map_attribute "ParagraphShadingTopLeftCornerRadius", to: :paragraph_shading_top_left_corner_radius
        map_attribute "ParagraphShadingTopLeftCornerOption", to: :paragraph_shading_top_left_corner_option
        map_attribute "ParagraphShadingTopRightCornerRadius", to: :paragraph_shading_top_right_corner_radius
        map_attribute "ParagraphShadingTopRightCornerOption", to: :paragraph_shading_top_right_corner_option
        map_attribute "ParagraphShadingBottomLeftCornerRadius", to: :paragraph_shading_bottom_left_corner_radius
        map_attribute "ParagraphShadingBottomLeftCornerOption", to: :paragraph_shading_bottom_left_corner_option
        map_attribute "ParagraphShadingBottomRightCornerRadius", to: :paragraph_shading_bottom_right_corner_radius
        map_attribute "ParagraphShadingBottomRightCornerOption", to: :paragraph_shading_bottom_right_corner_option
        map_attribute "ParagraphBorderTopLeftCornerRadius", to: :paragraph_border_top_left_corner_radius
        map_attribute "ParagraphBorderTopLeftCornerOption", to: :paragraph_border_top_left_corner_option
        map_attribute "ParagraphBorderTopRightCornerRadius", to: :paragraph_border_top_right_corner_radius
        map_attribute "ParagraphBorderTopRightCornerOption", to: :paragraph_border_top_right_corner_option
        map_attribute "ParagraphBorderBottomLeftCornerRadius", to: :paragraph_border_bottom_left_corner_radius
        map_attribute "ParagraphBorderBottomLeftCornerOption", to: :paragraph_border_bottom_left_corner_option
        map_attribute "ParagraphBorderBottomRightCornerRadius", to: :paragraph_border_bottom_right_corner_radius
        map_attribute "ParagraphBorderBottomRightCornerOption", to: :paragraph_border_bottom_right_corner_option
        map_attribute "ParagraphBorderWidth", to: :paragraph_border_width
        map_attribute "ParagraphBorderTopOrigin", to: :paragraph_border_top_origin
        map_attribute "ParagraphBorderBottomOrigin", to: :paragraph_border_bottom_origin
        map_attribute "ParagraphBorderLeftOffset", to: :paragraph_border_left_offset
        map_attribute "ParagraphBorderRightOffset", to: :paragraph_border_right_offset
        map_attribute "ParagraphBorderTopOffset", to: :paragraph_border_top_offset
        map_attribute "ParagraphBorderBottomOffset", to: :paragraph_border_bottom_offset
        map_attribute "ParagraphBorderDisplayIfSplits", to: :paragraph_border_display_if_splits
        map_attribute "ProviderHyphenationStyle", to: :provider_hyphenation_style
        map_attribute "MergeConsecutiveParaBorders", to: :merge_consecutive_para_borders
        map_attribute "ParagraphKashidaWidth", to: :paragraph_kashida_width
        map_attribute "LastLineIndent", to: :last_line_indent
        map_attribute "HyphenateLastWord", to: :hyphenate_last_word
        map_attribute "OTFSlashedZero", to: :otf_slashed_zero
        map_attribute "OTFHistorical", to: :otf_historical
        map_attribute "OTFStylisticSets", to: :otf_stylistic_sets
        map_attribute "GradientFillLength", to: :gradient_fill_length
        map_attribute "GradientFillAngle", to: :gradient_fill_angle
        map_attribute "GradientStrokeLength", to: :gradient_stroke_length
        map_attribute "GradientStrokeAngle", to: :gradient_stroke_angle
        map_attribute "GradientFillStart", to: :gradient_fill_start
        map_attribute "GradientStrokeStart", to: :gradient_stroke_start
        map_attribute "RuleBelowOverprint", to: :rule_below_overprint
        map_attribute "RuleBelowGapOverprint", to: :rule_below_gap_overprint
        map_attribute "DropcapDetail", to: :dropcap_detail
        map_attribute "HyphenateAcrossColumns", to: :hyphenate_across_columns
        map_attribute "KeepRuleAboveInFrame", to: :keep_rule_above_in_frame
        map_attribute "IgnoreEdgeAlignment", to: :ignore_edge_alignment
        map_attribute "OTFMark", to: :otf_mark
        map_attribute "OTFLocale", to: :otf_locale
        map_attribute "PositionalForm", to: :positional_form
        map_attribute "ParagraphDirection", to: :paragraph_direction
        map_attribute "ParagraphJustification", to: :paragraph_justification
        map_attribute "MiterLimit", to: :miter_limit
        map_attribute "StrokeAlignment", to: :stroke_alignment
        map_attribute "EndJoin", to: :end_join
        map_attribute "OTFOverlapSwash", to: :otf_overlap_swash
        map_attribute "OTFStylisticAlternate", to: :otf_stylistic_alternate
        map_attribute "OTFJustificationAlternate", to: :otf_justification_alternate
        map_attribute "OTFStretchedAlternate", to: :otf_stretched_alternate
        map_attribute "CharacterDirection", to: :character_direction
        map_attribute "KeyboardDirection", to: :keyboard_direction
        map_attribute "DigitsType", to: :digits_type
        map_attribute "Kashidas", to: :kashidas
        map_attribute "DiacriticPosition", to: :diacritic_position
        map_attribute "XOffsetDiacritic", to: :x_offset_diacritic
        map_attribute "YOffsetDiacritic", to: :y_offset_diacritic
        map_attribute "ParagraphBreakType", to: :paragraph_break_type
        map_attribute "PageNumberType", to: :page_number_type
        map_attribute "CharacterAlignment", to: :character_alignment
        map_attribute "Tsume", to: :tsume
        map_attribute "LeadingAki", to: :leading_aki
        map_attribute "TrailingAki", to: :trailing_aki
        map_attribute "CharacterRotation", to: :character_rotation
        map_attribute "Jidori", to: :jidori
        map_attribute "ShataiMagnification", to: :shatai_magnification
        map_attribute "ShataiDegreeAngle", to: :shatai_degree_angle
        map_attribute "ShataiAdjustRotation", to: :shatai_adjust_rotation
        map_attribute "ShataiAdjustTsume", to: :shatai_adjust_tsume
        map_attribute "Tatechuyoko", to: :tatechuyoko
        map_attribute "TatechuyokoXOffset", to: :tatechuyoko_x_offset
        map_attribute "TatechuyokoYOffset", to: :tatechuyoko_y_offset
        map_attribute "KentenTint", to: :kenten_tint
        map_attribute "KentenStrokeTint", to: :kenten_stroke_tint
        map_attribute "KentenWeight", to: :kenten_weight
        map_attribute "KentenOverprintFill", to: :kenten_overprint_fill
        map_attribute "KentenOverprintStroke", to: :kenten_overprint_stroke
        map_attribute "KentenKind", to: :kenten_kind
        map_attribute "KentenPlacement", to: :kenten_placement
        map_attribute "KentenAlignment", to: :kenten_alignment
        map_attribute "KentenPosition", to: :kenten_position
        map_attribute "KentenFontSize", to: :kenten_font_size
        map_attribute "KentenXScale", to: :kenten_x_scale
        map_attribute "KentenYScale", to: :kenten_y_scale
        map_attribute "KentenCustomCharacter", to: :kenten_custom_character
        map_attribute "KentenCharacterSet", to: :kenten_character_set
        map_attribute "RubyTint", to: :ruby_tint
        map_attribute "RubyWeight", to: :ruby_weight
        map_attribute "RubyOverprintFill", to: :ruby_overprint_fill
        map_attribute "RubyOverprintStroke", to: :ruby_overprint_stroke
        map_attribute "RubyStrokeTint", to: :ruby_stroke_tint
        map_attribute "RubyFontSize", to: :ruby_font_size
        map_attribute "RubyOpenTypePro", to: :ruby_open_type_pro
        map_attribute "RubyXScale", to: :ruby_x_scale
        map_attribute "RubyYScale", to: :ruby_y_scale
        map_attribute "RubyType", to: :ruby_type
        map_attribute "RubyAlignment", to: :ruby_alignment
        map_attribute "RubyPosition", to: :ruby_position
        map_attribute "RubyXOffset", to: :ruby_x_offset
        map_attribute "RubyYOffset", to: :ruby_y_offset
        map_attribute "RubyParentSpacing", to: :ruby_parent_spacing
        map_attribute "RubyAutoAlign", to: :ruby_auto_align
        map_attribute "RubyOverhang", to: :ruby_overhang
        map_attribute "RubyAutoScaling", to: :ruby_auto_scaling
        map_attribute "RubyParentScalingPercent", to: :ruby_parent_scaling_percent
        map_attribute "RubyParentOverhangAmount", to: :ruby_parent_overhang_amount
        map_attribute "Warichu", to: :warichu
        map_attribute "WarichuSize", to: :warichu_size
        map_attribute "WarichuLines", to: :warichu_lines
        map_attribute "WarichuLineSpacing", to: :warichu_line_spacing
        map_attribute "WarichuAlignment", to: :warichu_alignment
        map_attribute "WarichuCharsAfterBreak", to: :warichu_chars_after_break
        map_attribute "WarichuCharsBeforeBreak", to: :warichu_chars_before_break
        map_attribute "OTFProportionalMetrics", to: :otf_proportional_metrics
        map_attribute "OTFHVKana", to: :otfhv_kana
        map_attribute "OTFRomanItalics", to: :otf_roman_italics
        map_attribute "ScaleAffectsLineHeight", to: :scale_affects_line_height
        map_attribute "CjkGridTracking", to: :cjk_grid_tracking
        map_attribute "GlyphForm", to: :glyph_form
        map_attribute "RubyFlag", to: :ruby_flag
        map_attribute "RubyString", to: :ruby_string
        map_attribute "GridAlignFirstLineOnly", to: :grid_align_first_line_only
        map_attribute "GridAlignment", to: :grid_alignment
        map_attribute "GridGyoudori", to: :grid_gyoudori
        map_attribute "AutoTcy", to: :auto_tcy
        map_attribute "AutoTcyIncludeRoman", to: :auto_tcy_include_roman
        map_attribute "KinsokuType", to: :kinsoku_type
        map_attribute "KinsokuHangType", to: :kinsoku_hang_type
        map_attribute "BunriKinshi", to: :bunri_kinshi
        map_attribute "Rensuuji", to: :rensuuji
        map_attribute "RotateSingleByteCharacters", to: :rotate_single_byte_characters
        map_attribute "LeadingModel", to: :leading_model
        map_attribute "RubyAutoTcyDigits", to: :ruby_auto_tcy_digits
        map_attribute "RubyAutoTcyIncludeRoman", to: :ruby_auto_tcy_include_roman
        map_attribute "RubyAutoTcyAutoScale", to: :ruby_auto_tcy_auto_scale
        map_attribute "TreatIdeographicSpaceAsSpace", to: :treat_ideographic_space_as_space
        map_attribute "AllowArbitraryHyphenation", to: :allow_arbitrary_hyphenation
        map_attribute "ParagraphGyoudori", to: :paragraph_gyoudori
        map_attribute "LinkResourceId", to: :link_resource_id
        map_attribute "AppliedTOCStyle", to: :applied_toc_style
        map_attribute "BulletsAndNumberingListType", to: :bullets_and_numbering_list_type
        map_attribute "NumberingExpression", to: :numbering_expression
        map_attribute "BulletsTextAfter", to: :bullets_text_after
        map_attribute "NumberingLevel", to: :numbering_level
        map_attribute "NumberingContinue", to: :numbering_continue
        map_attribute "NumberingStartAt", to: :numbering_start_at
        map_attribute "NumberingApplyRestartPolicy", to: :numbering_apply_restart_policy
        map_attribute "BulletsAlignment", to: :bullets_alignment
        map_attribute "NumberingAlignment", to: :numbering_alignment
        map_attribute "TrackChanges", to: :track_changes
        map_attribute "StoryTitle", to: :story_title
        map_attribute "AppliedNamedGrid", to: :applied_named_grid
        map_attribute "AiGeneratedStory", to: :ai_generated_story
        map_attribute "AiModelName", to: :ai_model_name
        map_attribute "AiDigitalSourceType", to: :ai_digital_source_type
        map_attribute "AiFirstParty", to: :ai_first_party
        map_attribute "AiTextContent", to: :ai_text_content
        map_attribute "BulletCharacterType", to: :bullet_character_type
        map_attribute "BulletCharacterValue", to: :bullet_character_value
        map_attribute "RestartPolicy", to: :restart_policy
        map_attribute "LowerLevel", to: :lower_level
        map_attribute "UpperLevel", to: :upper_level
        map_element "XMLElement", to: :xml_element
      end
    end
  end
end
