# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLElement>`. Every
    # attribute from `XMLElement_Object` in
    # `reference-docs/schemas/package/Stories/Story.rnc` is declared (4 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XmlElement < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :markup_tag, :string
      attribute :xml_content, :string
      attribute :no_text_marker, :boolean

      attribute :xml_element, Idml::Elements::XmlElement, collection: true
      attribute :content, Idml::Elements::Content, collection: true

      xml do
        root "XMLElement"
        map_attribute "Self", to: :self_attr
        map_attribute "MarkupTag", to: :markup_tag
        map_attribute "XMLContent", to: :xml_content
        map_attribute "NoTextMarker", to: :no_text_marker
        map_element "XMLElement", to: :xml_element
        map_element "Content", to: :content
      end

      def text_content
        [
          content.map(&:text),
          xml_element.map(&:text_content),
        ].join
      end

      def each_xml_element(&block)
        yield self
        xml_element.each { |c| c.each_xml_element(&block) }
      end
    end
  end
end
