# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLImportMap>`. Every
    # attribute from `XMLImportMap_Object` in
    # `reference-docs/schemas/package/XML/Mapping.rnc` is declared (3 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XmlImportMap < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :markup_tag, :string
      attribute :mapped_style, :string

      xml do
        root "XMLImportMap"
        map_attribute "Self", to: :self_attr
        map_attribute "MarkupTag", to: :markup_tag
        map_attribute "MappedStyle", to: :mapped_style
      end
    end
  end
end
