# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLExportMap>`. Every
    # attribute from `XMLExportMap_Object` in
    # `reference-docs/schemas/package/XML/Mapping.rnc` is declared (6 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XmlExportMap < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :markup_tag, :string
      attribute :mapped_style, :string
      attribute :include_master_page_stories, :boolean
      attribute :include_pasteboard_stories, :boolean
      attribute :include_empty_stories, :boolean

      xml do
        root "XMLExportMap"
        map_attribute "Self", to: :self_attr
        map_attribute "MarkupTag", to: :markup_tag
        map_attribute "MappedStyle", to: :mapped_style
        map_attribute "IncludeMasterPageStories",
                      to: :include_master_page_stories
        map_attribute "IncludePasteboardStories",
                      to: :include_pasteboard_stories
        map_attribute "IncludeEmptyStories", to: :include_empty_stories
      end
    end
  end
end
