# frozen_string_literal: true

module Idml
  module Elements
    # Typed model of `<XMLTag>`. Every
    # attribute from `XMLTag_Object` in
    # `reference-docs/schemas/package/XML/Tags.rnc` is declared (2 attributes),
    # generated by `scripts/rnc_to_lutaml.rb`.
    class XmlTag < Lutaml::Model::Serializable
      attribute :self_attr, :string
      attribute :name, :string

      xml do
        root "XMLTag"
        map_attribute "Self", to: :self_attr
        map_attribute "Name", to: :name
      end
    end
  end
end
