# frozen_string_literal: true

# Assembles a faithful lutaml-model class file from an RNC element
# definition. Used to regenerate lib/idml/elements/*.rb when the
# schemas change.

rnc_path = ARGV[0]
element_name = ARGV[1]
class_name = ARGV[2]
output_path = ARGV[3]
children_str = ARGV[4] # "Content,XmlElement" — typed children to declare

abort "usage: #{$PROGRAM_NAME} <rnc> <Element_Object> <ClassName> <output.rb> <child,child>" unless output_path

require "shellwords"
codegen_output = `ruby scripts/rnc_to_lutaml.rb #{rnc_path.shellescape} #{element_name.shellescape}`
attr_decls = codegen_output.lines.grep(/^attribute :(?!_placeholder)/)
map_attrs = codegen_output.lines.grep(/^  map_attribute /)

# Parse children list
children = children_str.split(",").map(&:strip).reject(&:empty?)

# Build child attribute + map_element declarations
child_decls = children.map do |child|
  "      attribute :#{child.downcase}, Idml::Elements::#{child}, collection: true"
end
child_maps = children.map do |child|
  %(        map_element "#{child}", to: :#{child.downcase})
end

out = []
out << "# frozen_string_literal: true"
out << ""
out << "module Idml"
out << "  module Elements"
out << "    # Typed model of `<#{element_name.sub('_Object', '')}>`. Every"
out << "    # attribute from `#{element_name}` in"
out << "    # `#{rnc_path}` is declared (#{attr_decls.length} attributes),"
out << "    # generated by `scripts/rnc_to_lutaml.rb`."
out << "    class #{class_name} < Lutaml::Model::Serializable"
attr_decls.each { |l| out << "      #{l.chomp}" }
out << ""
child_decls.each { |l| out << l }
out << ""
out << "      xml do"
out << "        root \"#{class_name}\""
map_attrs.each { |l| out << "        #{l.chomp}" }
child_maps.each { |l| out << l }
out << "      end"
out << "    end"
out << "  end"
out << "end"

File.write(output_path, "#{out.join("\n")}\n")
puts "wrote #{output_path} (#{out.length} lines, #{attr_decls.length} attrs)"
