# frozen_string_literal: true

# Assembles a faithful lutaml-model class file from an RNC element
# definition. Used to regenerate lib/idml/elements/*.rb when the
# schemas change.
#
# Usage:
#   scripts/assemble_element.rb <rnc> <Element_Object> <ClassName> \
#       <output.rb> <child,child> <xml_root_name>
#
# - <rnc>: path to the .rnc file containing the element definition.
# - <Element_Object>: the RNC rule name (e.g., Story_Object).
# - <ClassName>: Ruby class name (e.g., StoryInner).
# - <output.rb>: where to write the assembled Ruby file.
# - <child,child>: comma-separated list of typed children. Each entry
#   is either a Ruby class name ("Content") or "RubyClass:XmlName"
#   ("XmlElement:XMLElement") when they differ.
# - <xml_root_name>: the XML element name (defaults to ClassName).

rnc_path = ARGV[0]
element_name = ARGV[1]
class_name = ARGV[2]
output_path = ARGV[3]
children_str = ARGV[4] || ""
xml_root_name = ARGV[5] || class_name

abort "usage: #{$PROGRAM_NAME} <rnc> <Element_Object> <ClassName> <output.rb> <child,child> <xml_root_name>" unless output_path

require "shellwords"
codegen_output = `ruby scripts/rnc_to_lutaml.rb #{rnc_path.shellescape} #{element_name.shellescape}`
attr_decls = codegen_output.lines.grep(/^attribute :(?!_placeholder)/)
map_attrs = codegen_output.lines.grep(/^  map_attribute /)

children = children_str.split(",").map(&:strip).reject(&:empty?)

child_attr_name = lambda do |ruby_class|
  ruby_class
    .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
    .gsub(/([a-z\d])([A-Z])/, '\1_\2')
    .downcase
end

child_decls = children.map do |child|
  ruby_class = child.split(":").first
  "      attribute :#{child_attr_name.call(ruby_class)}, Idml::Elements::#{ruby_class}, collection: true"
end
child_maps = children.map do |child|
  ruby_class, xml_name = child.split(":")
  xml_name ||= ruby_class
  %(        map_element "#{xml_name}", to: :#{child_attr_name.call(ruby_class)})
end

# Preserve def blocks from the existing file so regeneration
# doesn't lose text_content, each_xml_element, etc.
preserved_methods = []
if File.exist?(output_path)
  existing = File.read(output_path)
  existing.scan(/^      def [^\n]+.*?^      end$/m) { |m| preserved_methods << m.rstrip }
end

out = []
out << "# frozen_string_literal: true"
out << ""
out << "module Idml"
out << "  module Elements"
out << "    # Typed model of `<#{xml_root_name}>`. Every"
out << "    # attribute from `#{element_name}` in"
out << "    # `#{rnc_path}` is declared (#{attr_decls.length} attributes),"
out << "    # generated by `scripts/rnc_to_lutaml.rb`."
out << "    class #{class_name} < Lutaml::Model::Serializable"
attr_decls.each { |l| out << "      #{l.chomp}" }
out << ""
child_decls.each { |l| out << l }
out << ""
out << "      xml do"
out << "        root \"#{xml_root_name}\""
map_attrs.each { |l| out << "        #{l.chomp.gsub(/", to: :(\w+)"/, '", to: :\1')}" }
child_maps.each { |l| out << l }
out << "      end"
out << ""
preserved_methods.each do |m|
  out << m
  out << ""
end
out << "    end"
out << "  end"
out << "end"

File.write(output_path, "#{out.join("\n")}\n")
puts "wrote #{output_path} (#{out.length} lines, #{attr_decls.length} attrs, #{preserved_methods.length} methods)"
