Preferences_File = element idPkg:Preferences { attribute DOMVersion { "7.0" }, ( DataMerge_Object?& DataMergeOption_Object?& LayoutAdjustmentPreference_Object?& EPubExportPreference_Object?& HTMLExportPreference_Object?& XMLPreference_Object?& XMLImportPreference_Object?& XMLExportPreference_Object?& ExportForWebPreference_Object?& TransparencyPreference_Object?& TransparencyDefaultContainerObject_Object?& TextFramePreference_Object?& TextPreference_Object?& TextDefault_Object?& DictionaryPreference_Object?& StoryPreference_Object?& AnchoredObjectDefault_Object?& AnchoredObjectSetting_Object?& BaselineFrameGridOption_Object?& FootnoteOption_Object?&
TextWrapPreference_Object?& DocumentPreference_Object?& GridPreference_Object?& GuidePreference_Object?& MarginPreference_Object?& PasteboardPreference_Object?& ViewPreference_Object?& PrintPreference_Object?& PrintBookletOption_Object?& PrintBookletPrintPreference_Object?& IndexOptions_Object?& IndexHeaderSetting_Object?& PageItemDefault_Object?& FrameFittingOption_Object?& ButtonPreference_Object?& TinDocumentDataObject_Object?& LayoutGridDataInformation_Object?& StoryGridDataInformation_Object?& CjkGridPreference_Object?& MojikumiUiPreference_Object?& ChapterNumberPreference_Object? ) }
