XMLImportPreference_Object = element XMLImportPreference { attribute CreateLinkToXML { xsd:boolean }?, attribute RepeatTextElements { xsd:boolean }?, attribute IgnoreUnmatchedIncoming { xsd:boolean }?, attribute ImportTextIntoTables { xsd:boolean }?, attribute IgnoreWhitespace { xsd:boolean }?, attribute RemoveUnmatchedExisting { xsd:boolean }?, attribute ImportToSelected { xsd:boolean }?, attribute ImportStyle { XMLImportStyles_EnumValue }?, attribute AllowTransform { xsd:boolean }?, attribute ImportCALSTables { xsd:boolean }?, element Properties { element TransformFilename { (file_type, xsd:string ) | (enum_type, XMLTransformFile_EnumValue ) }?& element TransformParameters { element NameValuePair { NameValuePair_TypeDef }* }? } ? }
