XMLPreference_Object = element XMLPreference { attribute DefaultStoryTagName { xsd:string }?, attribute DefaultTableTagName { xsd:string }?, attribute DefaultCellTagName { xsd:string }?, attribute DefaultImageTagName { xsd:string }?, element Properties { element DefaultStoryTagColor { InDesignUIColorType_TypeDef }?& element DefaultTableTagColor { InDesignUIColorType_TypeDef }?& element DefaultCellTagColor { InDesignUIColorType_TypeDef }?& element DefaultImageTagColor { InDesignUIColorType_TypeDef }? } ? }
