ExportForWebPreference_Object = element ExportForWebPreference { attribute CopyFormattedImages { xsd:boolean }?, attribute CopyOptimizedImages { xsd:boolean }?, attribute CopyOriginalImages { xsd:boolean }?, attribute ImageConversion { ImageConversion_EnumValue }?, attribute GIFOptionsPalette { GIFOptionsPalette_EnumValue }?, attribute GIFOptionsInterlaced { xsd:boolean }?, attribute JPEGOptionsQuality { JPEGOptionsQuality_EnumValue }?, attribute JPEGOptionsFormat { JPEGOptionsFormat_EnumValue }? }
