PrintBookletOption_Object = element PrintBookletOption { attribute BookletType { BookletTypeOptions_EnumValue }?, attribute SpaceBetweenPages { xsd:double {minInclusive="0" maxInclusive="288"} }?, attribute BleedBetweenPages { xsd:double {minInclusive="0" maxInclusive="144"} }?, attribute Creep { xsd:double {minInclusive="-144" maxInclusive="144"} }?, attribute SignatureSize { SignatureSizeOptions_EnumValue }?, attribute TopMargin { xsd:double {minInclusive="0" maxInclusive="288"} }?, attribute BottomMargin { xsd:double {minInclusive="0" maxInclusive="288"} }?, attribute LeftMargin { xsd:double {minInclusive="0" maxInclusive="288"} }?, attribute RightMargin { xsd:double {minInclusive="0" maxInclusive="288"} }?, attribute AutoAdjustMargins { xsd:boolean }?, attribute MarginsUniformSize { xsd:boolean }?, attribute PrintBlankPrinterSpreads { xsd:boolean }?, element Properties { element PageRange { (enum_type, PageRange_EnumValue) | (string_type, xsd:string) }? } ? }
