CjkGridPreference_Object = element CjkGridPreference { attribute ShowAllLayoutGrids { xsd:boolean }?, attribute ShowAllFrameGrids { xsd:boolean }?, attribute MinimumScale { xsd:double }?, attribute SnapToLayoutGrid { xsd:boolean }?, attribute ColorEveryNthCell { xsd:short }?, attribute SingleLineColorMode { xsd:boolean }?, attribute ICFMode { xsd:boolean }?, attribute UseCircularCells { xsd:boolean }?, attribute ShowCharacterCount { xsd:boolean }?, element Properties { element LayoutGridColorIndex { InDesignUIColorType_TypeDef }? } ? }
